### PR TITLE
fix: custom expect messages for expect.extend matchers

### LINKED ISSUE #8366: Custom Expect messages are not displayed for custom matchers
### Describe the bug

When passing the `message` parameter to the `expect` function, the message does not get included in the final error if the called matcher was defined using the `expect.extend` function.

### Reproduction

https://stackblitz.com/edit/vitest-custom-expect-message-bug?file=test%2FcustomMatcher.test.ts

### System Info

```shell
System:
    OS: macOS 15.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 3.55 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    pnpm: 9.1.1 - ~/.nvm/versions/node/v20.13.1/bin/pnpm
  Browsers:
    Chrome: 138.0.7204.169
    Safari: 18.5
  npmPackages:
    @vitejs/plugin-vue: 5.2.3 => 5.2.3 
    @vitest/coverage-v8: 3.2.4 => 3.2.4 
    @vitest/ui: 3.2.4 => 3.2.4 
    vite: 6.3.2 => 6.3.2 
    vitest: 3.2.4 => 3.2.4 
    vitest-sonar-reporter: 2.0.1 => 2.0.1
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by lzl0304**
### Description

When passing a message parameter to expect(), the custom message was not
included in the final error for matchers defined using expect.extend().

fixes #8366 

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [x] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [x] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/expect/src/jest-extend.ts [hunk 1]
```diff
@@ -85,15 +87,21 @@ function JestExtendPlugin(
             const thenable = result as PromiseLike<SyncExpectationResult>
             return thenable.then(({ pass, message, actual, expected }) => {
               if ((pass && isNot) || (!pass && !isNot)) {
-                throw new JestExtendError(message(), actual, expected)
+                const errorMessage = customMessage
+                  ? `${customMessage}: ${message()}`
```
Comment (sheremet-va) [inline packages/expect/src/jest-extend.ts]: default matchers ignore the matcher message in this case, so I think we should also ignore it here


```suggestion
                  ? customMessage
```

File: packages/expect/src/jest-extend.ts [hunk 2]
```diff
@@ -85,15 +87,21 @@ function JestExtendPlugin(
             const thenable = result as PromiseLike<SyncExpectationResult>
             return thenable.then(({ pass, message, actual, expected }) => {
               if ((pass && isNot) || (!pass && !isNot)) {
-                throw new JestExtendError(message(), actual, expected)
+                const errorMessage = customMessage
```
Comment (sheremet-va) [inline packages/expect/src/jest-extend.ts]:
```suggestion
                const errorMessage = customMessage != null
```

**Review by sheremet-va — CHANGES_REQUESTED** [review]

File: packages/expect/src/jest-extend.ts (hunk 2 above)
Comment (lzl0304) [reply packages/expect/src/jest-extend.ts]: Thanks for the review! I've applied the suggested changes.

File: packages/expect/src/jest-extend.ts [hunk 3]
```diff
@@ -85,15 +87,21 @@ function JestExtendPlugin(
...
               }
             })
           }
 
           const { pass, message, actual, expected } = result as SyncExpectationResult
 
           if ((pass && isNot) || (!pass && !isNot)) {
-            throw new JestExtendError(message(), actual, expected)
+            const errorMessage = customMessage != null
+              ? `${customMessage}: ${message()}`
```
Comment (sheremet-va) [inline packages/expect/src/jest-extend.ts]: Missed this line

File: test/core/test/expect.test.ts [hunk 4]
```diff
@@ -389,3 +389,39 @@ describe('Temporal equality', () => {
...
   })
 })
+
+describe('expect with custom message', () => {
+  test('built-in matcher throws custom message on failure', () => {
+    expect(() => expect(1, 'custom message').toBe(2)).toThrow('custom message')
+  })
+
+  test('custom matcher with expect.extend throws custom message on failure', () => {
+    expect.extend({
```
Comment (sheremet-va) [inline test/core/test/expect.test.ts]: Doesn't seem like there is a test for async matcher

File: test/core/test/expect.test.ts [hunk 5]
```diff
@@ -389,3 +389,39 @@ describe('Temporal equality', () => {
     })
   })
 })
+
+describe('expect with custom message', () => {
+  test('built-in matcher throws custom message on failure', () => {
+    expect(() => expect(1, 'custom message').toBe(2)).toThrow('custom message')
+  })
+
+  test('custom matcher with expect.extend throws custom message on failure', () => {
```
Comment (sheremet-va) [inline test/core/test/expect.test.ts]: Maybe let's use this so global expect is not polluted


```suggestion
  test('custom matcher with expect.extend throws custom message on failure', ({ expect }) => {
```

**Review by sheremet-va — CHANGES_REQUESTED** [review]

File: test/core/test/expect.test.ts (hunk 4 above)
Comment (lzl0304) [reply test/core/test/expect.test.ts]: Thank you for the review! I've added comprehensive tests for async matchers with custom messages. If there are any gaps or additional scenarios you'd like me to cover, I'm happy to add more tests!

**Review by sheremet-va — APPROVED** [review]
