### PR TITLE
fix: --project negation excludes browser instances

### LINKED ISSUE #9977: Negated project filtering (`!`) broken on browser projects
### Describe the bug

When running vitest against a config with multiple vitest projects, filtering out browser projects (with the negation/`!` operator) does not work. The expected behaviour and current behaviour over various filtering scenarios is laid out in the following table:

| filter               | expected # of tests | actual # of tests | result |
| -------------------- | ------------------- | ----------------- | ------ |
| *none*               | 2                   | 2                 | 🟢     |
| `--project node`     | 1                   | 1                 | 🟢     |
| `--project browser`  | 1                   | 1                 | 🟢     |
| `--project !node`    | 1                   | 1                 | 🟢     |
| `--project !browser` | 1                   | 2                 | 🔴     |

These are the above results executed on the attached reproduction:

Image

### Reproduction

https://github.com/james-camilleri/vitest-project-filtering-reproduction

### System Info

```shell
System:
    OS: Windows 11 10.0.26200
    CPU: (16) x64 AMD Ryzen AI 7 PRO 350 w/ Radeon 860M
    Memory: 3.13 GB / 23.65 GB
  Binaries:
    Node: 24.14.1 - C:\Users\JamesCamilleri\scoop\apps\nodejs-lts\current\node.EXE
    Yarn: 1.22.22 - C:\Users\JamesCamilleri\scoop\apps\nodejs-lts\current\bin\yarn.CMD
    npm: 11.11.0 - C:\Users\JamesCamilleri\scoop\apps\nodejs-lts\current\npm.CMD
    pnpm: 10.33.0 - C:\Users\JamesCamilleri\scoop\shims\pnpm.EXE
    Deno: 2.7.7 - C:\Users\JamesCamilleri\scoop\shims\deno.EXE
  Browsers:
    Edge: Chromium (145.0.3800.82)
  npmPackages:
    @vitest/browser-playwright: ^4.1.2 => 4.1.2
    vite: ^8.0.1 => 8.0.3
    vitest: ^4.1.2 => 4.1.2
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### LINKED ISSUE #10130: --project='!name' doesn't exclude browser project instances
## Describe the bug

`--project='!name'` negation patterns do not exclude browser-based projects because browser instances get a derived name with a suffix (e.g. `project-b (chromium)`), which doesn't match the negation regex.

Positive selection works correctly. Negation works for non-browser projects.

## Reproduction

https://github.com/felamaslen/vitest-project-exclude-repro

```bash
git clone https://github.com/felamaslen/vitest-project-exclude-repro.git
cd vitest-project-exclude-repro
npm install
npx playwright install chromium
```

Positive selection works:

```bash
npx vitest run --project=project-a
# Test Files  1 passed (1)
# Tests       1 passed (1)
```

Negation does not exclude the browser project:

```bash
npx vitest run '--project=!project-b'
# ✓ |project-a| a.test.ts > project-a test
# ✓ |project-b (chromium)| b.test.ts > project-b test
# Test Files  2 passed (2)
# Tests       2 passed (2)
```

**Expected:** 1 test file (only `project-a`).
**Actual:** 2 test files (both run).

## Cause

Browser projects create instances with derived names like `project-b (chromium)`. The negation regex `^(?!project\-b$)` anchors to end-of-string, so it doesn't match `project-b (chromium)`, and the instance passes through the filter.

## Workaround

Adding a trailing wildcard works:

```bash
npx vitest run '--project=!project-b*'
# Test Files  1 passed (1)
# Tests       1 passed (1)
```

## System Info

- vitest: 4.1.4
- @vitest/browser-playwright: 4.1.4
- OS: macOS (arm64)
- Node: v22

### PR DESCRIPTION
**Pull request by felamaslen**
## Description

`--project='!name'` did not exclude browser project instances because they have derived names like `name (chromium)`. The instance-level filtering would re-check each derived name against the negation regex, which didn't match, so the instances passed through.

When the original project name is explicitly excluded by a negation filter, all its browser instances are now excluded without falling through to per-instance filtering.

Fixes #10130

## Reproduction

https://github.com/felamaslen/vitest-project-exclude-repro

## Changes

- **`core.ts`**: Added `isExcludedByProjectFilter()` which checks if a name is explicitly matched by a negation pattern (e.g. `--project='!name'`)
- **`resolveProjects.ts`**: When the original project name is excluded by negation, return empty instances instead of falling through to per-instance filtering

### CODE REVIEW

File: packages/vitest/src/node/core.ts [hunk 1]
```diff
@@ -1643,6 +1643,24 @@ export class Vitest {
       return regexp.test(name)
     })
   }
+
+  /**
+   * Check if the project with a given name is explicitly excluded
+   * by a negation pattern (e.g. `--project='!name'`).
+   */
+  isExcludedByProjectFilter(name: string): boolean {
```
Comment (sheremet-va) [inline packages/vitest/src/node/core.ts:1648]: This should not be a public method. See how internal methods are handled in the file

File: packages/vitest/src/node/projects/resolveProjects.ts [hunk 2]
```diff
@@ -217,13 +217,17 @@ export async function resolveBrowserProjects(
...
-    const filteredInstances = vitest.matchesProjectFilter(originalName)
-      ? instances
-      : instances.filter((instance) => {
-          const newName = instance.name! // name is set in "workspace" plugin
-          return vitest.matchesProjectFilter(newName)
-        })
+    // if original name is explicitly excluded by a negation filter, exclude all instances
+    // if original name matches a positive filter, keep all instances
+    // otherwise, filter instances individually (user may target a specific instance name)
+    const filteredInstances = vitest.isExcludedByProjectFilter(originalName)
```
Comment (sheremet-va) [inline packages/vitest/src/node/projects/resolveProjects.ts]: This should be done earlier, on L215

**Review by sheremet-va — CHANGES_REQUESTED** [review]
This needs tests. See test/cli/browser-configs for examples

File: packages/vitest/src/node/projects/resolveProjects.ts (hunk 2 above)
Comment (felamaslen) [reply packages/vitest/src/node/projects/resolveProjects.ts]: https://github.com/vitest-dev/vitest/pull/10131/commits/132358c76d31addd368373aee1e38849bf0e02d1

File: packages/vitest/src/node/core.ts (hunk 1 above)
Comment (felamaslen) [reply packages/vitest/src/node/core.ts:1648]: https://github.com/vitest-dev/vitest/pull/10131/commits/132358c76d31addd368373aee1e38849bf0e02d1

**Comment by felamaslen** [comment]
Thanks for feedback - addressed

**Review by sheremet-va — APPROVED** [review]

**Review by AriPerkkio — APPROVED** [review]
