### PR TITLE
fix(inline-snapshots): detect linebreaks

### LINKED ISSUE #1134: Inline snapshots with line breaks are unstable
### Describe the bug

Test below keeps failing when run. It passes right after the snapshot is updated but fails immediately on the next run. Snapshot update doesn't actually change any content. I think `vitest` doesn't handle line changes properly when comparing inline snapshots.

```ts
import { expect, test } from 'vitest';

/*
 * - npm run test
 * - Error -> Snapshot has changed. Press u
 * - Snapshot is updated, test passes. Press enter to re-run
 * - Error -> Snapshot has changed. Repeat previous steps...
 */

test('unstable snapshot', () => {
  expect(() => {
    throw new Error(['First line', 'Second line'].join('\n'));
  }).toThrowErrorMatchingInlineSnapshot(`
    "First line
    Second line"
  `);
});
```

https://user-images.githubusercontent.com/14806298/162612663-002cd153-ad18-42e3-b5df-cf14a3acd5b3.mp4

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-kxavky?file=test/basic.test.ts

### System Info

```shell
Default Stackblitz environment.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by AriPerkkio**
Fixes #1134

There is one unrelated typo fix commit and one test regression commit. I'm happy to move those into separate PR if needed.

### CODE REVIEW

File: packages/vitest/src/integrations/snapshot/port/utils.ts [hunk 1]
```diff
@@ -161,17 +161,17 @@ export async function saveSnapshotFile(
 
 export function prepareExpected(expected?: string) {
   function findStartIndent() {
-    const match = /^( +)}\s+$/m.exec(expected || '')
+    const match = /^( +)[}|"]/m.exec(expected || '')
```
Comment (AriPerkkio) [inline packages/vitest/src/integrations/snapshot/port/utils.ts:164]: I'm quite unsure what this was supposed to do earlier:


`^( +)}\s+$`

- `^` From the beginning
- `( +)` Capture at least one space...
- `}` ... before } character
- `\s+$` ... only when whole expression ends with whitespaces

... right?

Should this have been without `^` instead?

Comment (AriPerkkio) [reply packages/vitest/src/integrations/snapshot/port/utils.ts]: Just realized there's the `m` modifier for multilines. Applied required changes for this.
