### PR TITLE
fix (ui): rerun individually tests with special chars in name

### LINKED ISSUE #7671: Tests with Special Characters in Test Name Don't Rerun Individually in Vitest UI
### Describe the bug

When using the Vitest UI, tests that have special characters like (), [], or similar in their test name cannot be rerun individually by clicking the "Run" button. Instead, only the "Rerun All" button at the top works. Instead the following error message appears:

```
RERUN  rerun test 
        Test name pattern: /Square root of nine (9)/

No test files found. You can change the file name pattern by pressing "p"

include: **/*.{test,spec}.?(c|m)[jt]s?(x)
exclude:  **/node_modules/**, **/dist/**, **/cypress/**, **/.{idea,git,cache,output,temp}/**, **/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*
```

This issue seems similar to vitest-dev/vscode#93, where the problem was resolved by escaping testNamePattern using:
> testNamePattern.replace(/[$^+?()[\]]/g, '\\$&')

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-8b9barmz?file=test%2Fbasic.test.ts

### System Info

```shell
System:
    OS: Linux 6.11 Ubuntu 24.04.2 LTS 24.04.2 LTS (Noble Numbat)
  Binaries:
    Node: 23.6.1
    npm: 10.9.2
  Browsers:
    Brave Browser: 134.1.76.73
  npmPackages:
    @vitejs/plugin-react-swc: ^3.8.0 => 3.8.0
    @vitest/browser: ^3.0.8 => 3.0.8
    playwright: ^1.51.0 => 1.51.0
    vite: ^6.2.0 => 6.2.1
    vitest: ^3.0.8 => 3.0.8
    vitest-browser-react: ^0.1.1 => 0.1.1
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by DevJoaoLopes**
### Description

Closes #7671 

Fixes behavior where it was not possible to click 'rerun' in the ui in tests with special characters.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by DevJoaoLopes** [comment]
@hi-ogawa For some reason that I haven't discovered yet, the pipeline jobs are breaking (I've even tried to go back to the implementation and it didn't work)

**Comment by sheremet-va** [comment]
> @hi-ogawa For some reason that I haven't discovered yet, the pipeline jobs are breaking (I've even tried to go back to the implementation and it didn't work)

You are adding tests to UI, but don't test them in the actual spec. UI tests expect a specific number of tests.

File: packages/vitest/src/node/core.ts [hunk 1]
```diff
@@ -906,7 +906,17 @@ export class Vitest {
       this.filenamePattern = undefined
     }
 
-    const testNamePattern = pattern ? new RegExp(pattern) : undefined
+    const validatePatternWithReplaceChars = () => {
+      if (!pattern) {
+        return undefined
+      }
+
+      return /[()[\]{}]/.test(pattern)
```
Comment (sheremet-va) [inline packages/vitest/src/node/core.ts:914]: 1. This is the correct regexp:

```ts
function escapeRegex(str: string) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}
```

2. It should be applied on the UI side in case someone wants to use the actual regexp in CLI

**Review by sheremet-va — CHANGES_REQUESTED** [review]

File: packages/vitest/src/node/core.ts (hunk 1 above)
Comment (DevJoaoLopes) [reply packages/vitest/src/node/core.ts:914]: Got it, thanks for the help @sheremet-va 

What do you think about the following approach:

Instead of trying to change task.name directly in ExplorerItem.vue, change the parameter passed in rerunTask using a ternary?

```ts
async rerunTask(id: string): Promise<void> {
    const task = this.state.idMap.get(id)
    if (!task) {
      throw new Error(`Task ${id} was not found`)
    }

    const taskNamePattern = this.config.ui ? task.name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') : task.name

    await this.changeNamePattern(
      taskNamePattern,
      [task.file.filepath],
      'tasks' in task ? 'rerun suite' : 'rerun test',
    )
  }
  ```

**Comment by DevJoaoLopes** [comment]
> > @hi-ogawa For some reason that I haven't discovered yet, the pipeline jobs are breaking (I've even tried to go back to the implementation and it didn't work)
> 
> You are adding tests to UI, but don't test them in the actual spec. UI tests expect a specific number of tests.

@sheremet-va I don't know if I understood very well, should I also change the spec.ts files?

**Comment by sheremet-va** [comment]
> > > @hi-ogawa For some reason that I haven't discovered yet, the pipeline jobs are breaking (I've even tried to go back to the implementation and it didn't work)
> > 
> > 
> > You are adding tests to UI, but don't test them in the actual spec. UI tests expect a specific number of tests.
> 
> @sheremet-va I don't know if I understood very well, should I also change the spec.ts files?

Your spec file doesn't test anything. To test that test is running, you need to write a test that clicks on the run button

File: packages/vitest/src/node/core.ts (hunk 1 above)
Comment (sheremet-va) [reply packages/vitest/src/node/core.ts:914]: Why can't we just do it in UI?

**Comment by DevJoaoLopes** [comment]
> > > > @hi-ogawa For some reason that I haven't discovered yet, the pipeline jobs are breaking (I've even tried to go back to the implementation and it didn't work)
> > > 
> > > 
> > > You are adding tests to UI, but don't test them in the actual spec. UI tests expect a specific number of tests.
> > 
> > 
> > @sheremet-va I don't know if I understood very well, should I also change the spec.ts files?
> 
> Your spec file (https://github.com/vitest-dev/vitest/pull/7707/files#diff-5759d01c34f2a4853324b490d41dfd7a0d497eb9ebe315ec5ab1df335964c6a9R10) doesn't test anything.
> 
> To test that regexp is applied correctly, you need to write a test that clicks on the run button

sure... I removed these scenarios (which were not validating anything) and I will rewrite more assertive tests.

File: packages/vitest/src/node/core.ts (hunk 1 above)
Comment (DevJoaoLopes) [reply packages/vitest/src/node/core.ts]: Done

**Review by sheremet-va — APPROVED** [review]

**Comment by sheremet-va** [comment]
Thanks! Seems to work fine
