### PR TITLE
fix: open browser in `--standalone` mode without running tests

### LINKED ISSUE #9901: Allow idle start for Browser Mode
### Clear and concise description of the problem

We want to adopt the Vitest Browser Mode, but as far as I can tell it is not possible to start it in some kind of "idle" mode during development. Whenever I start the Browser Mode (not headless; using watch mode) it automatically starts **all** tests.

Regular Vitest tests seem to have the `--standalone` option exactly for this use case. (So maybe this can also be considered as a bug, that browser mode doesn't respect the `--standalone` setting?)

### Suggested solution

Allow using `--standalone` in browser mode. When run non-headless the UI opens, but not test will automatically run - only on manual interaction.

### Alternative

Introduce a dedicated flag like `--browser.idle`, if we don't want to reuse `--standalone`.

### Additional context

Other testing tools that provide a UI (usually E2E testing tools like Cypress and Playwright) have similar behaviour. They open in a view where the developer can choose to run all tests or some tests manually. I'd like to support a similar workflow when I onboard other devs to vitest.

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by sheremet-va**
### Description

Resolves #9901

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [ ] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/vitest/src/node/core.ts [hunk 1]
```diff
@@ -794,11 +794,19 @@ export class Vitest {
...
+    this.logger.deprecate('`vitest.init()` is deprecated. Use `vitest.standalone()` instead.')
+    return this.standalone()
+  }
+
   /**
    * Initialize reporters and the coverage provider. This method doesn't run any tests.
    * If the `--watch` flag is provided, Vitest will still run changed tests even if this method was not called.
    */
-  async init(): Promise<void> {
+  async standalone(): Promise<void> {
```
Comment (AriPerkkio) [inline packages/vitest/src/node/core.ts:809]: Reporter's documentation about `onInit` also needs changes https://vitest.dev/api/advanced/reporters.html#oninit

> Internally this method is called inside `vitest.start`, `vitest.init` or `vitest.mergeReports`

**Review by AriPerkkio — APPROVED** [review]

**Review by hi-ogawa — APPROVED** [review]
