### PR TITLE
fix(browser): failing to load vitest/utils

### LINKED ISSUE #3124: Browser mode hanging on blank white screen, failing to load vitest/utils
### Describe the bug

When trying to run a test in browser mode (playwright) with a basic example next.js application, the browser window opens but hangs on a blank screen and fails to load vitest/utils in the background.

Screenshot 2023-04-03 at 21 17 38

### Reproduction

Reproduction repository, based on vitest next.js example: https://github.com/ludwigbacklund/vitest-browser-bug-repro

Just run `yarn test`, it will open a browser window and hang on a white screen. Check the console/network log.

### System Info

```shell
System:
    OS: macOS 13.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 774.77 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nodenv/versions/16.13.1/bin/node
    Yarn: 1.22.15 - ~/.nodenv/versions/16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nodenv/versions/16.13.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Safari: 16.4
  npmPackages:
    @vitejs/plugin-react: latest => 3.1.0 
    @vitest/browser: ^0.29.8 => 0.29.8 
    vitest: latest => 0.29.8
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by userquin**
Added test here https://github.com/userquin/vitest-browser-vue/tree/vite-4.3-vitest-pr with local browser copy of this PR.

EDIT: we've a working example with local browser copy of this PR on `anu-vue` repo (`vitest-browser-mode` branch): https://github.com/jd-solanki/anu/tree/vitest-browser-mode/packages/anu-vue

closes #3124

### CODE REVIEW

**Comment by userquin** [comment]
On my Windows laptop browser test working:

<details>
<summary>test/browser output</summary>

```shell
D:\work\projects\userquin\GitHub\antfu\vitest-fix-browser\test\browser>nr test

> @vitest/test-browser@ test D:\work\projects\userquin\GitHub\antfu\vitest-fix-browser\test\browser
> pnpm run test:webdriverio && pnpm run test:playwright


> @vitest/test-browser@ test:webdriverio D:\work\projects\userquin\GitHub\antfu\vitest-fix-browser\test\browser
> PROVIDER=webdriverio node --test specs/

TAP version 13
# Subtest: D:\\work\\projects\\userquin\\GitHub\\antfu\\vitest-fix-browser\\test\\browser\\specs\\runner.test.mjs
ok 1 - D:\\work\\projects\\userquin\\GitHub\\antfu\\vitest-fix-browser\\test\\browser\\specs\\runner.test.mjs
  ---
  duration_ms: 7.7818393
  ...
1..1
# tests 1
# pass 1
# fail 0
# cancelled 0
# skipped 0
# todo 0
# duration_ms 7.805842

> @vitest/test-browser@ test:playwright D:\work\projects\userquin\GitHub\antfu\vitest-fix-browser\test\browser
> PROVIDER=playwright node --test specs/

# tests 1
# pass 1
# fail 0
# cancelled 0
# skipped 0
# todo 0
# duration_ms 4.6533121
```
</details>

**Comment by userquin** [comment]
Maybe we should remove the timestamp from the requests, check my latest comments on the issue.

File: packages/browser/src/node/index.ts [hunk 1]
```diff
@@ -39,17 +40,53 @@ export default (base = '/'): Plugin[] => {
...
+              useId = useId.replace(/\\/g, '/')
+          }
+
           return
+        }
 
         id = normalizeId(id)
         return { id: await polyfillPath(id), moduleSideEffects: false }
       },
+      async load(id) {
```
Comment (userquin) [inline packages/browser/src/node/index.ts:78]: remove this

**Comment by userquin** [comment]
I have no dea what's happening with CI tests, on my local working properly.
