### PR TITLE
fix: don't resolve `setupFiles` from parent directory

### LINKED ISSUE #9955: Fails to run with `setupFile` when inside git worktree
### Describe the bug

Using vitest inside a git worktree fails because it resolves the `setupFile` from the wrong folder.

Vitest's `resolvePath(path, root)` calls `resolveModule(path, { paths: [root] })`. Internally, root is converted to a file URL without a trailing slash (`file:///.../.worktree`). Per URL spec, resolving `./setup.js` against that URL treats `.worktre` as a filename and resolves to the parent directory — so it finds and returns the main repo's setup.js instead of the worktree's.

### Reproduction

1. Create a repo with vitest + a setup file
  ```sh
  mkdir /tmp/vitest-worktree-bug && cd /tmp/vitest-worktree-bug
  git init
  echo "node_modules" > .gitignore
  echo '{"type":"module","dependencies":{"vitest":"3.2.1"}}' > package.json
  ```
2. Add a `vitest.config.mjs` file
  ```js
  import { defineConfig } from 'vitest/config';
  export default defineConfig({ test: { setupFiles: ['./setup.js'] } });
  ```
3. Add `setup.js`
  ```js
  globalThis.__SETUP_LOCATION = 'MAIN REPO';
  ```
4. Add a dummy test file
  ```js
  import { test, expect } from 'vitest';
  test('should load setup from worktree', () => {
    expect(globalThis.__SETUP_LOCATION).toBe('WORKTREE');
  });
  ```
5. Run `npm install && git add -A && git commit -m "initial"`
6. Create a worktree _inside_ the repo:
  ```sh
  git branch worktree-branch
  git worktree add .worktree worktree-branch
  ```
7. In the worktree change `setup.js`
  ```js
  globalThis.__SETUP_LOCATION = 'WORKTREE';
  ```
8. Run `npm install` inside the worktree
9. Run `npx vitest run` inside the worktree

```sh
# FAILS: expected 'MAIN REPO' to be 'WORKTREE'
```

### System Info

```shell
System:
  OS: macOS 26.3.1
  CPU: (8) arm64 Apple M1
  Memory: 103.16 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 24.9.0 - /Users/marvinhagemeister/.nvm/versions/node/v24.9.0/bin/node
  Yarn: 1.22.22 - /opt/homebrew/bin/yarn
  npm: 11.6.0 - /Users/marvinhagemeister/.nvm/versions/node/v24.9.0/bin/npm
  pnpm: 10.26.0 - /Users/marvinhagemeister/Library/pnpm/pnpm
  bun: 1.3.3 - /Users/marvinhagemeister/.bun/bin/bun
  Deno: 2.6.10 - /Users/marvinhagemeister/.deno/bin/deno
  Watchman: 2025.03.10.00 - /opt/homebrew/bin/watchman
Browsers:
  Chrome: 146.0.7680.80
  Chrome Canary: 148.0.7749.0
  Firefox: 148.0.2
  Safari: 26.3.1
npmPackages:
  vitest: 4.1.0 => 4.1.0
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

- Closes https://github.com/vitest-dev/vitest/issues/9955

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [ ] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/vitest/src/node/config/resolveConfig.ts [hunk 1]
```diff
@@ -29,8 +29,17 @@ import { BaseSequencer } from '../sequencers/BaseSequencer'
...
+  // /some/file.js
+  // /some/root/file
+  // /some/root/file.js
+  // etc.
+  // but we don't want to resolve files from parent directories,
+  // so we ensure passing "/" suffix such as "/some/root/"
+  // https://github.com/unjs/mlly/blob/401d42983f6f3a9112658d67b0a92ba4fb1d7efa/src/resolve.ts#L104-L110
   return normalize(
-    /* @__PURE__ */ resolveModule(path, { paths: [root] })
+    /* @__PURE__ */ resolveModule(path, { paths: [join(root, '/')] })
```
Comment (hi-ogawa) [inline packages/vitest/src/node/config/resolveConfig.ts:42]: This was a way more annoying than I thought. My first solution was merely doing:

```js
if (path[0] === '.' || path[0] === '/') {
  return normalize(resolve(root, path))
}
return (...same as before...)
```

but this broke a following test since it was relying on `resolveModule` to resolve `/(full)/file-setup.js`:

https://github.com/vitest-dev/vitest/blob/a712b9c6b08e3ef934d4f680868b27f2428c6d9d/test/config/fixtures/inline-setup-file/vitest.config.js#L3-L9

So, I went back to still rely on `resolveModule` for relative path.

**Review by sheremet-va — APPROVED** [review]
