### PR TITLE
fix(vite-node): coerce to string in import(dep)

### LINKED ISSUE #3429: __vite_ssr_dynamic_import__ doesn't coerce import(specifier) to a string
### Describe the bug

If you pass in a non-string into an import statement when using Vitest, you'll get a cryptic "id.startsWith is not a function" message. I think this is due to the custom `__vite_ssr_dynamic_import__()` function that seems to replace all `import()` stuff not properly doing ``myArg = `${myArg}`;`` like browsers and Node.js do natively to make sure the arg is a true string.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-mamgrv?file=test%2Fbasic.test.ts

image

### System Info

```shell
~/projects/vitest-dev-vitest-mamgrv 1m 15s
❯ npx envinfo --system --npmPackages '{vitest,@vitest/*,vite,@vitejs/*}' --binaries --browsers
success Install finished in 0.928s


  System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitest/ui: latest => 0.31.1 
    vite: latest => 4.3.8 
    vitest: latest => 0.31.1 
```
```


### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by jcbhmr**
This PR would...
- Coerce `dep` to string using the string coercion algorithm in `import(dep)`

Need to use `` `${s}` `` instead of `"" + s` in order to get the right hint in `Symbol.toPrimitive`

> ```js
> const obj2 = {
>   [Symbol.toPrimitive](hint) {
>     if (hint === "number") {
>       return 10;
>     }
>     if (hint === "string") {
>       return "hello";
>     }
>     return true;
>   },
> };
> console.log(+obj2); // 10        — hint is "number"
> console.log(`${obj2}`); // "hello"   — hint is "string"
> console.log(obj2 + ""); // "true"    — hint is "default"
> ```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toPrimitive#description

closes  #3429 

-----
<a href="https://stackblitz.com/~/github.com/jcbhmr/vitest/tree/jcbhmr%2Fissue3429">Review PR in StackBlitz Codeflow</a> _Submitted with [StackBlitz Codeflow](https://stackblitz.com/~/github.com/jcbhmr/vitest/tree/jcbhmr%2Fissue3429)._

### CODE REVIEW

File: packages/vite-node/src/client.ts [hunk 1]
```diff
@@ -267,6 +267,7 @@ export class ViteNodeRunner {
     const mod = this.moduleCache.getByModuleId(moduleId)
 
     const request = async (dep: string) => {
+      dep = `${dep}`
```
Comment (sheremet-va) [inline packages/vite-node/src/client.ts:270]:
```suggestion

```

File: packages/vite-node/src/client.ts [hunk 2]
```diff
@@ -267,6 +267,7 @@ export class ViteNodeRunner {
...
       const [id, depFsPath] = await this.resolveUrl(dep, fsPath)
```
Comment (sheremet-va) [inline packages/vite-node/src/client.ts:271]:
```suggestion
      const [id, depFsPath] = await this.resolveUrl(`${dep}`, fsPath)
```

**Review by sheremet-va — CHANGES_REQUESTED** [review]

**Review by sheremet-va — CHANGES_REQUESTED** [review]
Can you add a test case for this, please?

**Comment by jcbhmr** [comment]
Added a test case:

```ts
test('dynamic import coerces to string', async () => {
  const dataUri = 'data:text/javascript;charset=utf-8,export default "hi"'
  const { default: hi } = await import({ toString: () => dataUri } as string)
  expect(hi).toBe('hi')
})
```
