### PR TITLE
fix(mocker)!: deserialize automock as automock

### LINKED ISSUE #9706: `vi.mock()` does not replace the modules implementation in browser mode
### Describe the bug

`vi.mock('some-module')` calls do not replace the modules implementation when running in browser mode. Instead, they appear to behave as if `vi.mock('some-module', {spy: true})` was used and wrap the original implementation in spys.

As a workaround, you can setup empty mocks using a factory function or by importing the mocked functions and giving them a new `mockImplementation`

### Reproduction

https://github.com/bimbiltu/vitest-browser-mock-repro

This repo has 3 simple files:
```ts
// src/answer.ts
export const answer = () => 42;
```

```ts
// src/getTheAnswer.ts
import { answer } from './answer';
export const getTheAnswer = () => answer();
```

```ts
import { it, expect, vi } from 'vitest';
import { getTheAnswer } from './getTheAnswer';
import { answer } from './answer';

vi.mock('./answer')

// fails but should pass
it('should not return 42 when the answer module is mocked', () => {
  expect(getTheAnswer()).not.toBe(42);
});

it('should replace answer with a mock', () => {
  getTheAnswer();
  expect(answer).toHaveBeenCalled();
});
```

### System Info

```shell
System:
    OS: macOS 26.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.58 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.13.1 - /Users/USER/.asdf/installs/nodejs/24.13.1/bin/node
    Yarn: 1.22.22 - /Users/USER/.asdf/installs/nodejs/24.13.1/bin/yarn
    npm: 11.8.0 - /Users/USER/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.9.2 - /opt/homebrew/bin/pnpm
    Watchman: 2025.08.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 145.0.7632.77
    Firefox: 140.7.0
    Safari: 26.3
  npmPackages:
    @vitest/browser-playwright: ^4.0.18 => 4.0.18
    vitest: ^4.0.18 => 4.0.18
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by nami8824**
### Description

Resolves #9706

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [x] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [x] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: test/cli/fixtures/mocker/autospy/index.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import { mocker } from 'virtual:mocker'
 import { calculate } from './test'
 
-mocker.customMock(import('./test'))
+mocker.customMock(import('./test'), { spy: true })
```
Comment (nami8824) [inline test/cli/fixtures/mocker/autospy/index.js:4]: This fix caused the `"autospy works correctly"` test case in `test/cli/test/public-mocker.test.ts` to fail, because the automock was no longer being deserialized as a spy. To fix it, I added `{ spy: true }` to the `mocker.customMock()` call in the autospy fixture. I think passing `{ spy: true }` explicitly is the correct behavior here.

**Review by sheremet-va — APPROVED** [review]
