### PR TITLE
fix: automatically remove define related configuration

### LINKED ISSUE #3550: "vitest" command getting `TypeError: Cannot use 'in' operator to search for 'NO_COLOR' in undefined at chunk-colors
### Describe the bug

When I run the command vitest, I get the error;

TypeError: Cannot use 'in' operator to search for 'NO_COLOR' in undefined
 ❯ createColors node_modules/@vitest/utils/dist/chunk-colors.js:47:66
 ❯ setupGlobalEnv node_modules/vitest/dist/entry.js:53:15
 ❯ run node_modules/vitest/dist/entry.js:242:3
 ❯ run node_modules/vitest/dist/worker.js:60:5
 ❯ async file:/Users/aysegulkavakli/WebstormProjects/metamax-console/node_modules/tinypool/dist/esm/worker.js:109:20

and no test files found. Including vitest version 0.28.5 and before is working fine.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-mafqkz?file=package.json,vite.config.ts&initialPath=__vitest__/

### System Info

```shell
System:
    OS: macOS Big Sur 11.5.2
  Binaries:
    Node: 16.14.0 - /usr/local/opt/node@16/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
  Browsers:
    Chrome: 113.0.5672.126
  yarnPackages:
    testing-library/react: 14.0.0,
    vitejs/plugin-react: 4.0.0,
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by btea**
fix #3550

### CODE REVIEW

File: packages/vitest/src/node/plugins/utils.ts [hunk 1]
```diff
@@ -32,3 +32,39 @@ export function resolveOptimizerConfig(testOptionc: DepsOptimizationOptions | un
   }
   return newConfig
 }
+
+export function deleteDefineConfig(viteConfig: ViteConfig) {
+  const defines: Record<string, any> = {}
+  if (viteConfig.define) {
+    delete viteConfig.define['import.meta.vitest']
+    delete viteConfig.define['process.env']
+    delete viteConfig.define.process
```
Comment (sheremet-va) [inline packages/vitest/src/node/plugins/utils.ts:41]: We should probably also remove `global`.

And having a test would be nice 😄 I think adding `define` in `test/core` and checking the value in a test should be fine.

**Review by sheremet-va — CHANGES_REQUESTED** [review]

File: packages/vitest/src/node/plugins/utils.ts (hunk 1 above)
Comment (btea) [reply packages/vitest/src/node/plugins/utils.ts:41]: ok, I have updated the code. 😄

**Review by sheremet-va — APPROVED** [review]
