### PR TITLE
fix(vite-node): improve import handling

### LINKED ISSUE #3693: Vitests resolves node:test to test
### Describe the bug

I have to use `node:test` along with vitest (as we use mocks outside of vitest testing, and vitest won't allow this).
However, when I `import { mock } from 'node:test';` vitest runner will throw the following error:
```
Error: Failed to load url test (resolved id: test). Does the file exist?
```

### Reproduction

Here is a minimal reproduction file:
```TS
import { describe, expect, it } from 'vitest';
import { mock } from 'node:test';

describe('mock issue reproduction', () => {
  it('should pass', () => {
    mock.fn(() => {});
    expect(true).toBe(true);
  });
});
```

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 49.69 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.volta/tools/image/node/20.2.0/bin/node
    Yarn: 3.4.1 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.6.6 - ~/.volta/tools/image/node/20.2.0/bin/npm
    pnpm: 6.26.1 - ~/.volta/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
```

For some reason envinfo won't give me the npm package versions so here you go:
```
"vitest": "^0.32.2"
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### LINKED ISSUE #3705: dynamic import of `conventional-changelog-angular` throws Promise `then` incompatible receiver object module
### Describe the bug

Calling `await import('conventional-changelog-angular')` works fine in real world usage, that is in [Lerna-Lite](https://github.com/lerna-lite/lerna-lite/), but throws an error when running unit test with Vitest. I have Renovate running once a week on the repo, here's the failing PR [job](https://github.com/lerna-lite/lerna-lite/actions/runs/5194419667/jobs/9366058308)

To give a little bit of a background, I maintain [Lerna-Lite](https://github.com/lerna-lite/lerna-lite) (a fork of Lerna but rewritten as ESM) and the latest version of `conventional-changelog-angular` (which is a breaking version), that came out a few weeks ago, migrated from the Q library to pure Promise (see their v6 [changelog](https://github.com/conventional-changelog/conventional-changelog/releases/tag/conventional-changelog-angular-v6.0.0)). 

The code and library works fine in real world usage (I previewed a release in Lerna-Lite and it works fine and I added console logs to make sure of it), so it only fails in Vitest but not outside of it.

### Reproduction

Here's a Stackblitz repro:
https://stackblitz.com/edit/vitest-dev-vitest-conventional?file=test%2Fbasic.test.ts

Calling this simple test

```ts
test('conventional-changelog-angular', async () => {
  let config = await import('conventional-changelog-angular');
  expect(config).toBeTruthy();
});
```

will throw

> TypeError: Method Promise.prototype.then called on incompatible receiver [object Module]

or in some cases it throws this other but similar error

> TypeError: Promise.prototype.then called on incompatible Proxy

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz  
    Memory: 18.79 GB / 31.93 GB
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD 
    npm: 7.0.11 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: 114.0.5735.199
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.58)
  npmPackages:
    @vitest/coverage-v8: ^0.32.2 => 0.32.2
    vitest: ^0.32.2 => 0.32.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
Closes #3693
Closes #3705

### CODE REVIEW

File: packages/vite-node/src/utils.ts [hunk 1]
```diff
@@ -51,6 +51,9 @@ export function isInternalRequest(id: string): boolean {
 }
 
 export function normalizeModuleId(id: string) {
+  // unique id that is not available as "test"
+  if (id === 'node:test')
+    return 'node:test'
```
Comment (antfu) [inline packages/vite-node/src/utils.ts:56]: Maybe we could maintain a list of passthrough ids?
