### PR TITLE
fix(coverage): reduce size of leftover v8 reports

### LINKED ISSUE #2108: Delete tmp directory from coverage report after running
### Clear and concise description of the problem

The `/coverage/tmp` directory is preserved after the code coverage report is finished. That's fine for local development, but it's not on CI when we need to publish the results to an analysis tool like CodeClimate.

For example, this is the size of the temp directory for a project I'm working on:
```bash
435M	coverage/tmp
4.9M	coverage/xxx-api
1.7M	coverage/coverage-final.json
988K	coverage/clover.xml
 84K	coverage/index.html
 20K	coverage/prettify.js
8.0K	coverage/sorter.js
8.0K	coverage/base.css
4.0K	coverage/sort-arrow-sprite.png
4.0K	coverage/prettify.css
4.0K	coverage/favicon.png
4.0K	coverage/block-navigation.js
```

### Suggested solution

Add an option to the coverage config to remove the tmp directory.

### Alternative

For now, I can remove the files after running the coverage script, like:
```json
  "test:coverage": "vitest run --coverage && rm -rf ./coverage/tmp"
```

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by AriPerkkio**
Closes #2108, hopefully.

### CODE REVIEW

File: packages/coverage-c8/src/provider.ts [hunk 1]
```diff
@@ -102,6 +102,12 @@ export class C8CoverageProvider implements CoverageProvider {
 
     await report.run()
     await checkCoverages(this.options, report)
+
+    // Note that this will only clean up the V8 reports generated so far.
```
Comment (AriPerkkio) [inline packages/coverage-c8/src/provider.ts:106]: More details about this here: https://github.com/vitest-dev/vitest/issues/2108#issuecomment-1276557168

**Review by sheremet-va — APPROVED** [review]
