### PR TITLE
fix: remove undefined values in options

### LINKED ISSUE #2153: "Patterns must be a string" error when passing `undefined` to `include` option
### Describe the bug

The types for the `include` and `exclude` options allow for passing `undefined` as the value.
This is very nice since it allows for applying the option conditionally very easily.
```ts
{
  include: testSSR ? ["server.test.{ts,tsx}"] : undefined
}
```
But this error appears in the console when trying to do this
```
TypeError: Patterns must be a string (non empty) or an array of strings
```
As a walkaround, I can do this, but it doesn't seem intentional...
```ts
{
  ...(testSSR && { include: ["server.test.{ts,tsx}"] })
}
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-atexbn?file=vite.config.ts

### System Info

```shell
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 920.68 MB / 7.79 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (106.0.1370.42)
    Internet Explorer: 11.0.19041.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by g4rry420**
Signed-off-by: GurkiranSingh <gurkiransinghk@gmail.com>

Resolves #2153
I have added a `removeUndefinedValues` function which removes any undefined values passed by the user from userConfig so that default values can be applied.

### CODE REVIEW

File: packages/vitest/src/node/plugins/index.ts [hunk 1]
```diff
@@ -12,6 +12,14 @@ import { MocksPlugin } from './mock'
 import { CSSEnablerPlugin } from './cssEnabler'
 import { CoverageTransform } from './coverageTransform'
 
+function removeUndefinedValues(obj: Record<string, any>) {
```
Comment (dammy001) [inline packages/vitest/src/node/plugins/index.ts:15]: Can you move this to `utils/base.ts` file

**Review by antfu — APPROVED** [review]

**Review by dammy001 — APPROVED** [review]
