### PR TITLE
fix: start tracking module resolution as soon as possible for easier tracking

### LINKED ISSUE #2552: Dynamic imports started failing in 0.26.0
### Describe the bug

I'm having problems with dynamic imports
* everything was working in 0.25.8
* everything is working in 0.26.2 when I run **individual** test files (`npx vitest run individualFile.test.js`)

The problem happens when I test multiple test files that have modules which dynamically import other modules:
```js
// For example
await import(`../../${sth}/${sthElse}.js`)
```

The problem doesn't happen all the time - sometimes the tests pass, sometimes they fails and it's not always the exact same tests that fail. It feels like there's some sort of race condition between the workers when they start loading dynamic modules.

I made sure to await in all places 
```js
test('sth', async () => {
  // render a component that has `async created()` that load dynamic modules 

  await flushPromises() 
  await vi.dynamicImportSettled()
  
  // expect the side effects of the dynamic imports to have happened
})  
```

### Reproduction

It's difficult to put together a reproduction because of the complexity of the project.
Any tips that would help narrow this down are welcome. 🙏 

I tried creating a repro but it's still not ready - couldn't reproduce the flaky failures.

However I bumped into **an interesting problem which may or may not be related**:
* starting the tests in watch mode works `npx vitest`
* running the tests once hangs (CPU 100%) `npx vitest run`

https://stackblitz.com/edit/vitest-dynamic-imports-issues

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.34 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.volta/tools/image/node/16.19.0/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 8.19.3 - ~/.volta/tools/image/node/16.19.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0.1
    Safari: 16.2
  npmPackages:
    @vitejs/plugin-vue: ^3.2.0 => 3.2.0
    vite: ^3.2.5 => 3.2.5
    vitest: ^0.26.2 => 0.26.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
Fixes #2552

I am not sure, if we should reuse `moduleCache` here, @antfu what do you think? I initially wanted to use original ID and update mod path to `fsPath`, but it complicates things too much, I think.

### CODE REVIEW

File: packages/vite-node/src/client.ts [hunk 1]
```diff
@@ -215,6 +215,18 @@ export class ViteNodeRunner {
     return [resolvedId, fsPath]
   }
 
+  async resolveUrl(id: string, importee?: string) {
+    const resolveKey = `resolve:${id}`
+    // put info about new import as soon as possible, so we can start tracking it
+    this.moduleCache.set(resolveKey, { resolving: true })
```
Comment (antfu) [inline packages/vite-node/src/client.ts:221]: ModuleCache's `set` will apply a normalization. Ideally, in this case, we could expose `_set` `_delete` without normalization to be used here, and avoid extra normalization costs.
