### PR TITLE
fix(browser): ensure setup files are re-evaluated on each test run (fixes #8883)

### LINKED ISSUE #8883: Setup files are not re-evaluated before each test file when disabling isolation in browser mode
### Describe the bug

Setup files are not re-evaluated when disabling isolation in browser mode due to caching.

### Reproduction

https://github.com/vitest-dev/vitest/pull/8884/files

### System Info

N/A

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by yjaaidi**
### Description

Resolves #8883 

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [X] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [X] Ideally, include a test that fails without this PR but passes with it.
- [X] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [X] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [X] Run the tests with `pnpm test:ci`.

### Documentation
- [X] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [X] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/browser/src/client/tester/runner.ts [hunk 1]
```diff
@@ -257,7 +257,9 @@ export function createBrowserRunner(
 
     importFile = async (filepath: string, mode: 'collect' | 'setup') => {
       let hash = this.hashMap.get(filepath)
-      if (!hash) {
+
+      // if the mode is setup, we need to re-evaluate the setup file on each test run
+      if (mode === 'setup' || !hash) {
         hash = Date.now().toString()
         this.hashMap.set(filepath, hash)
```
Comment (yjaaidi) [inline packages/browser/src/client/tester/runner.ts:264]: Given we want to cache bust, is it useful to populate the hashMap when mode is `setup`?

File: packages/browser/src/client/tester/runner.ts [hunk 2]
```diff
@@ -257,7 +257,9 @@ export function createBrowserRunner(
 
     importFile = async (filepath: string, mode: 'collect' | 'setup') => {
       let hash = this.hashMap.get(filepath)
-      if (!hash) {
+
+      // if the mode is setup, we need to re-evaluate the setup file on each test run
+      if (mode === 'setup' || !hash) {
```
Comment (yjaaidi) [inline packages/browser/src/client/tester/runner.ts:262]: Not sure if this is the right way but I tried to keep the change minimalistic.

File: test/browser/specs/runner.test.ts [hunk 3]
```diff
@@ -290,6 +290,13 @@ test('in-source tests run correctly when filtered', async () => {
   expect(stdout).toContain(`Tests  ${instances.length} passed`)
 })
 
+test('re-evaluate setupFiles on each test run even when isolate is false', async () => {
+  const { exitCode } = await runBrowserTests({
+    root: './fixtures/isolate-and-setup-file',
+  })
+  expect(exitCode).toBe(0)
```
Comment (sheremet-va) [inline test/browser/specs/runner.test.ts]: this needs a check similar to line 284 that confirms the file actually did run

Comment (yjaaidi) [reply test/browser/specs/runner.test.ts]: ✅ done

Oh! I didn't notice the who instances settings. Good to know 😊
Btw, `expect.soft` sounds like a better fit for failure analysis here. (I mean in these kind of exitCode + outputs checks)

Comment (sheremet-va) [reply test/browser/specs/runner.test.ts]: That's a good point. We usually keep the error check first instead of the exitCode for that reason

Comment (yjaaidi) [reply test/browser/specs/runner.test.ts]: 👌

**Review by sheremet-va — APPROVED** [review]
