### PR TITLE
fix: manual and redirect mock shouldn't `load` or `transform` original module

### LINKED ISSUE #9622: mocking module with factory function transforms the original module
### Describe the bug

See test case in https://github.com/vitest-dev/vitest/pull/9617 or https://stackblitz.com/edit/vitest-dev-vitest-oqrkbbdz?file=test%2Fsyntax-error.test.js

```js
import * as dep from './syntax-error.js'; // file content is "bad code"

vi.mock('./syntax-error.js', () => {
  return { mocked: 'ok' };
});

test('can mock invalid module', () => {
  expect(dep).toMatchObject({ mocked: 'ok' });
});
```

```sh
❯ vitest

 DEV  v4.1.0-beta.3 /home/projects/vitest-dev-vitest-oqrkbbdz

 ❯ test/syntax-error.test.js (0 test)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/syntax-error.test.js [ test/syntax-error.test.js ]
RollupError: Parse failure: Expected ';', '}' or <eof>
At file: /test/syntax-error.js:1:4
  File: /test/syntax-error.js:1:4
  1  |  bad code
     |      ^
 ❯ getRollupError node_modules/rollup/dist/es/shared/parseAst.js:571:41
 ❯ convertProgram node_modules/rollup/dist/es/shared/parseAst.js:1277:26
 ❯ Module.parseAstAsync node_modules/rollup/dist/es/shared/parseAst.js:2263:106
 ❯ ssrTransformScript node_modules/vite/dist/node/chunks/config.js:15473:9

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯


 Test Files  1 failed (1)
      Tests  no tests
   Start at  13:54:30
   Duration  630ms (transform 25ms, setup 0ms, import 0ms, tests 0ms, environment 0ms)
```

From what I dug so far, I found that this early return for manual mocking isn't happening:

https://github.com/vitest-dev/vitest/blob/c8614f6c60f21c69e92bcbd99c0e64f6e137e755/packages/vitest/src/runtime/moduleRunner/startVitestModuleRunner.ts#L106-L109

because at this point `rawId = /test/syntax-error.js` (url from project root) and `registry.getById` expects absolute path. I changed it here to `registry.get` (which uses `registryByUrl`) and the reproduction is fixed but I found some other test cases got broken (seems like `importOriginal` got broken).

https://github.com/vitest-dev/vitest/blob/c8614f6c60f21c69e92bcbd99c0e64f6e137e755/packages/vitest/src/runtime/moduleRunner/bareModuleMocker.ts#L190-L193

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-oqrkbbdz?file=test%2Fsyntax-error.test.js

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    vitest: beta => 4.1.0-beta.3
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

- Built on https://github.com/vitest-dev/vitest/pull/9772
- Closes https://github.com/vitest-dev/vitest/issues/9622

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [ ] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/vitest/src/runtime/moduleRunner/startVitestModuleRunner.ts [hunk 1]
```diff
@@ -103,15 +111,17 @@ export function startVitestModuleRunner(options: ContextModuleRunnerOptions): Vi
...
-          if (resolvedMock?.type === 'manual' || resolvedMock?.type === 'redirect') {
-            return {
-              code: '',
-              file: null,
-              id: resolvedMock.id,
-              url: resolvedMock.url,
-              invalidate: false,
-              mockedModule: resolvedMock,
+          if (!isImportActual) {
+            const resolvedMock = moduleRunner.mocker.getDependencyMockByUrl(id)
```
Comment (hi-ogawa) [inline packages/vitest/src/runtime/moduleRunner/startVitestModuleRunner.ts:115]: `getDependencyMock(rawId)` doesn't work for actual file since `getDependencyMock` expects full module graph id but `rawid/id` here is a normalized path from project root. Also here `id` over `rawId` is preferred since `id` is an "url" passed to `fetchModule`, e.g.
- `rawId = \0virtual:module` vs `id = /@id/__x00__virtual:module`
- `rawId = /src/foo.js` vs `id = /src/foo.js`

File: packages/vitest/src/runtime/moduleRunner/moduleRunner.ts [hunk 2]
```diff
@@ -165,11 +166,24 @@ export class VitestModuleRunner
...
+      // - mock was removed by doUnmock (stale mockedModule in meta)
+      // - self-import: mock factory/file is importing the module it's mocking
+      const isStale = !this.mocker.getDependencyMock(mod.id)
+      const isSelfImport = callstack.includes(mockId)
+        || callstack.includes(url)
+        || ('redirect' in mockedModule && callstack.includes(mockedModule.redirect))
+      if (isStale || isSelfImport) {
+        const node = await this.fetchModule(injectQuery(url, '_vitest_original'))
+        return this._cachedRequest(node.url, node, callstack, metadata)
+      }
```
Comment (hi-ogawa) [inline packages/vitest/src/runtime/moduleRunner/moduleRunner.ts:181]: This is added to support existing use cases where "import original module" fallback was happening magically. As the previous PR https://github.com/vitest-dev/vitest/pull/9772 consolidated "import original module" to be only possible through `_vitest_original` query, this adjustment became necessary.

**Comment by sheremet-va** [comment]
Conflict!

**Review by sheremet-va — APPROVED** [review]
