### PR TITLE
fix: testFileDir always matches

### LINKED ISSUE #4425: `testFileDir` always matches
### Describe the bug

Given the tree:
```
.
├── tests1
│   └── test.spec.ts
├── tests11
│   └── test.spec.ts
└── tests2
    └── test.spec.ts
```

Vitest will match `tests1` & `tests11` when supplied with filter `tests1/`. 

Whilst i recognise that you can use the `include` option or even specifying direct filenames, that is a very heavyhanded and hardcoded approach which doesn't fit large test repositories (in my case i have 400+ test files in nested directories). 

Instead it would be less-surprising for it to match based on inputs such as `tests1/` to only use that directory. A regex `\b` would also be acceptable. 

### Reproduction

Using this [StackBlitz](https://stackblitz.com/edit/vitest-dev-vitest-grbmeo?file=package.json) you can execute the following scripts that illustrates a plausible scenario:
- `pnpm test:all` : ✅
- `pnpm test:1` : ❌ - Runs tests for both `folder1` and `folder11`
- `pnpm test:2` : ✅
- `pnpm test:11` : ✅

> [!IMPORTANT]  
> In reality, most scenarios wouldn't be matching based on numbers, but i've got into weird scenarios where expressions collide with each other: `test_blocks` and `test_blockscope`

### System Info

```shell
all
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by ibuibu**
### Description
fix #4425 

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [x] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/vitest/src/node/workspace.ts [hunk 1]
```diff
@@ -254,7 +254,8 @@ export class WorkspaceProject {
       return testFiles.filter((t) => {
         const testFile = relative(dir, t)
         return filters.some((f) => {
-          return testFile.includes(f) || testFile.includes(relative(dir, f))
+          const relativePath = f.endsWith('/') ? `${relative(dir, f)}/` : relative(dir, f)
```
Comment (timbrinded) [inline packages/vitest/src/node/workspace.ts:257]: seems safer to use the `node:path` functions then hard coding it like this.

**Review by sheremet-va — APPROVED** [review]
