### PR TITLE
fix(coverage): env-replacer to remove query params from sourcemaps filenames

### LINKED ISSUE #2540: c8 coverage seems broken when using import.meta.env
### Describe the bug

Hi,
I'm using c8 for test coverage in a Vite/Vue project and encountered an issue when using `import.meta.env`.
Vue project is written in OptionAPI, and `.vue` files import `.ts` files.
When using `import.meta.env` in an imported `.ts` file, coverage report indicate only 1 line, and 100% coverage.
Commenting the line causes the coverage report to display correct values.
(Running test with `istanbul` does not raise this issue.)
(Using script in `.vue` as SFC does not raise this issue.)

**Result**:
Statements   : 100% ( 7/7 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 7/7 )

**Expected Result**:
Statements   : 94.73% ( 18/19 )
Branches     : 50% ( 1/2 )
Functions    : 100% ( 1/1 )
Lines        : 94.73% ( 18/19 )

### Reproduction

Here is a repository to reproduce : https://github.com/Polluux/demo-c8-issues
(Note : This repository contains multiple issues for c8)

### System Info

```shell
System: 
  Ubuntu 22.04.1 LTS x86_64 GNU/Linux
Node:
  v16.15.1
Dependencies:
  "vue": "^3.2.45"
  "@vitejs/plugin-vue": "^4.0.0",
  "@vitest/coverage-c8": "^0.26.0",
  "@vue/test-utils": "2.2.6",
  "c8": "^7.12.0",
  "jsdom": "^20.0.3",
  "typescript": "^4.9.4",
  "vite": "^4.0.2",
  "vitest": "^0.26.0",
  "vue-tsc": "^1.0.14"
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by AriPerkkio**
- Fixes bugs where vue components lost coverage when `import.meta.env` is used
- Fixes #2540 

The test case reproduces the issue. The source maps left `sourcesContent` empty/`null` when env-replacer intercepted the transforms. It was adding query parameters to the filenames which we are intentionally dropping in C8 provider. 

**Before** adding `import.meta.env` to the tested vue file the coverage looks OK:
image

**After** adding `import.meta.env` to the test file coverage breaks, on the left side. On the right side it is fixed by this PR:
image

### CODE REVIEW

File: packages/vitest/src/node/plugins/envReplacer.ts [hunk 1]
```diff
@@ -27,7 +27,12 @@ export const EnvReplacerPlugin = (): Plugin => {
       if (s) {
         return {
           code: s.toString(),
-          map: s.generateMap({ hires: true, source: id }),
+          map: s.generateMap({
+            hires: true,
+
+            // Remove possible query parameters, e.g. vue's "?vue&type=script&src=true&lang.ts"
+            source: id.split('?')[0],
```
Comment (sheremet-va) [inline packages/vitest/src/node/plugins/envReplacer.ts:34]: We have `cleanUrl` utility now in `vite-node/utils`

**Review by sheremet-va — CHANGES_REQUESTED** [review]

File: packages/vitest/src/node/plugins/envReplacer.ts (hunk 1 above)
Comment (AriPerkkio) [reply packages/vitest/src/node/plugins/envReplacer.ts]: Now using `cleanUrl`. Maybe the coverage provider packages should be refactored to use it also. As that's out of scope here, I'll leave it to other day.

**Review by sheremet-va — APPROVED** [review]
