### PR TITLE
fix: can mock workspace files

### LINKED ISSUE #578: module mock will not work with yarn workspaces mode
### Describe the bug

My project use yarn workspaces mode. So some node_modules will hoist to the project root node_modules directory.
However, when I use vi.mock to mock a module which hoisted to the root it didnot work as expected.
`// in test.spec.ts`
`vi.mock('some-package');`
`// in index.ts`
`import { someFn } from 'some-package'; // someFn still not mocked`
But when mocking a module not hoisted to the root node_modules it works as expected.

In this case to fix that, I have to use relateive path while mocking such module:
`
vi.mock('../some_path_to_root_dir/node_modules/some-package');
`
Which is pretty tricky. Hope that vi.mock can resolve the correct module path.
Thanks.

### Reproduction

1. Use yarn workspaces mode in package.json:
   `"workspaces": [
    "packages/**"
  ],`
2. create a sub project which path is like: root/packages/app1 and in this dir use yarn to install any package like axios.
3. mock axios in test code like: `vi.mock('axios')` under the dir root/packages/app1;
4. mock will not succeed.

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 319.96 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
Fixes #578

### CODE REVIEW

File: packages/vitest/src/node/mocker.ts [hunk 1]
```diff
@@ -91,7 +91,7 @@ export class VitestMocker {
     const path = await this.options.resolveId(id, importer)
     return {
       path: normalizeId(path?.id || id),
-      external: path?.external ?? path?.id.includes('/node_modules/') ? id : null,
+      external: path?.external || path?.id.includes('/node_modules/') ? id : null,
```
Comment (Demivan) [inline packages/vitest/src/node/mocker.ts:94]: I'm not sure that this is correct. Theoretically `node_modules` file can be marked as not external.

Comment (sheremet-va) [reply packages/vitest/src/node/mocker.ts:94]: This is only for deciding when to store `mocks`. If it's `node_modules`, mocks should be placed in root.

**Review by Demivan — APPROVED** [review]

File: packages/vitest/src/node/mocker.ts (hunk 1 above)
Comment (sheremet-va) [reply packages/vitest/src/node/mocker.ts]: I've removed `path?.external` tho, don't know why I added it in this PR, this place should only check for `node_modules`
