### PR TITLE
fix(browser): stop creating unnecessary directories when taking screenshots

### LINKED ISSUE #8604: `toMatchScreenshot` still creates a folder with the test's filename even when specifing otherwise
### Describe the bug

I have specified in the `vitest.config.ts` a different path for the screenshot directory like so:

```ts
resolveScreenshotPath: ({ root, testFileDirectory, screenshotDirectory, arg, browserName, platform, ext }) => 
    `${root}/${testFileDirectory}/${screenshotDirectory}/${arg}-${browserName}-${platform}${ext}`,

resolveDiffPath: ({ root, testFileDirectory, screenshotDirectory, arg, browserName, platform, ext }) => 
    `${root}/${testFileDirectory}/${screenshotDirectory}/diff/${arg}-${browserName}-${platform}${ext}`,
```

and yet whenever i update my screenshot with the command `pnpm vitest run --update`, it creates the folder with the test file's name (in this screenshot the file name is `button.visual.spec.tsx`)

Image

also important to note that as you can see, it doesnt insert any of the files into it, but simply creates it.

### Reproduction

i feel like the issue is pretty straight forward... if a reproduction is absolutely necessary ill make one.

### System Info

```shell
System:
    OS: macOS 15.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 248.60 MB / 16.00 GB
    Shell: 5.3.3 - /usr/local/bin/bash
  Binaries:
    Node: 22.18.0 - ~/.nvm/versions/node/v22.18.0/bin/node
    npm: 10.9.3 - ~/.nvm/versions/node/v22.18.0/bin/npm
    pnpm: 10.16.1 - ~/.nvm/versions/node/v22.18.0/bin/pnpm
    Watchman: 2025.08.25.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 140.0.7339.133
    Safari: 18.6
  npmPackages:
    @vitejs/plugin-react: catalog: => 5.0.2
    @vitest/browser: ^4.0.0-beta.11 => 4.0.0-beta.11
    @vitest/coverage-v8: ^4.0.0-beta.11 => 4.0.0-beta.11
    @vitest/ui: ^4.0.0-beta.11 => 4.0.0-beta.11
    playwright: ^1.55.0 => 1.55.0
    vite: catalog: => 6.3.6
    vitest: ^4.0.0-beta.11 => 4.0.0-beta.11
    vitest-browser-react: ^2.0.0-beta.3 => 2.0.0-beta.3
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by macarie**
### Description

Fixes #8604 

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [ ] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/browser/src/node/commands/screenshot.ts [hunk 1]
```diff
@@ -84,8 +99,9 @@ export async function takeScreenshot(
     // webdriverio expects the path to contain the extension and only works with PNG files
     const savePathWithExtension = savePath.endsWith('.png') ? savePath : `${savePath}.png`
 
+    // there seems to be a bug in webdriverio, `X:/` gets appended to cwd, so we convert to `X:\`
     const buffer = await element.saveScreenshot(
-      savePathWithExtension,
+      platformNormalize(savePathWithExtension),
```
Comment (macarie) [inline packages/browser/src/node/commands/screenshot.ts:104]: As said in the comment above, we need to change `X:/` to `X:\` when using Windows, so the simplest thing we can do is to use `normalize` from `node:path` and normalize only this path.

**Review by sheremet-va — APPROVED** [review]
