### PR TITLE
fix: fix node crash under Windows (fix #582)

### LINKED ISSUE #582: Crashes under Windows
### Describe the bug

Adding this here so we don't forget to fix it

### Reproduction

https://github.com/vitest-dev/vitest/runs/4868391749?check_suite_focus=true

### System Info

```shell
Windows
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by Demivan**
Fixes #582

### CODE REVIEW

File: packages/vitest/src/node/cli.ts [hunk 1]
```diff
@@ -112,9 +112,6 @@ async function run(cliFilters: string[], options: UserConfig) {
   }
   finally {
     if (!ctx.config.watch)
-      await ctx.close()
+      await ctx.exit()
```
Comment (Demivan) [inline packages/vitest/src/node/cli.ts:115]: Because this was `ctx.close()` all timeout logic was not doing anything anyway :)

File: packages/vitest/src/node/core.ts [hunk 2]
```diff
@@ -351,35 +351,12 @@ export class Vitest {
...
-      },
-      (err) => {
-        cleanup()
-        console.error('error during close', err)
-        process.exit(1)
-      },
-    )
+    setTimeout(() => {
+      console.warn(`close timed out after ${CLOSE_TIMEOUT}ms`)
+      process.exit()
```
Comment (sheremet-va) [inline packages/vitest/src/node/core.ts:356]: shouldn't exitCode be 1?

**Review by sheremet-va — CHANGES_REQUESTED** [review]

File: packages/vitest/src/node/core.ts (hunk 2 above)
Comment (Demivan) [reply packages/vitest/src/node/core.ts:356]: I'm not sure. It does not mean that tests have failed. We weren't returning 1 on timeout before this.

Comment (Demivan) [reply packages/vitest/src/node/core.ts:356]: But it probably does not matter (as this should not happen) and we can have 1 just in case. This way if we have a task that does not finish in time we will get an error and can investigate.

Comment (Demivan) [reply packages/vitest/src/node/core.ts:356]: We actually have some long running stuff and it fails. Need to investigate

**Comment by userquin** [comment]
this changes works
