### PR TITLE
fix(browser): fail playwright timeouts earlier than a test timeout

### LINKED ISSUE #7309: Interacting with `page.getBy*`non-existing element hangs instead of throwing
### Describe the bug

When using `userEvent` + `page.getBy*` and providing a selector that doesn't exist on the page, the test hangs forever instead of throwing "Element by this selector not found".

### Reproduction

Reproduction repository: https://github.com/kettanaito/vitest-locator-issue

## Actual behavior

```
 FAIL   chromium  src/App.test.tsx > fills in the email field
Error: Test timed out in 15000ms.
If this is a long-running test, pass a timeout value as the last argument or configure it globally with "testTimeout".
```

### System Info

```shell
System:
    OS: macOS 15.2
    CPU: (24) arm64 Apple M2 Ultra
    Memory: 90.80 GB / 128.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.13.0 - /usr/local/bin/node
    npm: 10.9.2 - /usr/local/bin/npm
    pnpm: 9.15.3 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 132.0.6834.83
    Safari: 18.2
  npmPackages:
    vitest: ^3.0.2 => 3.0.2
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
### Description

Closes #7309
Related #7559

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/vitest/src/integrations/chai/poll.ts [hunk 1]
```diff
@@ -91,7 +91,7 @@ export function createExpectPoll(expect: ExpectStatic): ExpectStatic['poll'] {
               const rejectWithCause = (cause: any) => {
                 reject(
                   copyStackTrace(
-                    new Error(`Matcher did not succeed in ${timeout}ms`, {
+                    new Error('Matcher did not succeed in time.', {
```
Comment (hi-ogawa) [inline packages/vitest/src/integrations/chai/poll.ts:94]: Is there any reason for removing `${timeout}ms` from the error message?

File: test/browser/test/failing.test.ts [hunk 2]
```diff
@@ -21,6 +21,16 @@ it('several locator methods are not awaited', () => {
   page.getByRole('button').tripleClick()
 })
 
+describe.runIf(server.provider === 'playwright')('timeouts are failing correctly', () => {
+  it('click on non-existing element fails', async () => {
+    await page.getByRole('code').click()
```
Comment (hi-ogawa) [inline test/browser/test/failing.test.ts:26]: To exercise remaining time subtraction logic, can we add a random sleep here?

```suggestion
    await new Promise(r => setTimeout(r, 500))
    await page.getByRole('code').click()
```

**Review by hi-ogawa — COMMENTED** [review]
Looks good! I was worrying about `test.concurrent` breaking `getWorkerState().current` state, but it's probably fine since people wouldn't use concurrent tests with dom interaction/assertions.

File: packages/vitest/src/integrations/chai/poll.ts (hunk 1 above)
Comment (sheremet-va) [reply packages/vitest/src/integrations/chai/poll.ts:94]: mostly because the new timeout value is now irrelevant - it's set by Vitest and equal to basically random numbers (to the user) - like 3542ms, 2323ms. I don't think they are worth printing out

Comment (hi-ogawa) [reply packages/vitest/src/integrations/chai/poll.ts:94]: Ah, I didn't realize `expect.element` is doing `processTimeoutOptions`. It looks good to me :+1: 
If I remember correctly, playwright doesn't change the error message when they patch timeout, so they are lying :smile:

**Review by hi-ogawa — APPROVED** [review]

File: packages/browser/src/client/tester/utils.ts [hunk 3]
```diff
@@ -0,0 +1,180 @@
...
+    || provider !== 'playwright'
+  ) {
+    return options_
+  }
+  // if there is a default action timeout, use it
+  if (getWorkerState().config.browser.providerOptions.actionTimeout != null) {
+    return options_
+  }
+  const currentTest = getWorkerState().current
+  const startTime = currentTest?.result?.startTime
```
Comment (sheremet-va) [inline packages/browser/src/client/tester/utils.ts:148]: This might not be a good idea. The `current` will return the test even if it runs `beforeEach` and `afterEach`, and the timeout there must be different!
