### PR TITLE
fix(vitest): print warnings form Vite plugins

### LINKED ISSUE #6598: Rollup plugin warnings are not shown
### Clear and concise description of the problem

As a developer using Vitest, I would like any Rollup plugins using the [`this.warn` API](https://rollupjs.org/plugin-development/#this-warn) to automatically show the warnings in the console while I am running tests, so that I know there might be issues in the plugin that I should fix.

This actually seems to work out-of-the-box today with Vite ([minimal repro](https://gist.github.com/nolanlawson/a920a2df2ba13ce7f829543e487da170)):

```
[plugin:custom-rollup-plugin] [plugin custom-rollup-plugin] I am warning you!! (x4)
```

However, [a similar repro with  Vitest](https://gist.github.com/nolanlawson/a87ba8df34b0e74c7bdb91b00c4d4d32) does not show any warnings when running `vitest`.

### Suggested solution

By default, I think Rollup warnings should be shown in the console. Perhaps there could also be a way to disable this default behavior, or to handle the warnings in `vitest.config.js`.

### Alternative

I'm not aware of any way to surface Rollup plugin warnings using current Vitest. I apologize if I missed something in the docs!

### Additional context

```
$ node --version
v20.11.0
$ npm --version
10.4.0
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by sheremet-va**
### Description

Fixes #6598

I decided to specify a custom Vite logger by reusing our own. This allows us to reuse the same stdout/stderr. Ideally, Vite should accept the console in the options so we don't need to copy-paste the implementation 😄 

I am keeping `error` in vite-node because it might be a breaking change depending on how it's used

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/vitest/src/node/viteLogger.ts [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+  timeFormatter ??= new Intl.DateTimeFormat(undefined, {
+    hour: 'numeric',
+    minute: 'numeric',
+    second: 'numeric',
+  })
+  return timeFormatter
+}
+
+export function createViteLogger(
+  console: VitestLogger,
```
Comment (hi-ogawa) [inline packages/vitest/src/node/viteLogger.ts:36]: Ah, this is unfortunate, but copying looks fine :+1: 
Probably we should add the comment to the original source somewhere https://github.com/vitejs/vite/blob/main/packages/vite/src/node/logger.ts

**Review by hi-ogawa — COMMENTED** [review]
There are a few more places with `logLevel: 'error'' https://github.com/search?q=repo%3Avitest-dev%2Fvitest+%22logLevel%3A+%27error%27%22&type=code
Perhaps `workspace.ts` one needs update too.
