### PR TITLE
fix(vitest): show correct error when vi.hoisted is used inside vi.mock and the other way around

### LINKED ISSUE #4907: magic-string error
### Describe the bug

Getting the following error after `pnpm exec vitest`

```
Error: Cannot use replaced character 610 as slice start anchor.
 ❯ MagicString.slice node_modules/.pnpm/magic-string@0.30.5/node_modules/magic-string/dist/magic-string.es.mjs:924:10
 ❯ Object.transform node_modules/.pnpm/vite@5.0.11_@types+node@20.10.7/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:64060:62
 ❯ loadAndTransform node_modules/.pnpm/vite@5.0.11_@types+node@20.10.7/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:49741:29
```

### Reproduction

Try using `vi.hoisted` in your code. I am not able to identify how to reproduce exactly because I'm unsure how to debug properly.

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 59.13 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - /opt/homebrew/bin/node
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: 8.14.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Safari: 17.2.1
  npmPackages:
    @vitejs/plugin-react: ^4.2.1 => 4.2.1 
    vitest: ^1.1.3 => 1.1.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
### Description

Closes #4907

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/vitest/src/node/hoistMocks.ts [hunk 1]
```diff
@@ -222,6 +223,57 @@ export function hoistMocks(code: string, id: string, parse: PluginContext['parse
...
+      if (argument.type === 'CallExpression')
+        return getNodeCall(argument as Node)
+    }
+    return node as Positioned<CallExpression>
+  }
+
+  function createError(outsideNode: Node, insideNode: Node) {
+    const outsideCall = getNodeCall(outsideNode)
+    const insideCall = getNodeCall(insideNode)
+    const _error = new SyntaxError(`Cannot call ${getNodeName(insideCall)} inside ${getNodeName(outsideCall)}: both methods are hoisted to the top of the file and not actually called inside each other.`)
```
Comment (ghiscoding) [inline packages/vitest/src/node/hoistMocks.ts:253]: is there a particular reason that you're using `${getNodeName(insideCall)}` instead of both constants `outsideCall` and `insideCall`? It seems redundant

Comment (sheremet-va) [reply packages/vitest/src/node/hoistMocks.ts:253]: insideCall and outsideCall are objects

**Review by dammy001 — APPROVED** [review]
LGTM
