### PR TITLE
fix: inconsistency with globTestFiles and isTargetFile (fix #981, #982)

### LINKED ISSUE #981: file addition is not detected when using relative `include`
### Describe the bug

When a file is added the test reruns on watch mode.
But when `include` is relative like below, the rerun does not happen.
```ts
export default defineConfig({
  test: {
    include: ['test/**.test.ts'],
  },
});
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-b4spnq?file=vite.config.ts

1. Run `npm run test`.
2. Add `foo.test.ts` to `test` directory.
3. test does not rerun.

The rerun happens if you change `include` to `['**/test/**.test.ts']`.

### System Info

```shell
stackblitz

vitest 0.7.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### LINKED ISSUE #982: `dir` option is not respected with file addition detection
### Describe the bug

When there is a config like below, `test/foo.test.ts` will not run. (This is correct.)
But if you add `test/bar.test.ts` after running `vitest`, it gets included.
```ts
export default defineConfig({
  test: {
    dir: 'src',
    include: ['**/*.test.ts'],
  },
});
```

Maybe related to #981.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-xrmrde?file=vite.config.ts&initialPath=__vitest__

1. Run `npm run test`.
2. See `src/bar.test.ts` is included and `test/bar.test.ts` **is not** included.
3. Add `test/foo.test.ts`.
4. Rerun will happen and `test/foo.test.ts` **is** included.

### System Info

```shell
stackblitz

vitest 0.7.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sapphi-red**
This PR fixes inconsistency with `globTestFiles` and `isTargetFile`.

fixes #981
fixes #982 

I actually tested with #981 and #982's reproduction and checked that it works.

### CODE REVIEW

File: packages/vitest/src/node/core.ts [hunk 1]
```diff
@@ -429,12 +429,17 @@ export class Vitest {
     return testFiles
   }
 
+  private isMatchPattern(id: string, pattern: readonly string[]) {
+    const relativeId = relative(this.config.dir || this.config.root, id)
```
Comment (patak-dev) [inline packages/vitest/src/node/core.ts:433]: Is `this.config.dir` needed here? Isn't exclude/include/includeSource relative to the root?

```suggestion
    const relativeId = relative(this.config.root, id)
```

Also, maybe we want to directly make the path `relative` in isTargetFile, or before calling it (we are already calling slash), instead of creating a private function that is potentially called several times (and results in more complexity).

**Review by patak-dev — APPROVED** [review]
