### PR TITLE
fix(browser): remove `crypto.randomUUID` from the client

### LINKED ISSUE #6076: Custom hosts no longer work in Browser mode
### Describe the bug

https://github.com/vitest-dev/vitest/blob/af7fec588d23755899d7ad5dc35d28559dcd0596/packages/browser/src/client/client.ts#L14

This line uses crypto.randomUUID() which is only available in a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts). Localhost is considered secure, but when using a custom domain (we use one that is just an A record with 127.0.0.1) the page isn't secure without setting up SSL certs, so crypto.randomUUID() isn't available

### Reproduction

```ts
      api: {
        host: "aDomainThatPointsToLocalhost.com",
      },
```

then run browser tests as usual, they should fail

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 219.69 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.1.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.6.1 - ~/Library/pnpm/pnpm
    bun: 1.0.26 - ~/.bun/bin/bun
  npmPackages:
    @vitest/browser: ^2.0.1 => 2.0.1 
    @vitest/ui: ^2.0.1 => 2.0.1 
    @vitest/utils: ^2.0.1 => 2.0.1 
    vite: ^5.3.3 => 5.3.3 
    vitest: ^2.0.1 => 2.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by userquin**
### Description

closes #6076

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/browser/src/client/client.ts [hunk 1]
```diff
@@ -11,7 +11,7 @@ export const HOST = [location.hostname, PORT].filter(Boolean).join(':')
 export const SESSION_ID
   = PAGE_TYPE === 'orchestrator'
     ? getBrowserState().contextId
-    : crypto.randomUUID()
+    : getBrowserState().testerContextId
```
Comment (sheremet-va) [inline packages/browser/src/client/client.ts:14]: let's call it `testerId` instead - too much `context` bloat I feel like

Comment (userquin) [reply packages/browser/src/client/client.ts]: done

**Review by sheremet-va — APPROVED** [review]
