### PR TITLE
fix(vite-node): normalize drive letter to keep the same reference to a module

### LINKED ISSUE #3776: Vitest with environment JSDOM not working on windows with lower-case drive letter
### Describe the bug

Vitest does not seem to work with a lower-case drive letter on windows when using `testEnvironment: "jsdom"`

```
c:\Users\nicoj\github\vitest-drive-letter>npx vitest --run

 RUN  v0.33.0 c:/Users/nicoj/github/vitest-drive-letter

 ❯ src/math.spec.js (0)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/math.spec.js [ src/math.spec.js ]
Error: No test suite found in file c:/Users/nicoj/github/vitest-drive-letter/src/math.spec.js
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  no tests
   Start at  15:53:08
   Duration  1.17s (transform 36ms, setup 0ms, collect 118ms, tests 0ms, environment 613ms, prepare 153ms)


c:\Users\nicoj\github\vitest-drive-letter>cd ..

c:\Users\nicoj\github>cd "C:\Users\nicoj\github\vitest-drive-letter"

C:\Users\nicoj\github\vitest-drive-letter>npx vitest --run

 RUN  v0.33.0 C:/Users/nicoj/github/vitest-drive-letter

 ✓ src/math.spec.js (1)
   ✓ add (1)
     ✓ should result in 42 for 40 and 2

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  15:53:38
   Duration  1.09s (transform 37ms, setup 0ms, collect 25ms, tests 3ms, environment 608ms, prepare 152ms)

```

### Reproduction

[lower-case-letter.zip](https://github.com/vitest-dev/vitest/files/12061538/lower-case-letter.zip)

Using windows:

1. Unzip and cd into it
2. `npm i`
3. `vitest --run` -- this should work
4. cd up 1 dir
5. cd into the child dir using the full path, but with _lower case drive letter_: `cd "c:\Users\nicoj\github\vitest-drive-letter"`
6. `vitest --run` -- see that it doesn't work.

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 4.48 GB / 31.73 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.82)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
Fixes #3776

### CODE REVIEW

File: packages/vite-node/src/utils.ts [hunk 1]
```diff
@@ -6,6 +6,15 @@ import type { Arrayable, Nullable } from './types'
...
 export const isWindows = process.platform === 'win32'
 
+const drive = isWindows ? process.cwd()[0] : null
+const driveOpposite = drive
+  ? (drive === drive.toUpperCase()
+      ? drive.toLowerCase()
+      : drive.toUpperCase())
+  : null
+const driveRegexp = drive ? new RegExp(`${drive}(\:[\\/])`) : null
+const driveOppositeRegext = driveOpposite ? new RegExp(`${driveOpposite}(\:[\\/])`) : null
```
Comment (sheremet-va) [inline packages/vite-node/src/utils.ts:16]: This regexp will also work for `D:/path/named:/`, so should be rewritten
