### PR TITLE
fix: re-apply default conditions if using vite 6 or later

### LINKED ISSUE #7070: Vite 6 compatibility issue `resolve.conditions`
### Describe the bug

When using a browser-based evironment (happy-dom, jsdom, ~browser~), vitest still passes `conditions: ['node']` in the resolve config.

When using Vite 5, this doesn't really matter because it would infer that we were targetting a web environment and it would resolve in that context anyway. I'm not 100% sure on how this worked before, but `tryNodeResolve` was being passed a `targetWeb` boolean and the returned ID will match the browser / default import conditions instead of the node condition.

With Vite 6 a lot of this default environment magic was stripped out as part of the Environments api refactor, and now it's just using the resolve.conditions from the corresponding client/ssr configs. This results in a change in behavior where Vitest now uses the node condition for browser environments when using Vite 6.

Using the node condition instead of browser can result in test failures due to differences in behavior between browser and node implementations of a library, but I've also run into issues where esbuild as part of deps optimization generates invalid code where the module itself is "babel compatible" but tries to deconstruct the named exports from `import_mod1.default` instead of `import_mod1`.

These issues reproduce in the latest Vitest `2.1.8` using a resolution for Vite `6.0.3`, as well as Vitest `3.0.0-beta.2`.

### Reproduction

I'm still working on creating a reproducer that I can share and should be able to do so by the end of the day. 

In terms of the actual code changes, I think these two locations can be changed to use:
```ts
conditions: [testConfig.environment === 'node' ? 'node' : 'browser']
```

https://github.com/vitest-dev/vitest/blob/4e60333dc7235704f96314c34ca510e3901fe61f/packages/vitest/src/node/plugins/index.ts#L88-L94

https://github.com/vitest-dev/vitest/blob/4e60333dc7235704f96314c34ca510e3901fe61f/packages/vitest/src/node/plugins/workspace.ts#L67-L73

But it's also a little unclear to me if we should be clearing out the `mainFields: [],` for the browser-based environments also.

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Memory: 11.40 GB / 31.64 GB
  Binaries:
    Node: 20.18.0 - ~\AppData\Local\fnm_multishells\18680_1733347780000\node.EXE
    Yarn: 4.5.3 - ~\AppData\Local\fnm_multishells\18680_1733347780000\yarn.CMD
    npm: 10.9.1 - D:\source\delete-me\test-vite6\node_modules\.bin\npm.CMD
    bun: 1.1.29 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    vite: ^6.0.0 => 6.0.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by thebanjomatic**
Fixes #7070

### Description

Vite 6 no longer applies default conditions when you override resolve.conditions. This PR adds them back conditionally based on the vite version.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [X] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [X] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/vitest/src/node/plugins/conditions.ts [hunk 1]
```diff
@@ -0,0 +1,32 @@
+function normalizeConditions(conditions?: string[]) {
+  if (!conditions) {
+    return []
+  }
+
+  // We remove browser and node conditions from the default list because
+  // we add back "node" explicitly in both client and server conditions.
+  // this ensures that the conditions we pass on to vite doesn't include
+  // both browser and node at the same time, or node twice in the server case.
+  return conditions.filter(c => c !== 'browser' && c !== 'node')
```
Comment (thebanjomatic) [inline packages/vitest/src/node/plugins/conditions.ts:10]: I don't love that the vite migration docs say:
> For example, if you previously specified ['custom'] for resolve.conditions, you need to specify ['custom', ...defaultClientConditions] instead.

which implies that we should just be doing:
```ts
clientConditions: ['node', ...defaultClientConditions],
```
but there is some subtlety in that in vite 5, 'node' and 'browser' weren't actually part of the default conditions, but instead it passed:
```ts
browser: targetWeb && !additionalConditions.has('node')
```

So in the case of vitest passing node as an additional condition it would disable the browser resolve, but if node wasn't passed in, it would infer 'browser'.

If you want the same behavior as before, we need to remove "browser" from vite's default conditions, and add the node condition instead.

**Comment by thebanjomatic** [comment]
@sheremet-va assuming this change looks good for the vitest 3.x release, is there any chance of back-patching it to 2.1.9 while waiting for the official 3.x release?

**Comment by sheremet-va** [comment]
Vitest 2 doesn’t support Vite 6

**Comment by thebanjomatic** [comment]
The 2.1.7 [release notes](https://github.com/vitest-dev/vitest/releases/tag/v2.1.7) implied a soft support:

> We will enable support for it later. In the meantime, you can still use pnpm.overrides or yarn resolutions to override the vite version in the vitest package - the APIs are compatible.

But that was under the assumption the api's were compatible which doesn't appear to be the case. I'm ok waiting, but thought I'd ask.

**Comment by sheremet-va** [comment]
The API is compatible, only default config values have breaking changes

**Comment by thebanjomatic** [comment]
@sheremet-va would it be possible to get this looked at again for a future vitest 3 alpha release?

File: packages/vitest/src/node/plugins/conditions.ts (hunk 1 above)
Comment (hi-ogawa) [reply packages/vitest/src/node/plugins/conditions.ts:10]: > If you want the same behavior as before, we need to remove "browser" from vite's default conditions, and add the node condition instead.

I think we need to go with this. Running `browser` exports on jsdom/happy-dom will likely break a lot, for example https://github.com/vitest-dev/vitest/issues/7215.

To keep the intention of Vitest's `conditions: ["node"]` on Vite 5, I think what we need is essentially setting `defaultServerConditions` all the time, namely something like:

```js
const { defaultServerConditions } = await import("vite");
{
  resolve: {
    conditions: defaultServerConditions
  },
  ssr: {
    resolve: {
      conditions: defaultServerConditions
    }
  }
}
```

**Comment by hi-ogawa** [comment]
Can you also test CI with Vite 6? You can temporarily bump this version and commit.
https://github.com/vitest-dev/vitest/blob/e2e065853052c26b3121ea413a9db7145be3512d/package.json#L65

File: packages/vitest/src/node/plugins/conditions.ts [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+}
+
+async function getDefaultConditions() {
+  type Vite6Options = typeof import('vite') & Partial<{
+    defaultClientConditions?: string[]
+    defaultServerConditions?: string[]
+  }>
+  const vite: Vite6Options = await import('vite')
```
Comment (sheremet-va) [inline packages/vitest/src/node/plugins/conditions.ts:18]: why do we need to import this dynamically?

**Review by sheremet-va — CHANGES_REQUESTED** [review]

**Comment by thebanjomatic** [comment]
@hi-ogawa / @sheremet-va Thanks for your help with the revisions.

I was able to add a test case for this which fails in vite 6 without this change, but succeeds with the change. I was trying to reuse the existing fixture for the "conditions-cli" test case, but I couldn't find a way to add a check for the "module" condition without breaking the other tests. The simplest idea of just wrapping the existing conditions in a "module" condition, unfortunately doesn't work in Vite 5 but does in Vite 6, so I fell back on adding a simpler reproducer test more in line with what was suggested.

Vite 5 test run: https://github.com/vitest-dev/vitest/actions/runs/12796508495?pr=7071
Vite 6 test run: https://github.com/vitest-dev/vitest/actions/runs/12796723653?pr=7071

There were failures in the Vite 6 test run, but I don't think they are related, and some of them happened before and some after the new tests that were added. There seemed to be 3 types of failures:

```
  FAIL  test/browser-multiple.test.ts > automatically assigns the port
  AssertionError: expected [ 'http://localhost:63315/', 'http://localhost:63317/' ] to include 'http://localhost:63316/'
```

```
  FAIL   threads  test/imports.test.ts > importing special files from node_modules > importing wasm with ?raw query
  AssertionError: expected '' to be '(module)' // Object.is equality
```
  
```
  FAIL   v8  test/vue.test.ts > coverage results matches snapshot
  Error: Snapshot `coverage results matches snapshot 1` mismatched
  - Expected
  + Received
  @@ -1,11 +1,11 @@
    {
      "branches": {
  -     "covered": 5,
  +     "covered": 7,
  -     "pct": 83.33,
  +     "pct": 87.5,
        "skipped": 0,
  -     "total": 6,
  +     "total": 8,
      }, 
``` 

I have reverted the temporary vite 6 upgrade commit.

**Review by hi-ogawa — DISMISSED** [review]
Thanks, looks good to me! I pushed some cleanup for tests.

Btw, I'm guessing your original repro was hit by `tslib`'s `module` and `node` condition https://publint.dev/tslib@2.8.1. Can you verify your repro is fixed using https://github.com/vitest-dev/vitest/pull/7071#issuecomment-2594233434?

> There were failures in the Vite 6 test run, but I don't think they are related, and some of them happened before and some after the new tests that were added. There seemed to be 3 types of failures:

Ah, I should've given you a heads up. There are some tests failing due to other things. It should be fine to not worry about them for now.

**Review by sheremet-va — APPROVED** [review]

**Comment by kolorfilm** [comment]
With 6.0 my tests are successful. With this change my tests are failing. It doesn't find many properties, for instance:

`Cannot read properties of undefined (reading '100')`

I do not unterstand why this change was made (reverted).
