### PR TITLE
fix: incorrect error message for non-awaited `expect.element()`

### LINKED ISSUE #8953: Incorrect error message in non-awaited `expect.element()` calls
### Describe the bug

When not awaiting an `expect.element()` call, there seem to be an issue with the error text. it shows the error for `expect.poll`:

(image taken from https://github.com/vitest-dev/eslint-plugin-vitest/issues/683)

### Reproduction

```TS
test("renders name", async () => {
  const element = page.getByText("Hello Vitest!");

  expect.element(element).toBeInTheDocument();
});

```

### System Info

```shell
Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.21.1 - /Users/**/.local/state/fnm_multishells/15956_1762412239648/bin/node
    Yarn: 1.22.22 - /Users/**/.local/state/fnm_multishells/15956_1762412239648/bin/yarn
    npm: 10.9.4 - /Users/**/.local/state/fnm_multishells/15956_1762412239648/bin/npm
    pnpm: 10.20.0 - /Users/**/.local/state/fnm_multishells/15956_1762412239648/bin/pnpm
  Browsers:
    Chrome: 142.0.7444.60
    Firefox Developer Edition: 144.0
    Safari: 18.5
  npmPackages:
    @vitest/browser-playwright: ^4.0.7 => 4.0.7 
    vitest: ^4.0.7 => 4.0.7
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by StyleShit**
### Description

Resolves #8953

Flagging the callback happened [inside the callback itself](https://github.com/vitest-dev/vitest/blob/97aed7454f09d352a9e71b3cd67c3584238cf455/packages/browser/src/client/tester/expect-element.ts#L19), which runs after [the check](https://github.com/vitest-dev/vitest/blob/97aed7454f09d352a9e71b3cd67c3584238cf455/packages/vitest/src/integrations/chai/poll.ts#L113) whether it's `poll` or `element`, so I flagged it outside the callback

I want to add some tests. Saw that there are tests for [`poll-no-awaited`](https://github.com/vitest-dev/vitest/blob/97aed7454f09d352a9e71b3cd67c3584238cf455/test/cli/fixtures/fails/poll-no-awaited.test.ts), but I'm assuming that `expect.element` tests shouldn't be there and I wasn't sure how to test it. Would be glad to get some help here

### CODE REVIEW

**Comment by sheremet-va** [comment]
The error is correct, just the message is wrong.

**Comment by sheremet-va** [comment]
I don't see how this fixes the message. Please, add a test somewhere in `test/browser`, probably

**Comment by StyleShit** [comment]
> I don't see how this fixes the message

Determining the error message is based on a flag that's attached to the expect function reference (either `expect.poll()` or `expect.element()`).

What happened is that the flagging of `expect.element()` happens inside the function itself
(basically `function expectElement() { addFlag(this, 'expect.element', true) }`),
but the check against this flag runs _before_ this function even runs, so it's not flagged yet.

> add a test

Added. Took me some time to figure it out...

File: packages/browser/src/client/tester/expect-element.ts [hunk 1]
```diff
@@ -47,6 +46,10 @@ function element<T extends HTMLElement | SVGElement | null | Locator>(elementOrL
 
     return result
   }, processTimeoutOptions(options))
+
+  chai.util.flag(expectElement, '_poll.element', true)
```
Comment (Omerisra6) [inline packages/browser/src/client/tester/expect-element.ts:50]: Hi, new here :) 
How does this ensures the right message?

**Comment by sheremet-va** [comment]
> but the check against this flag runs _before_ this function even runs, so it's not flagged yet.

I see, the `poll` is not called at all if the function is not awaited, so the flag is never set
