### PR TITLE
fix(pool): prevent writing to closed worker

### LINKED ISSUE #9014: Error: write EPIPE
### Describe the bug

Vitest is failing randomly with the error `Error: write EPIPE`. Sometimes (mostly the first runs) are succeed and at some point, when the notebook is under more pressure, it starts failing. Also tested this setup with our runners, 2-3 are failing out of 5 with the same error in different areas.

I saw also that if it fails multiple times, that there node processes running in the background which will not be cleared.

```
node:events:486
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at ChildProcess.target._send (node:internal/child_process:877:20)
    at ChildProcess.target.send (node:internal/child_process:751:19)
    at ForksPoolWorker.send (file:///Users/michaelholst/Documents/projects/k3k-web-frontend/node_modules/vitest/dist/chunks/cli-api.BQ-bjcRi.js:6839:13)
    at PoolRunner.postMessage (file:///Users/michaelholst/Documents/projects/k3k-web-frontend/node_modules/vitest/dist/chunks/cli-api.BQ-bjcRi.js:6677:63)
    at post (file:///Users/michaelholst/Documents/projects/k3k-web-frontend/node_modules/vitest/dist/chunks/cli-api.BQ-bjcRi.js:6668:28)
    at EventEmitter.onMessage (file:///Users/michaelholst/Documents/projects/k3k-web-frontend/node_modules/vitest/dist/chunks/index.DAL392Ss.js:152:19)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
Emitted 'error' event at:
    at ChildProcess.emitWorkerError (file:///Users/michaelholst/Documents/projects/k3k-web-frontend/node_modules/vitest/dist/chunks/cli-api.BQ-bjcRi.js:6769:22)
    at ChildProcess.emit (node:events:508:28)
    at node:internal/child_process:881:39
    at processTicksAndRejections (node:internal/process/task_queues:85:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

```

### Reproduction

1. fork https://gitlab.opencode.de/opentalk/web-frontend/-/tree/main
2. download patch [0001-chore-deps-update-node.js-to-v24.patch](https://github.com/user-attachments/files/23494924/0001-chore-deps-update-node.js-to-v24.patch)
3. `git apply --verbose 0001-chore-deps-update-node.js-to-v24.patch`
4. `pnpm install`
5. `pnpm test:unit:ci`

Last step is running in the pipeline, you can find other scripts in the package.json in the root directory of the monorepo.

### System Info

```shell
System:
    OS: macOS 15.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 5.69 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.11.0 - /Users/michaelholst/.nvm/versions/node/v24.11.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 11.6.1 - /Users/michaelholst/.nvm/versions/node/v24.11.0/bin/npm
    pnpm: 10.21.0 - /usr/local/bin/pnpm
    Deno: 1.23.1 - /usr/local/bin/deno
    Watchman: 2025.04.14.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 141.1.83.118
    Chrome: 142.0.7444.135
    Firefox Developer Edition: 145.0
    Safari: 18.6
  npmPackages:
    @vitest/coverage-v8: 4.0.8 => 4.0.8 
    @vitest/eslint-plugin: ^1.4.1 => 1.4.1 
    vitest: 4.0.8 => 4.0.8
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by AriPerkkio**
### Description

Resolves #9014

When user's test case doesn't do proper clean up, it can trigger rpc calls after test finished. In the reproduction there's `rpc.fetch()` that resolves on main thread after worker has stopped. This leads to `EPIPE` as IPC is closed already.

This is reproducible by having Vite plugin that takes long time on specific file transform, and that file is imported without awaiting it in test case.

Minimal repro for `test/core` - this will raise `Error: [vitest-worker]: Closing rpc while "fetch" was pending` errors on worker side so not adding the test case for now:

```ts
import { defineConfig } from 'vitest/config'

export default defineConfig({
  plugins: [
    {
      name: 'slow-down-transform',
      enforce: 'pre',
      async resolveId(id) {
        if (id.includes('vitest-test:slow-transform')) {
          return '\0vitest-test-slow-transform'
        }
      },
      async load(id) {
        if (id.includes('vitest-test-slow-transform')) {
          await new Promise(res => setTimeout(res, 1000))
          return `export default "Hello world"`
        }
      },
    },
  ],
});
```

```ts
import { test } from 'vitest'

test('should not cause EPIPE when imports resolve after test finishes', async () => {
  for (const _ of Array.from({ length: 50 }).fill(0)) {
    const cache = Math.round(Math.random() * 1000)

    setTimeout(
      () =>
        import(`vitest-test:slow-transform` + `?cache=${cache}`),
      2,
    ).unref()
  }
})
```

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [x] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/vitest/src/node/pools/poolRunner.ts
Comment (AriPerkkio) [inline packages/vitest/src/node/pools/poolRunner.ts:85]: Another option is to prevent writing to `STOPPING` workers. I think before `RunnerState` refactoring this used to do it.

We've seen with previous Vitest majors that it tried to write to closed workers:
- https://github.com/tinylibs/tinypool/issues/84


```suggestion
  postMessage(message: WorkerRequest): void {
    // Only send messages when runner is active (not fully stopped)
    // Allow sending during STOPPING state for the 'stop' message itself
    if (this._state !== RunnerState.STOPPED && this._state !== RunnerState.STOPPING) {
      return this.worker.send(message)
    }

    if (this._state === RunnerState.STOPPING && message.__vitest_worker_respose__ && message.type === 'stop') {
      return this.worker.send(message)
    }
  }
```

Comment (axel7083) [reply packages/vitest/src/node/pools/poolRunner.ts:85]: Hey! Tried this suggested you provided (I created a patch https://github.com/axel7083/podman-desktop/pull/5/commits/9fb93e14d47b1bdb7d76dc67ce23cbd320a3ab7e), this seems to lead to _a lot or weird behavior_ our all logs are filled  with

```
[vitest-pool]: Timeout terminating forks worker for test files 
[vitest-pool]: Failed to terminate forks worker for test files
[vitest-pool-runner]: Timeout waiting for worker to respond
    at Timeout.<anonymous> (file:///home/runner/work/podman-desktop/podman-desktop/node_modules/vitest/dist/chunks/cli-api.D48wY175.js:6803:58)
    at listOnTimeout (node:internal/timers:588:17)
    at processTimers (node:internal/timers:523:7)
```

and at the end it just got cancelled by GitHub runner on Linux ([unit tests / ubuntu-24.04#job](https://github.com/axel7083/podman-desktop/actions/runs/19370618013/job/55425346113))

Lead to  process out of memory on Windows ([unit tests / windows-2025#job](https://github.com/axel7083/podman-desktop/actions/runs/19370618013/job/55425346028))

File: packages/vitest/src/node/pools/poolRunner.ts [hunk 1]
```diff
@@ -155,6 +155,8 @@ export class PoolRunner {
     try {
       this._state = RunnerState.STOPPING
 
+      this._rpc.$close(new Error('[vitest-pool-runner]: Pending methods while closing rpc'))
```
Comment (axel7083) [inline packages/vitest/src/node/pools/poolRunner.ts]: Hey! I tired this solution (I created a patch https://github.com/axel7083/podman-desktop/commit/3c56d405e50009664e23a104b29891e40b9c23bc), and tired on our migration from vitest 3 to vitest 4 

This does not seems to have address the problem reported in https://github.com/vitest-dev/vitest/issues/9014

**Review by axel7083 — COMMENTED** [review]
Hey! So glad to see you working on this issue, we are in the middle of our migration to vitest 4. We have an almost 100% reproducer on GitHub, (not reproducing locally however) if you need to experiment let me know I could try to help

--- 

I also tried to downgrade to 4.0.4 but the problem still persist [unit tests / ubuntu-24.04#job](https://github.com/axel7083/podman-desktop/actions/runs/19371375986/job/55428334008?pr=5)

File: packages/vitest/src/node/pools/poolRunner.ts
Comment (AriPerkkio) [reply packages/vitest/src/node/pools/poolRunner.ts:85]: @axel7083 thanks for testing out. 

Could you try this one?

`npm i https://pkg.pr.new/vitest@617260f`

```json
"devDependencies": {
  "vitest": "https://pkg.pr.new/vitest@617260f"
}
```

- https://github.com/vitest-dev/vitest/pull/9023#issuecomment-3525790784

E: Fix confirmed here: https://github.com/vitest-dev/vitest/issues/9014#issuecomment-3539326544

File: packages/vitest/src/node/pools/pool.ts [hunk 2]
```diff
@@ -76,8 +76,9 @@ export class Pool {
       const activeTask = { task, resolver, method, cancelTask }
       this.activeTasks.push(activeTask)
 
+      // active tasks receive cancel signal and shut down gracefully
       async function cancelTask() {
-        await runner.stop()
+        await runner.waitForTerminated
```
Comment (sheremet-va) [inline packages/vitest/src/node/pools/pool.ts]:
```suggestion
        await runner.waitForTerminated()
```

File: packages/vitest/src/node/pools/poolRunner.ts [hunk 3]
```diff
@@ -44,6 +45,10 @@ export class PoolRunner {
     return this._state === RunnerState.STOPPED
   }
 
+  public get waitForTerminated(): Promise<void> {
```
Comment (sheremet-va) [inline packages/vitest/src/node/pools/poolRunner.ts]:
```suggestion
  public waitForTerminated(): Promise<void> {
```

**Review by sheremet-va — DISMISSED** [review]

**Review by sheremet-va — APPROVED** [review]
