### PR TITLE
fix(vite-node): provide import.meta.filename and dirname

### LINKED ISSUE #5010: `import.meta.filename` and `import.meta.dirname` is `undefined` on Node.js Latest LTS `v20.11.0`
### Describe the bug

Node.js implemented API that `import.meta.filename` and `import.meta.dirname` on `v21.2.0`,
and it backported into latest LTS `v20.11.0`.

- https://github.com/nodejs/node/pull/48740

- https://nodejs.org/en/blog/release/v21.2.0
- https://nodejs.org/en/blog/release/v20.11.0

### Reproduction

vitest: `v1.2.1`

Repo: https://github.com/d-hajime-san/reference-vitest-import-meta-object

Result

```bash
% pnpm test

> reference-vitest-import-meta-object@ test /Users/hostname/repository/reference-vitest-import-meta-object
> vitest run


 RUN  v1.2.1 /Users/hostname/repository/reference-vitest-import-meta-object

 ❯ src/module.test.ts (2)
   ❯ testing import.meta (2)
     × filename
     × dirname

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 2 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/module.test.ts > testing import.meta > filename
AssertionError: expected undefined to be '/Users/hostname/repository/ref…' // Object.is equality

- Expected: 
"/Users/hostname/repository/reference-vitest-import-meta-object/src/module.test.ts"

+ Received: 
undefined

 ❯ src/module.test.ts:10:34
      8| describe("testing import.meta", () => {
      9|   it("filename", () => {
     10|     expect(import.meta.filename).toBe(__filename);
       |                                  ^
     11|   });
     12|   it("dirname", () => {

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/2]⎯

 FAIL  src/module.test.ts > testing import.meta > dirname
AssertionError: expected undefined to be '/Users/hostname/repository/ref…' // Object.is equality

- Expected: 
"/Users/hostname/repository/reference-vitest-import-meta-object/src"

+ Received: 
undefined

 ❯ src/module.test.ts:13:33
     11|   });
     12|   it("dirname", () => {
     13|     expect(import.meta.dirname).toBe(__dirname);
       |                                 ^
     14|   });
     15| });

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[2/2]⎯

 Test Files  1 failed (1)
      Tests  2 failed (2)
   Start at  17:09:53
   Duration  247ms (transform 49ms, setup 0ms, collect 39ms, tests 5ms, environment 0ms, prepare 85ms)

 ELIFECYCLE  Test failed. See above for more details
```

### System Info

```shell
System:
  OS: macOS 13.5.1
  CPU: (8) arm64 Apple M1
  Memory: 588.38 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.11.0 - ~/.volta/tools/image/node/20.11.0/bin/node
  npm: 10.2.4 - ~/.volta/tools/image/node/20.11.0/bin/npm
  pnpm: 8.14.0 - ~/.volta/bin/pnpm
Browsers:
  Chrome: 120.0.6099.234
  Chrome Canary: 122.0.6256.6
  Edge: 120.0.2210.144
  Safari: 16.6
  Safari Technology Preview: 17.0
npmPackages:
  vitest: 1.2.1 => 1.2.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
### Description

Fixes #5010

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/vitest/src/runtime/external-executor.ts [hunk 1]
```diff
@@ -71,11 +71,11 @@ export class ExternalModulesExecutor {
   }
 
   public resolveModule = async (specifier: string, referencer: string) => {
-    const identifier = await this.resolve(specifier, referencer)
+    const identifier = this.resolve(specifier, referencer)
     return await this.createModule(identifier)
   }
 
-  public async resolve(specifier: string, parent: string) {
+  public resolve(specifier: string, parent: string) {
```
Comment (AriPerkkio) [inline packages/vitest/src/runtime/external-executor.ts:78]: What's behind this change? I'm now running into error where `resolveModule` is passing `Promise` to `createModule`. Then this part:

https://github.com/vitest-dev/vitest/blob/cfd06118730098b9a15540d609d2fa2b598c866e/packages/vitest/src/runtime/external-executor.ts#L153

... crashes with error 

```
TypeError: identifier.startsWith is not a function
 ❯ ExternalModulesExecutor.getModuleInformation ../../packages/vitest/dist/vendor/vm.UXtVveu9.js:575:20
 ❯ ExternalModulesExecutor.createModule ../../packages/vitest/dist/vendor/vm.UXtVveu9.js:597:38
 ❯ ExternalModulesExecutor.resolveModule ../../packages/vitest/dist/vendor/vm.UXtVveu9.js:505:23
 ❯ ../../packages/vitest/dist/vendor/vm.UXtVveu9.js:258:58
 ❯ ModuleWrap.<anonymous> node:internal/vm/module:306:30
 ❯ SourceTextModule.<computed> node:internal/vm/module:305:36
 ❯ SourceTextModule.link node:internal/vm/module:199:22
 ❯ EsmExecutor.evaluateModule ../../packages/vitest/dist/vendor/vm.UXtVveu9.js:258:11
 ❯ ExternalModulesExecutor.import ../../packages/vitest/dist/vendor/vm.UXtVveu9.js:621:20
 ❯ VitestExecutor.interopedImport ../../packages/vite-node/dist/client.mjs:383:28
```

And by debugging the `identifier` there, it's `Promise` and not `string`.

This can be reproduced with `test/run` tests. The `exec-argv` one is crashing with `vmThreads`.

Comment (AriPerkkio) [reply packages/vitest/src/runtime/external-executor.ts:78]: `import.meta.resolve` is `async`. This is on Node `v18.17.1`:

```js
> console.log(nativeResolve.toString())

async function resolve(specifier, parentUrl = defaultParentUrl) {
    return PromisePrototypeThen(
      asyncESM.esmLoader.resolve(specifier, parentUrl),
      ({ url }) => url,
      (error) => (
        error.code === 'ERR_UNSUPPORTED_DIR_IMPORT' ?
          error.url : PromiseReject(error)),
    );
  }
```

Thought it's not in sources: https://github.com/nodejs/node/blob/6ae20aa63de78294b18d5015481485b7cd8fbb60/lib/internal/modules/esm/initialize_import_meta.js#L22
