### PR TITLE
feat(ui): fix file error + add colored support

### LINKED ISSUE #494: --ui does not capture errors / stacks for investigation
### Describe the bug

I would like to be able to debug why vitest isn't working, but without dropping into `--inspect-brk` it seems there isn't a way to do that.

image

In this picture, there is a failed test, the UI says all tests passed in this file, yet, but they didn't run, and in the terminal, I see this:
```
Error: Package subpath 'undefined' is not defined by "exports" in <repo>/node_modules/ember-template-lint/package.json.
 ❯ resolveDeepImport node_modules/vite/dist/node/chunks/dep-76613303.js:30664:19
 ❯ tryNodeResolve node_modules/vite/dist/node/chunks/dep-76613303.js:30440:20
 ❯ Context.resolveId node_modules/vite/dist/node/chunks/dep-76613303.js:30257:28
 ❯ Object.resolveId node_modules/vite/dist/node/chunks/dep-76613303.js:36922:55
 ❯ async TransformContext.resolve node_modules/vite/dist/node/chunks/dep-76613303.js:36721:23
 ❯ async normalizeUrl node_modules/vite/dist/node/chunks/dep-76613303.js:73684:34
 ❯ async TransformContext.transform node_modules/vite/dist/node/chunks/dep-76613303.js:73826:57
 ❯ async Object.transform node_modules/vite/dist/node/chunks/dep-76613303.js:36985:30
 ❯ async doTransform node_modules/vite/dist/node/chunks/dep-76613303.js:52049:29}
```
^ this particular issue looks similar to https://github.com/vitejs/vite/issues/3250, so I'll investigate in that direction (but this is orthogonal to empowering investigation, and I asked for followup here: [in discord](https://discord.com/channels/917386801235247114/918057998914568213/929748817765629974))

### Reproduction

run with --ui, have a module loading error.

My specific situation:
- `git clone git@gitlab.com:NullVoxPopuli/ember-template-lint-plugin-tailwindcss.git`
- `git checkout vitest`
- `yarn`
- `yarn start`

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 597.79 MB / 16.19 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.1 - ~/.volta/tools/image/node/16.13.1/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.1.2 - ~/.volta/tools/image/node/16.13.1/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 95.0.1
  npmPackages:
    vite: ^2.7.10 => 2.7.10 
    vitest: ^0.0.139 => 0.0.139 

```
```


### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### LINKED ISSUE #857: Console UI support ANSI color
### Clear and concise description of the problem

console can't support ANSI color now.

### Suggested solution

maybe we can add [ansi-to-html](https://github.com/rburns/ansi-to-html) dependencies. or I can fork this and deletion some features.

```typescript
import Filter from 'ansi-to-html'

function formatConsoleLog(log: string) {
  const filter = new Filter()
  return filter.toHtml(log)
}
```
```html
<pre v-html="formatConsoleLog(log.content)" />
```

### Alternative

_No response_

### Additional context

before: 
image

after:
image

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### LINKED ISSUE #973: False positive test result
### Describe the bug

image

### Reproduction

1. Create a Quasar project
2. Install jest unit test app extension
3. Configure Vite/Vitest to run the test

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 3.27 GB / 15.93 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.0 - ~\AppData\Roaming\npm\npm.CMD
    Watchman: 20210110.135312.0 - D:\Chocolatey\bin\watchman.EXE
  Browsers:
    Chrome: 99.0.4844.51
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.39)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitest: ^0.7.0 => 0.7.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by userquin**
This PR fixes the problem on file test compilation error and adds `ansi-to-html` support on report and console tabs.

closes #494 
closes #857 
closes #973

### CODE REVIEW

**Comment by userquin** [comment]
To test both tabs:
- base cases: `cd packages/core && pnpm run dev:ui` then from root folder `pnpm run test`: open the page and uncomment the `console` entries from the ui on `basic.test.ts` (search basic on left panel):
```ts
  // eslint-disable-next-line no-console
  // console.log(`\x1B[33m${new Date().toISOString()}\x1B[0m`)
  // eslint-disable-next-line no-console
  // console.log(`\x1B[31m${new Error('I\'m a red fg error').stack}\x1B[0m`)
  // eslint-disable-next-line no-console
  // console.log(`\x1B[37m\x1B[41m${new Error('I\'m a red bg error').stack}\x1B[0m`)
  // console.error('console error 1', new Error('hey there 2'))
```
- `@testing-library/xxx`: from root folder `pnpm run ui:build` then `cd examples\react-testing-lib && pnpm run test:ui`: change for example on `examples/react-testing-lib/src/components/input.test.tsx`  line 19 with `name: /email address/g` (change the `i` with `g`)

File: packages/vitest/src/types/tasks.ts [hunk 1]
```diff
@@ -21,6 +21,8 @@ export interface TaskResult {
   startTime?: number
   error?: ErrorWithDiff
   hooks?: Partial<Record<keyof SuiteHooks, TaskState>>
+  // only for ui: handling internal colored stack traces on report tab
+  uiHtmlError?: string
```
Comment (edimitchel) [inline packages/vitest/src/types/tasks.ts:25]: What about:
```suggestion
  error?: ErrorWithDiff
  htmlError?: string
  hooks?: Partial<Record<keyof SuiteHooks, TaskState>>
```
`error` is already using something the UI could use, so why not just named it `htmlError`?

File: test/core/test/basic.test.ts [hunk 2]
```diff
@@ -3,6 +3,13 @@ import { two } from '../src/submodule'
 import { timeout } from '../src/timeout'
 
 test('Math.sqrt()', async() => {
+  // eslint-disable-next-line no-console
+  // console.log(`\x1B[33m${new Date().toISOString()}\x1B[0m`)
+  // eslint-disable-next-line no-console
+  // console.log(`\x1B[31m${new Error('I\'m a red fg error').stack}\x1B[0m`)
+  // eslint-disable-next-line no-console
+  // console.log(`\x1B[37m\x1B[41m${new Error('I\'m a red bg error').stack}\x1B[0m`)
+  // console.error('console error 1', new Error('hey there 2'))
```
Comment (edimitchel) [inline test/core/test/basic.test.ts:12]: As UI testing with Cypress is enable on Vitest, it could be great to cover your work with it :)

**Review by edimitchel — CHANGES_REQUESTED** [review]

File: test/core/test/basic.test.ts (hunk 2 above)
Comment (userquin) [reply test/core/test/basic.test.ts:12]: I need to refactor the console view component a few to remove the client (birpc) entry (add a new component and use it on the component) and so we can only check the component, later I'll try to add a few cypress tests on ui package

Comment (edimitchel) [reply test/core/test/basic.test.ts:12]: Let me ask help or @JessicaSachs who will for sure be happy to help you!

Comment (userquin) [reply test/core/test/basic.test.ts:12]: @edimitchel check the console cy test : https://imgur.com/Tq4zB9g

Comment (userquin) [reply test/core/test/basic.test.ts]: working on report tab tests

**Review by edimitchel — APPROVED** [review]
Very nice @userquin, you rock!
That's ok for me, @antfu your turn :)

**Comment by userquin** [comment]
> Very nice @userquin, you rock!
> That's ok for me, @antfu your turn :)

@edimitchel

I need to include the cypress tests for the report tab as well, just wait I'm working on it, I'm going to eat in 1 hour or so I'll be back and finish it.

File: test/core/test/basic.test.ts (hunk 2 above)
Comment (userquin) [reply test/core/test/basic.test.ts]: @edimitchel check the report cy test: https://imgur.com/gcPyYmH

**Comment by userquin** [comment]
@edimitchel now it is ready to review

**Review by edimitchel — APPROVED** [review]

File: packages/ui/client/components/views/ViewConsoleOutputEntry.cy.tsx [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+        time={Date.now()}
+        html={false}
+        content={content}
+      />,
+    ).get(textSelector)
+    container.should('exist')
+    container.invoke('text').then((t) => {
+      expect(t, 'the message has the correct message').equals(content)
+    })
+  })
```
Comment (JessicaSachs) [inline packages/ui/client/components/views/ViewConsoleOutputEntry.cy.tsx:23]: The goal this test is to make sure that there is text that has the `content` you pass in when HTML is false. You also want to make sure that the `type`, `task-name`, and `time` are visible. Here's the shortest way to write that test:

```suggestion
  it('test plain entry', () => {
    const content = faker.hacker.phrase()
    const time = Date.now()
    const localeTime = time.toLocaleString()
    const type = 'stderr'
    const taskName = 'test/text'
    cy.mount(
      <ViewConsoleOutputEntry
        task-name={taskName}
        type={type}
        time={time}
        html={false}
        content={content}
      />,
    )

    // always either check for visible or exists
    // visibility checks prevent CSS bugs relating to overflow, height, width, or opacity
    cy.contains(content).should('be.visible')
    cy.contains(taskName).should('be.visible')
    cy.contains(localeTime).should('be.visible')
    cy.contains(type).should('be.visible')
  })
  
```

File: packages/ui/client/components/views/ViewConsoleOutputEntry.cy.tsx [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+  it('test html entry', () => {
+    const now = new Date().toISOString()
+    const content = new Filter().toHtml(`\x1B[33m${now}\x1B[0m`)
+    const container = cy.mount(
```
Comment (JessicaSachs) [inline packages/ui/client/components/views/ViewConsoleOutputEntry.cy.tsx:27]: Don't use the return value of `container` unless you want the Vue Test Utils `wrapper` result.

File: packages/ui/client/components/views/ViewConsoleOutputEntry.cy.tsx [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+      <ViewConsoleOutputEntry
+        task-name="test/html"
+        type="stderr"
+        time={Date.now()}
+        html={true}
+        content={content}
+      />,
+    ).get(htmlSelector)
+    container.should('exist')
+    container.children('span').then((c) => {
```
Comment (JessicaSachs) [inline packages/ui/client/components/views/ViewConsoleOutputEntry.cy.tsx:37]: Instead of using DOM tags like `span` and hierarchy like `children`, just as the test for what you want -- you want to find the element with the text `now`.

This can be done via

```js
cy.contains(now)
```

and you can delete all references to span, etc.

the `contains` check **implicitly checks that `now` exists in the DOM** so you ca delete `container.should('exist')`.

`cy.contains` is very similar to Testing Library's `findByText` and I may suggest installing `@testing-library/cypress` to have similar bindings throughout the codebase.

File: packages/ui/client/components/views/ViewReport.cy.tsx [hunk 6]
```diff
@@ -0,0 +1,120 @@
...
+        state: 'fail',
+        error: {
+          name: 'Do some test',
+          stacks: [{ line: 10, column: 20, file: 'test/plain-stack-trace.ts', method: 'dummy test' }],
+          message: 'Error: Transform failed with 1 error:',
+        },
+      },
+      tasks: [],
+    }
+    const container = cy.mount(<ViewReport file={file} />)
```
Comment (antfu) [inline packages/ui/client/components/views/ViewReport.cy.tsx:24]: Do we need TSX here? Possible to simply use `h`?

Comment (userquin) [reply packages/ui/client/components/views/ViewReport.cy.tsx:24]: it is the cypress test, I just "clone" the existing one

Comment (userquin) [reply packages/ui/client/components/views/ViewReport.cy.tsx:24]: you have it on dashboard folder (the original from Jess)

File: packages/ui/client/components/views/ViewConsoleOutputEntry.cy.tsx [hunk 7]
```diff
@@ -0,0 +1,42 @@
...
+      expect(c, 'the message has the correct message').to.have.text(now)
+      expect(c, 'the message has the correct text color').to.have.attr('style', 'color:#A50')
+    })
+  })
```
Comment (JessicaSachs) [inline packages/ui/client/components/views/ViewConsoleOutputEntry.cy.tsx:41]: This test is brittle because it depends on the specific CSS output of UnoCSS on styles 😮. 

Try to avoid these kinds of tests.

```suggestion
      <ViewConsoleOutputEntry
        task-name="test/html"
        type="stderr"
        time={Date.now()}
        html={true}
        content={content}
      />,
    )
    cy.get(htmlSelector)
      .should('have.class', 'text-red-600')
      .and('be.visible')
      .and('contain.text', now)
  })
```

File: packages/ui/client/components/views/ViewReport.cy.tsx (hunk 6 above)
Comment (userquin) [reply packages/ui/client/components/views/ViewReport.cy.tsx:24]: @antfu I can change cy tests to render the component and passing the props instead using tsx

Comment (userquin) [reply packages/ui/client/components/views/ViewReport.cy.tsx:24]:
```ts
const container = cy.mount(ViewReport, { 
  propsData: { file } 
})
```

**Comment by JessicaSachs** [comment]
Oof. I was in the middle of adding PR feedback.

**Comment by JessicaSachs** [comment]
Like a lot of it 😓

**Comment by antfu** [comment]
Oh haha, I guess you can still do and we could improve it with another PR. Thanks!

**Review by JessicaSachs — COMMENTED** [review]
The **`ViewReport.cy.tsx`** needs more help, but I added some feedback to the other spec.

File: packages/ui/client/components/views/ViewReport.cy.tsx (hunk 6 above)
Comment (JessicaSachs) [reply packages/ui/client/components/views/ViewReport.cy.tsx:24]: > Do we need TSX here? Possible to simply use `h`?

The reason we use TSX in such a simple example is for consistency. I prefer native `h`, but I think TSX is the most elegant answer right now to:
1. passing in spies for emitted events
2. making components under test reactive/into playgrounds
3. styling wrapper or related content

The other pattern we explored at Cy was using SFCs.

### Passing Spies

```tsx
const onMyEventSpy = cy.spy().as('myEventSpy')
mount(() => <MyComponent onMyEvent={onMyEventSpy}>)

cy.get('button').click().get('@myEventSpy').should('have.been.called.with', 'some arguments')
```

### Interactive Tests

TSX becomes really helpful for modals when you not only want to **spy** on the event emitted (somewhat identical to `wrapper.emitted()`, but also when you want to make the component into more of a playground and **do** something. e.g.

```tsx
const visible = ref(true)
mount(() => (
  <button onClick={visible.value = !visible.value}>Toggle</button>
  <MyModal visible={visible}/>
))
```

### Styling Wrapper DOM

Lastly, when you want to control parent/container styles in order to see your component behave differently in different UIs. This works especially well with UnoCSS

```tsx
mount(() => (
  <div min-w-200px resize overflow-auto>
    <MyTextComponent>Content inside here!</MyTextComponent>
  </div>
))
```

File: packages/ui/client/components/views/ViewConsoleOutputEntry.cy.tsx (hunk 7 above)
Comment (userquin) [reply packages/ui/client/components/views/ViewConsoleOutputEntry.cy.tsx:41]: @JessicaSachs 

The resulting html is this:
```html
<pre data-type="html"><span style="color:#A50">2022-04-07T19:10:53.637Z</span></pre>
```
using your suggestion, the messages aren't totally accurate (the `pre` doesn't have that style, it's the inner `span` that does):

imagen
