### PR TITLE
fix(browser-webdriverio): fall back to WebDriver Classic #9244

### LINKED ISSUE #9244: BUG: @vitest/browser-webdriverio fails with Safari when BiDi commands are used despite enforcing WebDriver Classic
### Describe the bug

Original Report: https://github.com/webdriverio/webdriverio/issues/14927
Reproduction Repo: https://github.com/chrisguttandin/vitest-webdriverio

Root Cause
The @vitest/browser-webdriverio package's setViewport method unconditionally uses a WebDriver BiDi command without checking if BiDi is actually available:

Why This Fails
Safari on GitHub Actions may not support WebDriver BiDi yet OR the BiDi session wasn't established
User sets 'wdio:enforceWebDriverClassic': true to explicitly disable BiDi
WebdriverIO respects this and doesn't create a BiDi session (no webSocketUrl in capabilities)
Vitest's provider ignores this and tries to use BiDi commands anyway
Result: Command fails because no BiDi session exists

we need to check BiDi availability before using BiDi commands, and fall back to WebDriver Classic commands when BiDi isn't available.

### Reproduction

Original Report: https://github.com/webdriverio/webdriverio/issues/14927
Reproduction Repo: https://github.com/chrisguttandin/vitest-webdriverio

### System Info

```shell
Original Report: https://github.com/webdriverio/webdriverio/issues/14927
Reproduction Repo: https://github.com/chrisguttandin/vitest-webdriverio
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by JustasMonkev**
### Description

  Check `browser.isBidi` before using BiDi commands in `setViewport`. When BiDi is unavailable (e.g., Safari or when `wdio:enforceWebDriverClassic` is set), fall back to `setWindowSize` instead of failing.

Resolves #9244

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [x] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [x] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/browser-webdriverio/src/webdriverio.ts [hunk 1]
```diff
@@ -117,14 +117,19 @@ export class WebdriverBrowserProvider implements BrowserProvider {
...
+        method: 'browsingContext.setViewport',
+        params: {
+          context: this.topLevelContext,
+          devicePixelRatio: 1,
+          viewport: options,
+        },
+      })
+    }
+    else {
+      await this.browser.setWindowSize(options.width, options.height)
```
Comment (sheremet-va) [inline packages/browser-webdriverio/src/webdriverio.ts:131]: Why not `browser.setViewport`?

Comment (JustasMonkev) [reply packages/browser-webdriverio/src/webdriverio.ts:131]: `browser.setViewport()` in `WebDriverIO` uses `browsingContextSetViewport()` under the hood, which is a BiDi-only command.

  `setWindowSize` is the WebDriver Classic equivalent for controlling browser dimensions. While not a perfect 1:1 match (it sets window size including browser chrome, not just viewport). 
  
  https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/browser/setViewport.ts#L61
  
  https://github.com/webdriverio/webdriverio/blob/5b35e4e2b94e3ac5247ec2bf27f2f5e41ef00372/packages/webdriverio/src/commands/browser/setWindowSize.ts#L26
