### PR TITLE
fix(reporter): `dot` reporter leaves pending tests

### LINKED ISSUE #9681: Dot reporter minor visual bug in Vitest 4
### Describe the bug

When all tests pass, instead of displaying all green dots in the end, some (at least one) dots remain yellow, as if pending. It's only a visual bug, all the tests have actually ran. It's a regression from Vitest 3

Image

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-b6ubd6qx?file=vite.config.ts&initialPath=__vitest__/

### System Info

```shell
System:
    OS: macOS 26.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 22.67 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.13.1 - /Users/Jaroslav/.nvm/versions/node/v24.13.1/bin/node
    npm: 11.8.0 - /Users/Jaroslav/.nvm/versions/node/v24.13.1/bin/npm
    bun: 1.3.1 - /Users/Jaroslav/.bun/bin/bun
  Browsers:
    Chrome: 144.0.7559.133
    Firefox: 147.0.3
    Safari: 26.3
  npmPackages:
    @vitejs/plugin-react: ^5.1.4 => 5.1.4 
    @vitest/coverage-v8: ^4.0.18 => 4.0.18 
    vite: ^7.3.1 => 7.3.1 
    vitest: ^4.0.18 => 4.0.18
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by AriPerkkio**
### Description

Resolves https://github.com/vitest-dev/vitest/issues/9681

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [x] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Review by AriPerkkio — COMMENTED** [review]
If testing with `test/core`, I noticed that this test is incorrectly reported as `pending` when test run finishes. It's unrelated bug to `dot` reporter 👀 

https://github.com/vitest-dev/vitest/blob/bb20389f4b1a74e8357ae1229896d0c8817088c1/test/core/test/retry.test.ts#L73-L78

File: packages/vitest/src/node/reporters/dot.ts [hunk 1]
```diff
@@ -36,6 +36,10 @@ export class DotReporter extends BaseReporter {
   // Ignore default logging of base reporter
   printTestModule(): void {}
 
+  onTestRunStart(): void {
+    this.renderer?.start()
+  }
```
Comment (hi-ogawa) [inline packages/vitest/src/node/reporters/dot.ts]: The `BaseReporter` has some state reset. Shouldn't this call super too?

https://github.com/vitest-dev/vitest/blob/5b336b29b4cc70d99dbc269dc1ff022a3dae2aa1/packages/vitest/src/node/reporters/base.ts#L78-L81

Comment (AriPerkkio) [reply packages/vitest/src/node/reporters/dot.ts]: Good catch! I thought I checked this yesterday and got type errors about `super.onTestRunStart` not existing 🤔

**Review by hi-ogawa — APPROVED** [review]
