### PR TITLE
fix(vitest): test deep dependencies change detection

### LINKED ISSUE #4933: `--changed` not picking up deep imports
### Describe the bug

`--changed` does not pick up deep changes.

In the attached reproduction run `yarn vitest --run --changed=HEAD`

- No changes made will detect no specs to run. This is expected 👍 
- Changing `add` will detect no specs to run. This is not expected 👎  
- Changing `add-twice.ts` will detect no specs to run. This is expected 👍 

This is problematic for monorepo like setups (or any setup IMO). I expect the `--changed` flag to deeply look at dependencies to detect possible spec files to run. At moment this is shallow and only direct imports will cause files to change. 

It looks to me that the logic in `getTestDependecies` is trying to do this, as it recursively calls `addImports`, however the guard clause for checking if the dep is already added is preventing the deep lookup of depenendencies.

[getTestDependencies ](https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/node/core.ts#L401-L403)

- `LN: 401` adds the dep to the collected set
- `LN: 403` invokes looking up further dependencies of that dependency
- `LN: 390` checks if that dependency is already added and bails out

As line 401 adds the collected dependency the further lookups of nested dependencies is not running. This causes the changed file dependencies to be shallow which does not accurately trigger related specs when a nested dependency is changed.

In order to correct the `changed` logic the logic needs to shift a little. Line 403 and 401 can't simply be shifted as otherwise it will cause any cyclic dependencies to cause a stack overflow. Aware that cyclic dependencies shouldn't exist in user code but having a cyclic dependency shouldn't cause vitest to crash. 

### Reproduction

github.com/blake-newman/vitest-dev-vitest-kx8wc3

(I couldn't reproduce in stackblitz but checking out locally shows issue)

### System Info

```shell
Not applicable
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by blake-newman**
`--changed` flag is not correctly looking up deep dependencies, as such the changed flag does not trigger specs if a sub dependency is changed.

Alters the logic to add the collected dependency after recursive `addImports` is called, otherwise the logic returns early because that dependency has already been added to the collected deps set. So it will not look deeply.

Resolves #4933 
(Also Resolves https://github.com/vitest-dev/vitest/issues/5009)

### CODE REVIEW

File: packages/vitest/src/node/core.ts [hunk 1]
```diff
@@ -386,9 +386,13 @@ export class Vitest {
   }
 
   private async getTestDependencies(filepath: WorkspaceSpec, deps = new Set<string>()) {
+    const [, workspaceFilepath] = filepath
     const addImports = async ([project, filepath]: WorkspaceSpec) => {
       if (deps.has(filepath))
         return
+      if (workspaceFilepath !== filepath)
+        deps.add(filepath)
```
Comment (hi-ogawa) [inline packages/vitest/src/node/core.ts:394]: nit: this is probably just a minor thing, but I think we could just accumulating everything but filter `workspaceFilepath` later? something like:

```tsx
  const addImports = async (...) => {
      if (deps.has(filepath))
        return
      deps.add(filepath)
      ...
  } 

  await addImports(filepath)
  deps.delete(filepath[1])
```

**Review by hi-ogawa — COMMENTED** [review]
Thanks for the PR! (also reproduction and your analysis are awesome!)

This looks like a bug to me since the same logic is also used for `vitest related` https://vitest.dev/guide/cli.html#vitest-related and it also misses deep dependency. I checked it based on your repro https://stackblitz.com/edit/github-ndav2w?file=package.json

For the sake of verifying this PR, I don't think setting up new tests for `--changed` is necessary (actually there seems none currently probably because it's tedious to setup git), but It would be great if you can expand existing tests in `test/changed/fixtures/related` to show that deep dependencies is covered.

**Review by sheremet-va — CHANGES_REQUESTED** [review]
Let's add a test case for this change. The tests for this feature are located in `test/changed`

**Comment by blake-newman** [comment]
@sheremet-va @hi-ogawa i've added the relevant tests (including imports / re-export syntax). 

I also tested locally to ensure that the specs fail if the changes are not applied.

**Review by sheremet-va — APPROVED** [review]

**Review by hi-ogawa — APPROVED** [review]
Looks good!
