### PR TITLE
fix: hooks should respect `maxConcurrency`

### LINKED ISSUE #8367: `maxConcurrency` is not respected in `beforeAll`/`afterAll` hooks
### Describe the bug

More than `maxConcurrency` number of hooks can run in parallel. 

### Reproduction

package.json
```json title="package.json"
{
  "name": "vitest",
  "version": "1.0.0",
  "description": "",
  "license": "ISC",
  "author": "",
  "type": "commonjs",
  "devDependencies": {
    "vitest": "^3.2.4"
  }
}
```

a.test.js
```js
import { beforeAll, describe, it } from 'vitest';

async function sleep(ms=1000) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

describe.concurrent('Test Suite', () => {
    describe.for(["a", "b"])('$0', (name) => {
        beforeAll(async () => {
            console.log(`Running beforeAll for ${name}`);
            await sleep();
        });

        it(`test ${name} 1`, async () => {
        });
    });
});
```

```console
$ npm exec -- vitest run --max-concurrency=1 a.test.js

 RUN  v3.2.4 <snip>

stdout | a.test.js > Test Suite > 'b'
Running beforeAll for a
Running beforeAll for b

 ✓ a.test.js (2 tests) 1008ms
   ✓ Test Suite > 'a' > test a 1 2ms
   ✓ Test Suite > 'b' > test b 1 0ms

 Test Files  1 passed (1)
      Tests  2 passed (2)
   Start at  09:50:21
   Duration  1.26s (transform 17ms, setup 0ms, collect 12ms, tests 1.01s, environment 0ms, prepare 59ms)
```

I would expect the test to run for at least 2 seconds, because the calls to sleep should not be run in parallel with `--max-concurrency=1`.

### System Info

```shell
Not relevant
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

- Closes https://github.com/vitest-dev/vitest/issues/8367

(This includes the same change from https://github.com/vitest-dev/vitest/pull/9673 for `aroundEach/All` error aggregation behavior.)

#### Problems 

Currently we apply promise limit only at `runTest` level, which executes `beforeEach -> test fn -> afterEach > onTestFinished/onTestFailed` routine for single test case. This doesn't limit other parallelism we have, which are:
- suite hooks (`beforeAll`, `afterAll`) between `describe.concurrent` neighbors
- running hooks (`beforeAll`, `afterAll`, `beforeEach`, `afterEach`) within a single group via `sequence.hooks: "parallel"`

#### Solution

This PR moves promise limit from `runTest` level to each "leaf level" function calls, which are user functions registered via `test/beforeEach/afterEach/beforeAll/afterAll/onTestFinished/onTestFailed`. This ensures any user code managed by test runner is bounded by single `maxConcurrency` limit. Since we apply this only at "leaf level", it's free from dead locking itself by nested promise limit.

~I'm not sure how `aroundEach/aroundAll` can work with this model, so they aren't currently bounded by `maxConcurrency`. (AI might figure out somehow making this work but I haven't tried yet).~ (EDIT: apparently it's possible)

TODO
- [x] summary
- [x] docs
- [x] test

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [ ] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/runner/src/utils/limit-concurrency.ts
Comment (hi-ogawa) [inline packages/runner/src/utils/limit-concurrency.ts:1]: As I've put a lot more `limitConcurrency` in runner, I optimized this to reduce microtask as much as possible. This should cost only one microtask in the happy path (i.e. when not reaching limit) and two when limited. The previous implementation always paid three microtasks.

File: test/test-utils/index.ts [hunk 1]
```diff
@@ -423,7 +424,7 @@ export default config
   return `export default ${JSON.stringify(content)}`
 }
 
-export function useFS<T extends TestFsStructure>(root: string, structure: T, ensureConfig = true) {
+export function useFS<T extends TestFsStructure>(root: string, structure: T, ensureConfig = true, context?: TestContext) {
```
Comment (sheremet-va) [inline test/test-utils/index.ts]: Maybe it's better to pass `task`? It has `task.context` that you can use and it still allows destructuring

**Review by sheremet-va — CHANGES_REQUESTED** [review]

File: test/test-utils/index.ts [hunk 2]
```diff
@@ -554,16 +556,33 @@ export class StableTestFileOrderSorter {
...
+        return result.errors.map(e => e.message)
+      }
+      return result.state
+    },
+    (testSuite, suiteChildren) => {
+      const errors = testSuite.errors().map(error => error.message)
+      if (errors.length > 0) {
+        return {
+          ...suiteChildren,
+          __suite_errors__: errors,
```
Comment (hi-ogawa) [inline test/test-utils/index.ts:573]: Tweaked test util so that `errorTree` includes suite errors.

File: test/cli/test/expect-task.test.ts
Comment (hi-ogawa) [inline test/cli/test/expect-task.test.ts:1]: The concurrent tests was broken since it's using global `onTaskFinished`. I adjusted `runInlineTests` helper so it can use `context.onTaskFinished`.

File: test/cli/fixtures/fails/concurrent-suite-deadlock.test.ts
Comment (hi-ogawa) [inline test/cli/fixtures/fails/concurrent-suite-deadlock.test.ts:1]: I moved these "fails" tests to more through integration test in `concurrent.test.ts`

**Review by sheremet-va — APPROVED** [review]
