### PR TITLE
fix: cleanup before exiting process

### LINKED ISSUE #582: Crashes under Windows
### Describe the bug

Adding this here so we don't forget to fix it

### Reproduction

https://github.com/vitest-dev/vitest/runs/4868391749?check_suite_focus=true

### System Info

```shell
Windows
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
Fixes #582

### CODE REVIEW

File: packages/vitest/src/node/core.ts [hunk 1]
```diff
@@ -351,18 +351,31 @@ export class Vitest {
...
   async exit() {
-    const closePromise = this.close()
     let timeout: NodeJS.Timeout
+    let resolveClose: () => void
+    let resolveTimeout: () => void
+    const closePromise = new Promise((resolve, reject) => {
+      resolveClose = () => resolve(true)
+      this.close().then(resolve, reject)
+    })
+    // make sure all premises are resolved before exiting process
```
Comment (Demivan) [inline packages/vitest/src/node/core.ts:361]:
```suggestion
    // make sure all promises are resolved before exiting process
```

**Review by Demivan — APPROVED** [review]

File: packages/vitest/src/node/core.ts [hunk 2]
```diff
@@ -351,18 +351,31 @@ export class Vitest {
...
+    })
+    // make sure all promises are resolved before exiting process
+    // https://github.com/nodejs/node/blob/master/src/node_file-inl.h#L160
+    const cleanup = () => {
+      clearTimeout(timeout)
+      resolveTimeout?.()
+      resolveClose?.()
+    }
     const timeoutPromise = new Promise((resolve, reject) => {
+      resolveTimeout = () => resolve(true)
```
Comment (patak-dev) [inline packages/vitest/src/node/core.ts:369]: This could directly be the resolve function, no?
```suggestion
      resolveTimeout = resolve
```

Comment (sheremet-va) [reply packages/vitest/src/node/core.ts:369]: It can be, but it's type requires to pass something, so I just did it before 👀
