### PR TITLE
fix(happy-dom): support fetch globals

### LINKED ISSUE #8777: vitest@4 problem with MSW + Axios
### Describe the bug

Hi,

I'm trying to upgrade to vitest@4 and I'm facing an issue. You can reproduce it here: https://github.com/ddolcimascolo/vitest-4-msw-issue. The reproduction is a very trimmed-down version of my monorepo. Basically there's seomething weird with request headers not received by MSW.

Feel free to ask anything else to debug the issue.

Regards,
David

### Reproduction

https://github.com/ddolcimascolo/vitest-4-msw-issue

### System Info

```shell
System:
    OS: Linux 6.8 Linux Mint 22.2 (Zara)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 4.22 GB / 15.35 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 22.11.0 - /home/david/.nvm/versions/node/v22.11.0/bin/node
    Yarn: 1.22.22 - /home/david/.nvm/versions/node/v22.11.0/bin/yarn
    npm: 10.9.0 - /home/david/.nvm/versions/node/v22.11.0/bin/npm
    pnpm: 10.13.1 - /home/david/.nvm/versions/node/v22.11.0/bin/pnpm
  Browsers:
    Chrome: 141.0.7390.122
    Firefox: 144.0
    Firefox Developer Edition: 144.0
  npmPackages:
    vite: 6.4.1 => 6.4.1 
    vitest: 4.0.1 => 4.0.1
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### LINKED ISSUE #8788: v4 regression: something is wrong with happy-doms Blob
### Describe the bug

This code works with v3.2.4, but throws an error with 4.0.2:

```
import { test } from 'vitest';

test('Blob', () => {
  const file = new window.File([window.Buffer.from('<foo />')], 'a.xml');
  window.URL.createObjectURL(file);
});
```

May be related to
- https://github.com/capricorn86/happy-dom/issues/471
- https://github.com/capricorn86/happy-dom/issues/847

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-nsv5fpsa?file=package.json

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: 4.0.2 => 4.0.2 
    vite: 7.1.11 => 7.1.11 
    vitest: 4.0.2 => 4.0.2
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
### Description

Fixes #8777
Fixes #8788

We removed fetch related globals from the KEYS to support jsdom, but happy-dom does define them properly, so they need to stay in the happy-dom environment.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [ ] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/vitest/src/integrations/env/happy-dom.ts [hunk 1]
```diff
@@ -63,8 +63,18 @@ export default <Environment>{
...
+      // jsdom doesn't support fetch API, but happy-dom does
+      additionalKeys: [
+        'Request',
+        'Response',
+        'MessagePort',
+        'fetch',
+        'Headers',
+        'AbortController',
+        'AbortSignal',
+        'URL',
```
Comment (EvHaus) [inline packages/vitest/src/integrations/env/happy-dom.ts:75]: @sheremet-va After upgrading to vitest 4.0.3 my `happy-dom`-based tests are now failing with:

```
ReferenceError: URL is not defined
 ❯ new Location ../../node_modules/.pnpm/happy-dom@20.0.10/node_modules/happy-dom/lib/location/Location.js:26:25
 ❯ new BrowserWindow ../../node_modules/.pnpm/happy-dom@20.0.10/node_modules/happy-dom/lib/window/BrowserWindow.js:708:41
 ❯ new Window ../../node_modules/.pnpm/happy-dom@20.0.10/node_modules/happy-dom/lib/window/Window.js:39:9
 ❯ new GlobalWindow ../../node_modules/.pnpm/happy-dom@20.0.10/node_modules/happy-dom/lib/window/GlobalWindow.js:10:16
 ❯ Object.setup ../../node_modules/.pnpm/vitest@4.0.5_@types+node@24.9.1_happy-dom@20.0.10_jiti@2.6.1_yaml@2.8.1/node_modules/vitest/dist/chunks/index.DON9WL-E.js:338:69
 ❯ processTicksAndRejections node:internal/process/task_queues:105:5
 ❯ withEnv ../../node_modules/.pnpm/vitest@4.0.5_@types+node@24.9.1_happy-dom@20.0.10_jiti@2.6.1_yaml@2.8.1/node_modules/vitest/dist/chunks/base.RFExFinv.js:55:14
 ❯ run ../../node_modules/.pnpm/vitest@4.0.5_@types+node@24.9.1_happy-dom@20.0.10_jiti@2.6.1_yaml@2.8.1/node_modules/vitest/dist/chunks/base.RFExFinv.js:72:144
 ❯ runBaseTests ../../node_modules/.pnpm/vitest@4.0.5_@types+node@24.9.1_happy-dom@20.0.10_jiti@2.6.1_yaml@2.8.1/node_modules/vitest/dist/chunks/base.RFExFinv.js:122:2
 ❯ executeTests ../../node_modules/.pnpm/vitest@4.0.5_@types+node@24.9.1_happy-dom@20.0.10_jiti@2.6.1_yaml@2.8.1/node_modules/vitest/dist/chunks/init-forks.WSf5dRNP.js:24:4
```

Could it be related to this change? Downgrading to vitest 4.0.2 makes the issue go away.

Comment (andrewbrennanfr) [reply packages/vitest/src/integrations/env/happy-dom.ts:75]: Same failure for me ☝️

Comment (sheremet-va) [reply packages/vitest/src/integrations/env/happy-dom.ts:75]: Please, create an issue with a reproduction. A quick run of our happy-dom tests didn't show an error

Comment (andrewbrennanfr) [reply packages/vitest/src/integrations/env/happy-dom.ts:75]: Ok done here https://github.com/vitest-dev/vitest/issues/8882 👍
