### PR TITLE
fix: correctly remove import query from url

### LINKED ISSUE #836: Unit test be failed with component contain svg
### Describe the bug

The files structure of pro
```bash
./
├── README.md
├── index.html
├── package.json
├── pnpm-lock.yaml
├── public
│   └── favicon.ico
├── src
│   ├── App.vue
│   ├── assets
│   │   └── logo.png
│   ├── components
│   │   ├── HelloWorld.vue
│   │   └── foo.svg
│   └── main.js
├── test
│   └── HelloWorld.test.js
└── vite.config.js
```

The HelloWorld.vue
```vue
<script setup>
import { ref } from 'vue'
import IconLink from './foo.svg?raw';
</script>

<template>
  {{ IconLink }}
</template>
```
The Test File
```js
import { expect, test } from 'vitest';
import { mount } from '@vue/test-utils'
import Hello from '../src/components/HelloWorld.vue'

test('', async() => {
  const wrapper = mount(Hello)

  expect(wrapper).toBeTruthy()
})
```
The package.json
```json
{
  "name": "vite-project",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "test": "vitest",
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.2.25"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^2.2.0",
    "@vue/test-utils": "^2.0.0-rc.17",
    "happy-dom": "^2.39.1",
    "vite": "^2.8.0",
    "vitest": "^0.5.1"
  }
}
```

The vite.config.js

```js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [vue()],
  test: {
    watch: false,
    environment: 'happy-dom',
  }
})
```
execute `pnpm run test`, and failed:

```bash
> vite-project@0.0.0 test /Users/apple/Playground/vite-project
> vitest


 RUN  /Users/apple/Playground/vite-project

 ↓ test/HelloWorld.test.js (0) [skipped]

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/HelloWorld.test.js [ test/HelloWorld.test.js ]
Error: ENOENT: no such file or directory, open '/src/components/foo.svg&raw'
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

Test Files  1 failed | 1 skipped (1)
     Tests  no tests
      Time  1.76s (in thread 0ms, Infinity%)

 ELIFECYCLE  Test failed. See above for more details.

```

### Reproduction

**Please see the Describe the bug，there have all details & reproduction steps。**

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 4.50 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.0 - ~/Library/Caches/fnm_multishells/48818_1645428770973/bin/node
    Yarn: 1.22.17 - ~/Library/Caches/fnm_multishells/48818_1645428770973/bin/yarn
    npm: 8.5.1 - ~/Library/Caches/fnm_multishells/48818_1645428770973/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Safari: 15.3
  npmPackages:
    @vitejs/plugin-vue: ^2.2.0 => 2.2.2
    vite: ^2.8.0 => 2.8.4
    vitest: ^0.5.1 => 0.5.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
Fixes #836

### CODE REVIEW

File: packages/vite-node/src/utils.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ export function normalizeId(id: string, base?: string): string {
     .replace(/^(node|file):/, '')
     .replace(/^\/+/, '/') // remove duplicate leading slashes
     .replace(/[?&]v=\w+/, '?') // remove ?v= query
-    .replace(/\?import/, '') // remove ?import query
+    .replace(/[?&]import/, '?') // remove ?import query
```
Comment (patak-dev) [inline packages/vite-node/src/utils.ts:22]: Maybe it would be better to replace `?import` by `?` and `&import` by `&`? I don't know if having two `?` in the URL will end up confusing Vite 🤔 
```suggestion
    .replace(/([&?])(import)/,'$1') // remove ?import query
```
