### PR TITLE
fix: invalidate new worker and its dependencies (fix #1873)

### LINKED ISSUE #1873: Can't run two web worker test cases in one file
### Describe the bug

Firstly, I used `@vitest/web-worker` to simulate web worker: 
```
export default defineConfig({
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['@vitest/web-worker'],
  },
})
```
Next, I wrote two test in one file(If I only add one test, It will be OK).

```typescript
const createWorker = () => new Worker(new URL('./fibonacci', import.meta.url), {
  type: 'module'
})

test('run MyWorker first time', async () => {
  const worker = createWorker()
  const ret = await promiseWorker(worker, 10)
  expect(ret).toBe(89)
})

// The second test will print such errors:
// Error: Test timed out in 5000ms.
// If this is a long-running test, pass a timeout value as the last argument or configure it globally with "testTimeout".
test('run MyWorker second time', async () => {
  const worker = createWorker()
  const ret = await promiseWorker(worker, 10)
  expect(ret).toBe(89)
})

function promiseWorker(worker: Worker, n: number) {
  return new Promise((resolve, reject) => {
    worker.onmessage = function({data}) {
      resolve(data)
    }
    worker.onmessageerror = function({data}) {
      reject(data)
    }

    worker.onerror = function(e) {
      reject(e)
    }

    worker.postMessage(n)
  }) 
}
```

This is my `fibonacci.ts` file, If I not import `exportWorker` but inline it, the tests will all passed : 

```typescript
import exportWorker from "./exportWorker"

// If I use the `exportWorker` from ./exportWorker.ts , It will be broken.
exportWorker(fibonacci)

// If I use inline exportWorker, It will passed
// function exportWorker(fn: CallableFunction) {
//   self.onmessage = function({data}) {
//     const result = fn(data)

//     self.postMessage(result)
//   }
// }
```

### Reproduction

[vitest-web-worker-reproduction](https://github.com/mysteryven/vitest-web-worker-reproduction)

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 16.84 MB / 8.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Firefox: 80.0.1
    Safari: 15.5
  npmPackages:
    vite: ^3.0.0 => 3.0.8 
    vitest: latest => 0.22.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sun0day**
Worker and its dependencies should be invalidated every time it is created so that Worker module and its dependencies will be injected into a new `context` on the next creation.

fix #1873

Before PR:

image

After PR:

image

### CODE REVIEW

File: packages/web-worker/src/pure.ts [hunk 1]
```diff
@@ -133,11 +133,11 @@ export function defineWebWorker() {
 
       runner.executeFile(fsPath)
         .then(() => {
-          invalidates.forEach((fsPath) => {
-            // worker should be new every time
-            moduleCache.delete(fsPath)
-            moduleCache.delete(`mock:${fsPath}`)
-          })
+          // worker should be new every time, invalidate its sub dependency
```
Comment (sheremet-va) [inline packages/web-worker/src/pure.ts:136]: Currently `invalidates` is not populated, and always contains only `fsPath`, so we can just remove it's usage entirely.

**Review by sheremet-va — CHANGES_REQUESTED** [review]
Please, add a test for his use case.

File: packages/web-worker/src/pure.ts (hunk 1 above)
Comment (sun0day) [reply packages/web-worker/src/pure.ts:136]: In fact, every time vitest creates a new worker via the same URL, the `context` (or `self`) injected into the worker and its dependencies is not always up-to-date because of the `mod` cache.

So we need to clear both the worker module and its dependencies `mod` cache.

**Comment by sun0day** [comment]
> Please, add a test for this use case.

Yeah, I will add some test cases later.

File: packages/web-worker/src/pure.ts (hunk 1 above)
Comment (sun0day) [reply packages/web-worker/src/pure.ts:136]: For example:

```ts
// entry.test.ts
test('case1', async () => {
  new Worker(new URL('./worker', import.meta.url), {
    type: 'module'
  })
})

test('case2', async () => {
  new Worker(new URL('./worker', import.meta.url), {
    type: 'module'
  })
})
```

```ts
// worker.ts
import getDepSelf from './worker-dep'

console.log(getDepSelf() === self) // in case1, output is true while in case2, output is false
```

```ts
// worker-dep.ts
export default () => {
  return self
}
```

Comment (sheremet-va) [reply packages/web-worker/src/pure.ts:136]: Well, yes, I was hoping this is what this PR does, no?

Comment (sun0day) [reply packages/web-worker/src/pure.ts:136]: Yes, this PR does solve this problem

**Comment by sun0day** [comment]
> Please, add a test for this use case.

Done. @sheremet-va

File: packages/web-worker/src/pure.ts (hunk 1 above)
Comment (sheremet-va) [reply packages/web-worker/src/pure.ts:136]: Still, I don't think we need `invalidates` at all here, it is not used anywhere except to add `fsPath`. 

It's original idea was to keep track of dependencies and remove them after (what this PR does in a different way).

I was asking you to remove it

**Review by sheremet-va — CHANGES_REQUESTED** [review]

File: packages/web-worker/src/pure.ts (hunk 1 above)
Comment (sun0day) [reply packages/web-worker/src/pure.ts:136]: So you mean it's OK to use `invalidateSubDepTree` to delete the dependency mod cache, besides that I should also remove the `invalidates` usage and not use it anymore？

Comment (sheremet-va) [reply packages/web-worker/src/pure.ts:136]: Yes

Comment (sun0day) [reply packages/web-worker/src/pure.ts:132]: Done. Sorry, I didn't catch what you mean before.

**Review by sheremet-va — APPROVED** [review]
