### PR TITLE
fix: change return type of expect.any(...) to any

### LINKED ISSUE #805: expect.any(..) is of type Any instead of any
### Describe the bug

Vitest `expect.any(...)` (e.g. `expect.any(Number)`) returns something of type `Any`. In contrast, Jest returns `any` as type. So I always end up casting those `Any` to `any` in Vitest. Not a big problem, but I wonder if this is an explicit design decision?

### Reproduction

Just call `expect.any(Number)` and watch the type.

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Xeon(R) CPU @ 2.80GHz
    Memory: 5.77 GB / 62.81 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

As discussed here https://github.com/vitest-dev/vitest/discussions/804

### PR DESCRIPTION
**Pull request by TrickyPi**
Fix #805

### CODE REVIEW

File: packages/vitest/src/index.ts [hunk 1]
```diff
@@ -54,7 +54,7 @@ declare global {
       assertions(expected: number): void
       hasAssertions(): void
       anything(): Anything
```
Comment (sheremet-va) [inline packages/vitest/src/index.ts:56]: maybe we should also do `anything`?

**Review by sheremet-va — CHANGES_REQUESTED** [review]

File: packages/vitest/src/index.ts (hunk 1 above)
Comment (TrickyPi) [reply packages/vitest/src/index.ts]: Yes.

Comment (TrickyPi) [reply packages/vitest/src/index.ts]: Done.

**Review by sheremet-va — APPROVED** [review]
