### PR TITLE
 fix: don't silence reporter errors from test runtime events handler in normal run and --merge-reports

### LINKED ISSUE #9642: Reporter error is silenced when `--merge-reports`
### Describe the bug

I noticed this in https://github.com/vitest-dev/vitest/pull/9641 when I try to merge blob reporter into html reporter but html reporter was broken. There's an intentional `.catch(noop)`, but I'm not sure this is desired behavior. Perhaps, at least, it should log what's thrown? also adjust exit code?

https://github.com/vitest-dev/vitest/blob/17798daae305932a32704efb5e1643341ea05afc/packages/vitest/src/node/core.ts#L610

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-nmeth2lr?file=vite.config.ts

```js
// vite.config.ts
import { defineConfig } from 'vite';

export default defineConfig({
  test: {
    reporters: [
      {
        onTestRunStart() {
          if (process.env.CRASH_REPORTER) {
            console.log('throwing but nothing?');
            throw new Error('boom');
          }
        },
      },
    ],
  },
});
```

```sh
❯ vitest --run --reporter=blob
blob report written to /home/projects/vitest-dev-vitest-nmeth2lr/.vitest-reports/blob.json

# exit code is 0
❯ CRASH_REPORTER=1 vitest --run --merge-reports 
throwing but nothing?
```

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: latest => 4.0.18 
    vite: latest => 7.3.1 
    vitest: latest => 4.0.18
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### LINKED ISSUE #9736: Reporter errors in test runtime events callback are silenced
### Describe the bug

Related 
- https://github.com/vitest-dev/vitest/issues/9642
- https://github.com/vitest-dev/vitest/pull/9727#discussion_r2845383372

Not only `--merge-reports`, but normal test run also silences reporter errors that are thrown during test runtime event such as `onUserConsoleLog`.

- repro.test.ts

```js
import { test } from 'vitest';

test('foo', () => {
  console.log('test-crash');
});
```

- vitest.config.ts

```ts
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    reporters: [
      'default',
      {
        onUserConsoleLog(log) {
          if (log.content.includes('test-crash')) {
            console.log('throwing an error from Reporter.onUserConsoleLog!');
            throw new Error('reporter error during onUserConsoleLog');
          }
        },
      },
    ],
  },
});
```

Test finishes with no errors:

```
❯ vitest --run

 RUN  v4.1.0-beta.4 /home/projects/vitest-dev-vitest-9qgrszam

stdout | test/repro.test.ts > foo
test-crash

throwing an error from Reporter.onUserConsoleLog!
 ✓ test/repro.test.ts (1 test) 3ms
   ✓ foo 2ms

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  11:59:16
   Duration  621ms (transform 37ms, setup 0ms, import 52ms, tests 3ms, environment 0ms)
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-9qgrszam?file=vitest.config.ts

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    vitest: beta => 4.1.0-beta.4
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

- Closes https://github.com/vitest-dev/vitest/issues/9642
- Closes https://github.com/vitest-dev/vitest/issues/9736

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [ ] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Review by AriPerkkio — DISMISSED** [review]

File: packages/vitest/src/node/core.ts [hunk 1]
```diff
@@ -635,8 +635,8 @@ export class Vitest {
   /** @internal */
   public async _reportFileTask(file: File): Promise<void> {
     const project = this.getProjectByName(file.projectName || '')
-    await this._testRun.enqueued(project, file).catch(noop)
-    await this._testRun.collected(project, [file]).catch(noop)
+    await this._testRun.enqueued(project, file)
+    await this._testRun.collected(project, [file])
```
Comment (sheremet-va) [inline packages/vitest/src/node/core.ts]: I don’t think the “runtime” ones (triggered by rpc normally) should throw a hard error because they don’t do that in a normal run, I think it should be added to unhandled error instead, maybe we need a test to run in both modes

Comment (hi-ogawa) [reply packages/vitest/src/node/core.ts]: Good point. Will compare with the normal run behavior.

Comment (hi-ogawa) [reply packages/vitest/src/node/core.ts]: Created an issue https://github.com/vitest-dev/vitest/issues/9736. It looks like normal run also does silence rpc events. I'll just revert this part, then add some tests to check alignment with normal runs.

File: packages/vitest/src/runtime/rpc.ts [hunk 2]
```diff
@@ -82,8 +82,6 @@ export function createRuntimeRpc(
       },
       {
         eventNames: [
-          'onUserConsoleLog',
-          'onCollected',
```
Comment (hi-ogawa) [inline packages/vitest/src/runtime/rpc.ts:86]: This fixes https://github.com/vitest-dev/vitest/issues/9736

Only these events were escaping the error handling while other event such as `onTestModuleQueued` and `onTaskUpdate` already propagate errors. Also browser mode tester rpc doens't have `eventNames` at all, so errors are surfaced properly on browser mode.

**Review by sheremet-va — APPROVED** [review]
