### PR TITLE
fix(browser): take failure screenshot if `toMatchScreenshot` can't capture a stable screenshot

### LINKED ISSUE #9690: [Regression] Browser mode: Failure screenshot not created when unstable error occurs in v4.1.0-beta.4
### Describe the bug

Regression: In v4.1.0-beta.4, the changes from https://github.com/vitest-dev/vitest/pull/9552 (fix: don't take failure screenshot if tests have artifacts created by `toMatchScreenshot`) unintentionally prevent a failure screenshot from being captured and saved in unstable test failures.

**Problem:**
When a test fails with an unstable screenshot error (e.g., `Could not capture a stable screenshot within...`), Vitest now only provides a reference screenshot artifact. This makes it impossible to see what was actually rendered at the point of instability, hampering debugging ability. Previously, an 'internal:failureScreenshot' artifact was attached, but after this change, it is missing for these failures if any `internal:toMatchScreenshot` artifacts exist.

**Expected:**
When a test fails due to instability or any other reason that doesn't generate regular diff/actual artifacts, the failure screenshot should still be saved and attached, probably in `.vitest-attachments` folder though and not next to referenced screenshot. 

### Reproduction

Attaching minimal reproduction case

[unstable-reproduction-test.zip](https://github.com/user-attachments/files/25393333/unstable-reproduction-test.zip)

### System Info

```shell
System:
    OS: macOS 26.2
    CPU: (12) arm64 Apple M3 Pro
    Memory: 384.31 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.15.1 - /Users/smilaite/.nvm/versions/node/v22.15.1/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.9.2 - /Users/smilaite/.nvm/versions/node/v22.15.1/bin/npm
    pnpm: 9.15.2 - /Users/smilaite/Library/pnpm/pnpm
  Browsers:
    Chrome: 145.0.7632.76
    Chrome Canary: 147.0.7693.0
    Firefox: 146.0
    Safari: 26.2
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by macarie**
### Description

Resolves #9690

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [ ] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/browser/src/client/tester/expect/toMatchScreenshot.ts [hunk 1]
```diff
@@ -120,5 +120,9 @@ export default async function toMatchScreenshot(
           ]
             .filter(element => element !== null)
             .join('\n'),
+    meta: {
+      assertion: 'toMatchScreenshot',
+      outcome: result.outcome,
+    },
```
Comment (macarie) [inline packages/browser/src/client/tester/expect/toMatchScreenshot.ts:125]: Not sure if this is the best way to accomplish this, but I didn't find other ways to check source/origin of an error and to attach additional data

Comment (hi-ogawa) [reply packages/browser/src/client/tester/expect/toMatchScreenshot.ts:125]: Looks good to me, but one question. Is `assertion` here and `expectAssertionName` available in `JestExtendPlugin` always same?

https://github.com/vitest-dev/vitest/blob/fea46b3a21d8f68c81de84406d64cb1e4cf2e66a/packages/expect/src/jest-extend.ts#L80

We could always add assertion as error metadata in the plugin level, then move properties like `JestExtendError.contenxt: { assertionName, meta }`.

Comment (macarie) [reply packages/browser/src/client/tester/expect/toMatchScreenshot.ts:125]: Could definitely do that — I wasn't sure if it made sense to add it to all errors, but I guess it might be useful in the future 👍🏼

File: packages/expect/src/jest-extend.ts [hunk 2]
```diff
@@ -65,9 +65,20 @@ function getMatcherState(
...
+
   constructor(message: string, public actual?: any, public expected?: any) {
     super(message)
   }
+
+  setContext(assertionName: string, meta?: object): this {
+    this.context = { assertionName, meta }
+
+    return this
+  }
```
Comment (macarie) [inline packages/expect/src/jest-extend.ts]: Should this be the 4th constructor parameter instead?

Comment (hi-ogawa) [reply packages/expect/src/jest-extend.ts]: I think so. I was wondering `JestExtendError.constructor` is somehow public, but probably not.

Comment (macarie) [reply packages/expect/src/jest-extend.ts]: Yep, it doesn't seem to be public. It's only used in this file

**Comment by hi-ogawa** [comment]
Is this testable?

File: test/browser/specs/failure-screenshot.test.ts [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+          reporters: ['verbose'],
+          update: 'new',
+        },
+      }`,
+  })
+}
+
+describe('failure screenshots', () => {
+  describe('`toMatchScreenshot`', () => {
+    test('usually does NOT produce a failure screenshot', async () => {
```
Comment (macarie) [inline test/browser/specs/failure-screenshot.test.ts:35]: This should technically control all exit paths of the assertion, but I don't think it's worth the added time in each CI run. It might be easier to just test the cases that expect the opposite (like the one below) as the condition is quite straightforward.

Edit: since the line this comment is talking about is not clear in the UI, the subject is the test with the `usually does NOT produce a failure screenshot` description.

**Review by hi-ogawa — APPROVED** [review]

**Review by sheremet-va — APPROVED** [review]
