### PR TITLE
fix: resolving dep optimizer issues with workspace

### LINKED ISSUE #4020: deps.optimizer appears broken in 0.34.3
### Describe the bug

This is new behavior for me starting in 0.34.3. 0.34.2 works correctly for me.

If I pass dependencies to deps.optimizer.web.includes, it appears to usually work the first time, but then it fails to save the dependencies with the following error:
```
[vite] error while updating dependencies:
Error: ENOENT: no such file or directory, rename 'C:\source\test-project\node_modules\.vitest\deps_temp_c61dd53a' -> 'C:\source\test-project\node_modules\.vitest\deps'
```

And then on subsequent runs, there is a long delay before timing out and producing the following error:

```
file:///C:/source/test-project/node_modules/vite-node/dist/server.mjs:310
        throw new Error(`ViteNodeServer: ${id} not found. This is a bug, please report it.`);
        ^

Error: ViteNodeServer: C:/source/test-project/node_modules/.vitest/deps/vue.js not found. This is a bug, please report it.
    at Timeout._onTimeout (file:///C:/source/test-project/node_modules/vite-node/dist/server.mjs:310:15)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

### Reproduction

Doesn't actually appear to reproduce in stackblitz, but does reproduce for me on windows:
https://stackblitz.com/edit/vitest-dev-vitest-ycqdpe?file=vite.config.ts

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Memory: 13.28 GB / 31.64 GB
  Binaries:
    Node: 20.5.1 - ~\AppData\Local\Volta\tools\image\node\20.5.1\node.EXE
    Yarn: 3.6.1 - ~\AppData\Local\Volta\tools\image\yarn\1.22.19\bin\yarn.CMD
    npm: 9.8.0 - ~\AppData\Local\Volta\tools\image\node\20.5.1\npm.CMD
    pnpm: 8.6.12 - ~\AppData\Local\Volta\tools\image\pnpm\8.6.12\bin\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (115.0.1901.200)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-vue2: ^2.2.0 => 2.2.0
    vite: ^4.0.4 => 4.4.4
    vitest: 0.34.3 => 0.34.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by thebanjomatic**
### Description

We now use a different cache directory per project in the workspace this way we don't wind up accidentally deleting the cache directory from one project as the next one starts running.

I'm using a hash of the project name as the basis for constructing the cache sub-directory. Using a hash here is primarily done as a way to avoid sanitizing the project name to remove characters that aren't valid directory names and dealing with collisions for similarly named projects that contain invalid characters ("Foo<" and "Foo>" might both sanitize to "Foo_") for example.

A potential downside to using project name (hashed or not) is that workspaces which don't define project names for their projects will fall back to using an index as the project name. As a result, changing the order of the projects in a workspace, can result in the wrong cache directory being used.

In some ways, it might be better to do something like hash the resolved config that way order wouldn't matter, and changing the config would result in a different hash, but I don't necessarily love that approach either since it would result in more directories being created and we don't currently ever clean-up the `node_modules/.vitest` directory to remove stale project dirs.

@sheremet-va please let me know if you have a preference for the above

Fixes #4020 

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [X] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [X] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [X] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/vitest/src/node/cache/index.ts [hunk 1]
```diff
@@ -2,6 +2,7 @@ import fs from 'node:fs'
 import { findUp } from 'find-up'
 import { resolve } from 'pathe'
 import { loadConfigFromFile } from 'vite'
+import { generateHash } from '@vitest/runner/utils'
```
Comment (sheremet-va) [inline packages/vitest/src/node/cache/index.ts:5]: Runner package should not be used in node

**Review by sheremet-va — CHANGES_REQUESTED** [review]
Looks good to me 👍🏻

File: packages/vitest/src/node/cache/index.ts (hunk 1 above)
Comment (thebanjomatic) [reply packages/vitest/src/node/cache/index.ts]: Ok, providing you are still ok with hashing the project name as a solution, I have switched this to use `node:crypto` to generate an md5 hash

**Review by sheremet-va — APPROVED** [review]
