### PR TITLE
fix: define process variable and using import.meta.env together did not work

### LINKED ISSUE #3735: Functions with parameters cant find import.meta.env
### Describe the bug

When testing a function that has parameters and also utilises import.meta.env, the test will always fail as `import.meta.env` is undefined. This problem does not exist for functions that take no arguments and they resolve `import.meta.env` to an object which can be edited via `vi.stubEnv`. 

### Reproduction

This problem is very easy to reproduce. All that is needed is two functions, one take takes an argument and returns an object with the argument and some `import.meta.env` value, and one that simply has the `import.meta.env` value. This is the simple example I use to demonstrate the issue: 

```javascript
export const getDefaults = () => ({ process: '', name: 'some name', mode: import.meta.env.MODE });

export const getDefaultsWithParam = (process: string) => ({
  process,
  name: 'some name',
  mode: import.meta.env.MODE,
});
```

This needs to be tested. Create a file that covers both these functions and for each of them test that when the function is called, it returns an object that contains the correct values. For each of them have 1 attempt that does NOT stub the environment variable and one that does. 

A full working example of this can be found on [StackBlitz](https://stackblitz.com/edit/vitest-dev-vitest-fccwec?file=test%2Fexample.test.ts)

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 462.12 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.11.0 - ~/.nvm/versions/node/v18.11.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.11.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.11.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Edge: 114.0.1823.51
    Firefox: 114.0.2
    Firefox Developer Edition: 100.0
    Safari: 16.5
  npmPackages:
    @vitejs/plugin-react: ^3.1.0 => 3.1.0 
    @vitest/coverage-c8: ^0.24.5 => 0.24.5 
    @vitest/coverage-v8: ^0.32.0 => 0.32.0 
    @vitest/ui: latest => 0.32.0 
    vite: ^4.2.1 => 4.2.2 
    vitest: ^0.32.0 => 0.32.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by Dunqing**
### Description

close #3735

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [x] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Review by sheremet-va — APPROVED** [review]

**Comment by sheremet-va** [comment]
You changed your avatar, and now I don't recognize you 😄 

What do you think about also proxying the env to allow booleans while we are at it? I wrote a proxy, but didn't public it yet:

```ts
export function createImportMetaEnvProxy() {
  const booleanKeys = [
    'DEV',
    'PROD',
    'SSR',
  ]
  return new Proxy({}, {
    get(_, key) {
      if (typeof key !== 'string')
        return undefined
      if (booleanKeys.includes(key))
        return !!process.env[key]
      return process.env[key]
    },
    has(_, key) {
      if (typeof key !== 'string')
        return false
      return !!process.env[key]
    },
    set(_, key, newValue) {
      if (typeof key !== 'string')
        return true
      process.env[key] = newValue
      return true
    },
    deleteProperty(_, key) {
      if (typeof key !== 'string')
        return true
      delete process.env[key]
      return true
    },
  })
}
```

**Comment by Dunqing** [comment]
> You changed your avatar, and now I don't recognize you 😄

Haha, I'll be participating in `vitest` contributions when I have time, you'll be impressed with my new avatar!

> What do you think about also proxying the env to allow booleans while we are at it? I wrote a proxy, but didn't public it yet:
> 
> ```ts
> export function createImportMetaEnvProxy() {
>   const booleanKeys = [
>     'DEV',
>     'PROD',
>     'SSR',
>   ]
>   return new Proxy({}, {
>     get(_, key) {
>       if (typeof key !== 'string')
>         return undefined
>       if (booleanKeys.includes(key))
>         return !!process.env[key]
>       return process.env[key]
>     },
>     has(_, key) {
>       if (typeof key !== 'string')
>         return false
>       return !!process.env[key]
>     },
>     set(_, key, newValue) {
>       if (typeof key !== 'string')
>         return true
>       process.env[key] = newValue
>       return true
>     },
>     deleteProperty(_, key) {
>       if (typeof key !== 'string')
>         return true
>       delete process.env[key]
>       return true
>     },
>   })
> }
> ```

I think we should allow booleans, but this implementation is a little complicated. Look like we  just only passing `get` function

```ts
export function createImportMetaEnvProxy() {
  const booleanKeys = [
    'DEV',
    'PROD',
    'SSR',
  ]
  return new Proxy(process.env, {
    get(_, key) {
      if (typeof key !== 'string')
        return undefined
      if (booleanKeys.includes(key))
        return !!process.env[key]
      return process.env[key]
    }
  })
}
```

**Comment by sheremet-va** [comment]
> I think we should allow booleans, but this implementation is a little complicated. Look like we just only passing `get` function

I'm fine with any implementation that does the job 😄

File: packages/vite-node/src/utils.ts [hunk 1]
```diff
@@ -199,3 +199,21 @@ function traverseBetweenDirs(
...
+  ]
+  return new Proxy(process.env, {
+    get(_, key) {
+      if (typeof key !== 'string')
+        return undefined
+      if (booleanKeys.includes(key))
+        return !!process.env[key]
+      return process.env[key]
+    },
+  })
```
Comment (sheremet-va) [inline packages/vite-node/src/utils.ts:218]: With this implementation I have a question: if you set `import.meta.env.SSR = false` will it be `false` or `true`? Since `process.env` casts a value to a string, I would assume that `process.env.SSR === 'false'` which will be `true` when casted back to boolean

**Review by sheremet-va — CHANGES_REQUESTED** [review]

File: packages/vite-node/src/utils.ts (hunk 1 above)
Comment (Dunqing) [reply packages/vite-node/src/utils.ts:218]: I think it's correct now.
