### PR TITLE
fix: fix re-mocking virtual module

### LINKED ISSUE #9742: Virtual module mocking issue in Vitest 4
### Describe the bug

_This discussion is a follow-up to [this discussion](https://github.com/vitest-dev/vitest/discussions/9734) that I initially opened before this issue.__

In a test file, I have different `describe` blocks where in each of them, I mock a virtual module, e.g. using `vi.doMock()` and mock a function from that virtual module making it return different values.

The behavior seems to be different between Vitest 3 and Vitest 4:

- Vitest 3: everything seems to work as expected, and calling some code that uses that virtual module returns the mocked value.
- Vitest 4: the first mocked value seems to be returned for all tests.

### Reproduction

I've setup a minimal repro available here: https://github.com/HiDeoo/vitest-4-mock-repro

1. Clone the repository
1. Run `pnpm install`
1. Run `pnpm test`

Some tests that are checking that the expected returned mocked value is correct will fail.

A few extra notes:

- Running `pnpm add vitest@3` and `pnpm test` will make the test pass
- I tried swapping the order of `vi.resetModules()` and `vi.doMock()` as [suggested](https://github.com/vitest-dev/vitest/discussions/9734#discussioncomment-15917711) but this didn't change the behavior

### System Info

```shell
System:
    OS: macOS 26.3
    CPU: (8) arm64 Apple M1
    Memory: 197.14 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.14.0 - /Users/hideoo/.local/state/fnm_multishells/36543_1772008897917/bin/node
    npm: 10.9.2 - /Users/hideoo/.local/state/fnm_multishells/36543_1772008897917/bin/npm
    pnpm: 9.15.9 - /Users/hideoo/.local/state/fnm_multishells/36543_1772008897917/bin/pnpm
    bun: 1.3.9 - /opt/homebrew/bin/bun
  Browsers:
    Firefox: 147.0.4
    Safari: 26.3
  npmPackages:
    vitest: ^4.0.18 => 4.0.18
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

- Closes https://github.com/vitest-dev/vitest/issues/9742

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [ ] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/vitest/src/runtime/moduleRunner/startVitestModuleRunner.ts [hunk 1]
```diff
@@ -108,8 +108,8 @@ export function startVitestModuleRunner(options: ContextModuleRunnerOptions): Vi
             return {
               code: '',
               file: null,
-              id,
-              url: id,
+              id: resolvedMock.id,
+              url: resolvedMock.url,
```
Comment (hi-ogawa) [inline packages/vitest/src/runtime/moduleRunner/startVitestModuleRunner.ts:112]: For the case of virtual module, here we previously had `id = /@id/virtual-module` (aka "url") as module runner `fetchModule` result, which then leaded to `evaluatedModuleNode.id = mock:/@id/virtual-module` during later mock interception.

However, when invalidating mock for next `doMock` calls, we use `resolveId` of `virtual-module` and it tries to invalidate `mock:virtual-module`. This inconsistency makes invalidation to miss.

What this `resolvedMock` case should do instead is to return `id` as `resolvedId` of mocked module, which is already available as `resolvedMock.id`, so that is the solution here.

**Review by sheremet-va — APPROVED** [review]
