### PR TITLE
fix(jsdom): support AbortSignal API

### LINKED ISSUE #8563: Failed to execute 'addEventListener' on 'EventTarget' when passing a signal from AbortController to addEventListener - vitest@"^4.0.0-beta.10"
### Describe the bug

On the latest beta version, `"vitest": "^4.0.0-beta.10"`, when passing a signal from `new AbortController()` to `addEventListener`, vitest fails with the following error:

```tsx
function App() {
  useEffect(() => {
    const abortController = new AbortController();
    const options = {
      signal: abortController.signal,
    };
    document.addEventListener("pointerdown", () => {}, options);
  }, []);

  return <div>Hello world</div>;
}
```

```
Failed to execute 'addEventListener' on 'EventTarget': parameter 3 dictionary has member 'signal' that is not of type 'AbortSignal'.
```

Downgrading back to `3.2.4` fixes the issue. Maybe related to https://github.com/vitest-dev/vitest/pull/8390

### Reproduction

Link to repro - run `npm run test`, it should fail
https://stackblitz.com/edit/vitejs-vite-gcbbdqsx?file=src%2FApp.spec.tsx

Downgrading vitest back to latest fixes the problem

### System Info

```shell
System:
    OS: Windows 11 10.0.26100
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 6.58 GB / 31.73 GB
  Binaries:
    Node: 24.7.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    npm: 11.5.1 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (140.0.3485.54)
    Internet Explorer: 11.0.26100.1882
  npmPackages:
    @vitejs/plugin-react: ^5.0.0 => 5.0.2
    vite: ^7.1.2 => 7.1.5
    vitest: ^4.0.0-beta.10 => 4.0.0-beta.11
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
### Description

Fixes #8563

In jsdom `AbortSignal` API is used only in `addEventListener`.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [ ] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/vitest/src/integrations/env/jsdom.ts [hunk 1]
```diff
@@ -70,7 +71,10 @@ export default <Environment>{
       userAgent,
       ...restOptions,
     })
-    const clearWindowErrors = catchWindowErrors(dom.window as any)
+
+    patchAddEventListener(dom.window)
```
Comment (hi-ogawa) [inline packages/vitest/src/integrations/env/jsdom.ts]: Shouldn't this unpatch on teardown?

Comment (sheremet-va) [reply packages/vitest/src/integrations/env/jsdom.ts]: teardown removes the EventTarget from global so I don't think it needs to be unpatched

Comment (hi-ogawa) [reply packages/vitest/src/integrations/env/jsdom.ts]: Right, I wondered about that, but just in case? I'm fine either way.

Comment (sheremet-va) [reply packages/vitest/src/integrations/env/jsdom.ts]: Ok, let's add it just in case
