### PR TITLE
fix(expect): handle async errors in expect.soft

### LINKED ISSUE #8092: expect.soft does not work together with an async expectation result
### Describe the bug

When using `expect.soft(actual)` combined with a `.to<Something>` that returns an `AsyncExpectationResult`, the test gets stopped after the first failure.

Initially found this trying to use `vitest-plugin-vis` matcher `toMatchImageSnapshot` together with `expect.soft` to enable getting multiple image comparison result files for a single test case.

A little bit of research (though not sure if it would be the right place to fix things) lead me to [jest-extend.ts, line 83](https://github.com/vitest-dev/vitest/blob/main/packages/expect/src/jest-extend.ts#L85) where a promise is augmented to throw an expectation error on failure, instead of handling it similar to [wrapAssertion](https://github.com/vitest-dev/vitest/blob/main/packages/expect/src/utils.ts#L76) where the `test.result.errors` is augmented when using `expect.soft`.

### Reproduction

StackBlitz here: https://stackblitz.com/edit/vitest-dev-vitest-pvde5zau

Reproduction in basic.test.ts (two tests, comparing an async assertion with a sync one)

### System Info

```shell
Windows and linux (probably any system), with vitest 3.2.1
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by lzl0304**
### Description

Fixes #8092 

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/expect/src/utils.ts [hunk 1]
```diff
@@ -95,13 +102,18 @@ export function wrapAssertion(
     }
 
     try {
-      return fn.apply(this, args)
+      const result = fn.apply(this, args)
+
+      if (result && typeof result === 'object' && result instanceof Promise) {
```
Comment (sheremet-va) [inline packages/expect/src/utils.ts]: I thought I already fixed that, but maybe I forgot. Can you change the check from `instanceof Promise` to `typeof result.then === 'function'` here and in `jest-extend.ts`? 

And use `then(noop, (err) => { /* ... */ })` here instead

This is needed to support `PromiseLike` (we already do this in all other places except here)

**Review by sheremet-va — CHANGES_REQUESTED** [review]
Looks very good, thank you! Just one little thing

File: packages/expect/src/utils.ts (hunk 1 above)
Comment (lzl0304) [reply packages/expect/src/utils.ts]: The updates have been submitted. Thank you for your suggestion!

**Review by sheremet-va — APPROVED** [review]

**Comment by sheremet-va** [comment]
LGTM! Thank you!
