### PR TITLE
fix: fix `vi.importActual()` for virtual modules

### LINKED ISSUE #9771: `vi.importActual()` issue with virtual modules in Vitest 4
### Describe the bug

In a test file, I mock a virtual module, e.g. using `vi.mock()` and try to import the original module using either [`vi.importActual()`](https://vitest.dev/api/vi.html#vi-importactual) or the [`importOriginal()`](https://vitest.dev/api/vi.html#vi-mock) helper.

```ts
vi.mock("virtual:test", async (importOriginal) => {
  const mod = await vi.importActual<"virtual:test">("virtual:test");
  console.log("🚨 mod with vi.importActual:", mod);

  const actual = await importOriginal();
  console.log("🚨 actual with importOriginal:", actual);

  // Not doing anything here for the sake of the repro, just returning the original module.
  return mod;
});
```

The behavior seems to be different between Vitest 3 and Vitest 4:

**Vitest 3**: everything seems to work as expected, I can import the original module and get the expected value.
**Vitest 4**: both `vi.importActual()` and the `importOriginal()` helper return what seems to be an empty module (e.g. when logging the result, I get `[Object: null prototype] [Module] {}`)

### Reproduction

I've setup a minimal repro available here: https://github.com/HiDeoo/vitest-4-mock-virtual-module-importactual-repro

1. Clone the repository
1. Run pnpm install
1. Run pnpm test

Some tests that are checking the result of calling a function using the virtual module will fail.

A few extra notes:

- Running `pnpm add vitest@3` and `pnpm test` will make the test pass
- I've carefully read the Vitest 4 migration guide, and specifically the section about ["Changes to Mocking"](https://vitest.dev/guide/migration.html#changes-to-mocking), but unless I'm missing something, I don't think any of the listed changes explain this behavior.

### System Info

```shell
System:
    OS: macOS 26.3
    CPU: (8) arm64 Apple M1
    Memory: 96.19 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.14.0 - /Users/hideoo/.local/state/fnm_multishells/42034_1772463011409/bin/node
    npm: 10.9.2 - /Users/hideoo/.local/state/fnm_multishells/42034_1772463011409/bin/npm
    pnpm: 9.15.9 - /Users/hideoo/.local/state/fnm_multishells/42034_1772463011409/bin/pnpm
    bun: 1.3.10 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 145.0.7632.117
    Firefox: 148.0
    Safari: 26.3
  npmPackages:
    vitest: 4.1.0-beta.5 => 4.1.0-beta.5
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

- Closes https://github.com/vitest-dev/vitest/issues/9771

This PR changes `importActual` to use `?_vitest_original` to fetch original module code. There is already a similar technique on browser mode. Additionally for this to actually work for virtual module, it's necessary to strip `?_vitest_original` before it gets into `load` hook of virtual module. For webdriverio though, this is actually not possible because it relies on plugin pipeline `load(originalId)` to implement mocking. For others, this is possible since "original id" handling happens outside of vite plugin pipeline.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [ ] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/vitest/src/runtime/moduleRunner/startVitestModuleRunner.ts [hunk 1]
```diff
@@ -103,15 +111,17 @@ export function startVitestModuleRunner(options: ContextModuleRunnerOptions): Vi
...
+            const resolvedMock = moduleRunner.mocker.getDependencyMock(rawId)
+            if (resolvedMock?.type === 'manual' || resolvedMock?.type === 'redirect') {
+              return {
+                code: '',
+                file: null,
+                id: resolvedMock.id,
+                url: resolvedMock.url,
+                invalidate: false,
+                mockedModule: resolvedMock,
+              }
```
Comment (hi-ogawa) [inline packages/vitest/src/runtime/moduleRunner/startVitestModuleRunner.ts:124]: The issue was that previously `rawId = "virtual:module"` would get short-circuit here for both initial mocked `import "virtual:module"` and following `importOriginal` calls, which means the real code never got read by module runner.

This PR adds `?_vitest_original` query to `importOriginal`'s `fetchModule` so that it can return the real module code.

File: test/cli/test/mocking.test.ts [hunk 2]
```diff
@@ -1,8 +1,16 @@
...
-import { expect, test } from 'vitest'
+import { playwright } from '@vitest/browser-playwright'
+import { webdriverio } from '@vitest/browser-webdriverio'
+import { afterAll, expect, test } from 'vitest'
 import { rolldownVersion } from 'vitest/node'
 import { runInlineTests, runVitest } from '../../test-utils'
 
+// webdriver@9 sets dns.setDefaultResultOrder("ipv4first") on import,
+// which makes Vite resolve localhost to 127.0.0.1 and breaks other tests asserting "localhost"
+afterAll(() => setDefaultResultOrder('verbatim'))
```
Comment (hi-ogawa) [inline test/cli/test/mocking.test.ts:12]: This is needed to avoid this silly `localhost` vs `127.0.0.1` errors https://github.com/vitest-dev/vitest/actions/runs/22614377230/job/65523514606#step:8:911

```
   FAIL  test/browser-multiple.test.ts:7:1 > automatically assigns the port
  AssertionError: expected [ 'http://127.0.0.1:63315/', 'http://127.0.0.1:63316/' ] to include 'http://localhost:63315/'
   ❯ test/browser-multiple.test.ts:31:16
       29|   expect(spy).not.toHaveBeenCalled()
       30|   expect(stderr).not.toContain('is in use, trying another one...')
       31|   expect(urls).toContain('http://localhost:63315/')
         |                ^
       32|   expect(urls).toContain('http://localhost:63316/')
       33| })
```

File: packages/browser/src/node/plugin.ts [hunk 3]
```diff
@@ -49,6 +49,20 @@ export default (parentServer: ParentBrowserProject, base = '/'): Plugin[] => {
...
+            req.url?.includes('_vitest_original')
+            && parentServer.project.config.browser.provider?.name === 'playwright'
+          ) {
+            req.url = req.url
+              .replace(/[?&]_vitest_original(?=[&#]|$)/, '')
+              .replace(/[?&]ext\b[^&#]*/, '')
+              .replace(/\?$/, '')
+          }
+          next()
+        })
```
Comment (hi-ogawa) [inline packages/browser/src/node/plugin.ts:65]: Ideally this should live in playwright provider, but don't think that's possible now, so here it is.

Comment (hi-ogawa) [reply packages/browser/src/node/plugin.ts:65]: Actually instead of middleware level rewriting, it should be also possible to just strip `?_vitest_original` from `resolveId` like

```js
resolveId(source) {
  if (source.endsWith("?_vitest_original")) { 
    return source.slice(...)
  }
}
```

This is because the `source` comes here is already the resolved id + `?_vitest_original` such e.g. `"\0virtual:module?_vitest_original"`.

In fact, I used a similar idea in RSC plugin to "redirect" already resolved id back as something importable https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-rsc/src/plugins/resolved-id-proxy.ts.

**Review by sheremet-va — APPROVED** [review]
