### PR TITLE
fix(browser): remove `--remote-debugging-address` from chrome args

### LINKED ISSUE #9710: chrome doesn't support `--remote-debugging-address` anymore
### Describe the bug

Apparently Chrome now hard-codes `127.0.0.1` internally for security purpose and `--remote-debugging-address` is removed entirely. I noticed this while trying to use `--remote-debugging-address=0.0.0.0` for docker playwright without `network_mode: host` in https://github.com/vitest-dev/vitest/pull/9702

The logging here confused me, so this should be removed after confirming if any current chrome doesn't support this.

https://github.com/vitest-dev/vitest/blob/395d1a29e82dbb866383fe95b1977e72de202860/packages/browser-webdriverio/src/webdriverio.ts#L219-L226

https://github.com/vitest-dev/vitest/blob/395d1a29e82dbb866383fe95b1977e72de202860/packages/browser-playwright/src/playwright.ts#L183-L191

### Reproduction

Did quite a digging locally. Some notes based on AI collaboration.

<details><summary>🤖 Chromium DevTools bind behavior (remote debugging)</summary>

# Chromium DevTools bind behavior (remote debugging)

## Scope

This note documents Chromium/Chrome behavior for DevTools HTTP remote debugging bind address.

This is intentionally about Chromium behavior itself, not Playwright `run-server` wrapper behavior.

## Findings

1. Chromium DevTools HTTP server is implemented to bind localhost by default in both major code paths:
   - Chrome browser path: `chrome/browser/devtools/remote_debugging_server.cc`
     - [source.chromium.org: remote_debugging_server.cc](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/devtools/remote_debugging_server.cc)
   - Headless shell path: `headless/lib/browser/headless_devtools.cc`
     - [source.chromium.org: headless_devtools.cc](https://source.chromium.org/chromium/chromium/src/+/main:headless/lib/browser/headless_devtools.cc)

2. In both files, the socket factory tries:
   - `127.0.0.1`
   - then `::1`

3. The headless implementation has no handling for `--remote-debugging-address` in this path.

4. `--remote-debugging-address` was a real/legit Chromium flag historically, but support was intentionally removed in old headless:
   - Commit: `6fee475feb9bc9aaded8f9b6443d18edb22de86b`
     - [chromium.googlesource: commit 6fee475](https://chromium.googlesource.com/chromium/src/+/6fee475feb9bc9aaded8f9b6443d18edb22de86b)
   - Patch: `6fee475feb9bc9aaded8f9b6443d18edb22de86b^!`
     - [chromium.googlesource: patch 6fee475^!](https://chromium.googlesource.com/chromium/src/+/6fee475feb9bc9aaded8f9b6443d18edb22de86b%5E%21)
   - Subject: `[headless] Remove --remote-debugging-address support from old headless`
   - Rationale from commit message: unprotected remote access to CDP was considered too dangerous.

5. Practical runtime observation (container):
   - `/proc/net/tcp` showed `0100007F:240D` while debugging (`240D` = 9229), i.e. listener bound to `127.0.0.1:9229`.
   - `curl http://127.0.0.1:9229/json/list` worked inside container.
   - Host access via Docker bridge port publishing for `9229` failed/reset.

## Conclusion

For this Chromium execution path, DevTools remote debugging endpoint is loopback-bound in practice.

As a result, bridge-mode Docker `ports: "9229:9229"` is not sufficient unless traffic can reach container loopback (which it normally cannot).

`network_mode: host` works because loopback binding becomes reachable from host namespace.

Historically, this was not a hallucination: the address flag existed, but Chromium tightened behavior and removed support in relevant headless paths.

Also, Chromium CLI parsing is generally permissive, so unsupported/ignored switches are often not hard-rejected by startup.

## Evidence pointers

- Chromium source:
  - `chrome/browser/devtools/remote_debugging_server.cc`
    - [source.chromium.org: remote_debugging_server.cc](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/devtools/remote_debugging_server.cc)
  - `headless/lib/browser/headless_devtools.cc`
    - [source.chromium.org: headless_devtools.cc](https://source.chromium.org/chromium/chromium/src/+/main:headless/lib/browser/headless_devtools.cc)
  - removal commit: `6fee475feb9bc9aaded8f9b6443d18edb22de86b`
    - [chromium.googlesource: commit 6fee475](https://chromium.googlesource.com/chromium/src/+/6fee475feb9bc9aaded8f9b6443d18edb22de86b)
- Runtime check:
  - `/proc/net/tcp` entry `0100007F:240D`
  - `curl http://127.0.0.1:9229/json/list` (inside container)

</details>

### System Info

```shell
na
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

- Closes https://github.com/vitest-dev/vitest/issues/9710

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [ ] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/browser-playwright/src/playwright.ts [hunk 1]
```diff
@@ -186,9 +186,11 @@ export class PlaywrightBrowserProvider implements BrowserProvider {
 
         launchOptions.args ||= []
         launchOptions.args.push(`--remote-debugging-port=${port}`)
-        launchOptions.args.push(`--remote-debugging-address=${host}`)
 
-        this.project.vitest.logger.log(`Debugger listening on ws://${host}:${port}`)
+        if (host !== 'localhost' && host !== '127.0.0.1' && host !== '::1') {
+          this.project.vitest.logger.warn(`Custom inspector host "${host}" will be ignored. Chrome only allows remote debugging on localhost.`)
```
Comment (AriPerkkio) [inline packages/browser-playwright/src/playwright.ts]: Just to confirm - while this is Chrome security feature, it also affects Chromium that Playwright uses? 👀 

```suggestion
          this.project.vitest.logger.warn(`Custom inspector host "${host}" will be ignored. Chromium only allows remote debugging on localhost.`)
```

Comment (hi-ogawa) [reply packages/browser-playwright/src/playwright.ts]: The flag itself is gone from core chromium code base and playwright doesn't add any special patch for flag (or at least no mention in doc), so should be safe to say this.

---

Also the actual case I couldn't make 0.0.0.0 debuggin work is with playwright provider.

**Review by AriPerkkio — APPROVED** [review]
