### PR TITLE
fix: dot reporter scrollback buffer spam

### LINKED ISSUE #3384: Dot reporter spams terminal if all the dots don't fit in the given height
### Describe the bug

If the number of tests is high enough that the dot reporter can't fit all the dots on the terminal at once, it'll keep pushing lines onto stdout instead of clearing it. This also introduces some stuttering if the terminal fails to keep up with the continuous logging.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-1pwqpk?file=vite.config.ts,test%2Fbasic.test.ts&initialPath=__vitest__/

### System Info

```shell
(Stackblitz)

System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitest/ui: latest => 0.31.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by gtm-nayan**
fixes #3384

### CODE REVIEW

File: packages/vitest/src/node/reporters/renderers/dotRenderer.ts [hunk 1]
```diff
@@ -27,54 +27,68 @@ function getIcon(task: Task) {
...
+      buf += `${char.repeat(width)}\n`.repeat(Math.floor(remaining / width))
+      remaining %= width
+
+      if (remaining > 0) {
+        buf += char.repeat(remaining)
+        previousLineWidth = remaining
+      }
+      else {
+        previousLineWidth = 0
+      }
```
Comment (AriPerkkio) [inline packages/vitest/src/node/reporters/renderers/dotRenderer.ts:62]: While this works fine I found it a bit difficult to read. I had to do some refactoring to it in order to understand what exactly is happening. I came up with following refactoring in the end. Would it be more readable?

```suggestion
      let buf = `${char.repeat(availableWidth)}\n`
      const remaining = currentTasks - availableWidth

      // Add full rows first
      const fullRows = Math.floor(remaining / width)
      if (fullRows > 0)
        buf += `${char.repeat(width)}\n`.repeat(fullRows)

      // Add remaining dots which don't make a full row
      const partialRow = remaining % width
      if (partialRow > 0) {
        buf += `${char.repeat(partialRow)}`
        previousLineWidth = partialRow
      }
      else {
        previousLineWidth = 0
      }
```

**Review by AriPerkkio — CHANGES_REQUESTED** [review]
These changes also improve performance as less work is expected from `log-update`'s dependencies. I ran the examples used in https://github.com/vitest-dev/vitest/pull/3006 to verify this. About 9s to 5s. I also verified manually that the mentioned bug is fixed by these changes. Great work overall @gtm-nayan!

File: packages/vitest/src/node/reporters/renderers/dotRenderer.ts (hunk 1 above)
Comment (gtm-nayan) [reply packages/vitest/src/node/reporters/renderers/dotRenderer.ts]: Sounds good. I've pushed the suggested changes with a few tweaks.

**Review by AriPerkkio — APPROVED** [review]
