### PR TITLE
fix: update spy type inference

### LINKED ISSUE #637: type: `vi.spyOn(window.localStorage, 'getItem')` inferred as `never`
### Describe the bug

`vi.spyOn(window.localStorage, 'getItem')` is wrongly inferred as never isntead of `SpyInstance`.

```ts
tests/composables/UserService.spec.ts:58:44 - error TS2339: Property 'mockReturnValue' does not exist on type 'never'.

58     vi.spyOn(window.localStorage, 'getItem').mockReturnValue(null));
```

### Reproduction

This can be seen in the [TS playground here](https://www.typescriptlang.org/play?ssl=14&ssc=109&pln=1&pc=1#code/JYWwDg9gTgLgBAbzgN2AGjgZTATwJIB2AzjAIYEDGApnAL5wBmUEIcA5KjFSWwFC8B6AXAAmEbnAIR4FFmGAAbGgHcAFlQJwiuYAQDmcCJswxopPTQAU2nHF0MqUKFRFxSRSVWSOAlL1QAdDYA8gSWyrpiygEKEBSkCiZmFhhsFjB4XCBsPgEgcQDWAEpUMACuUAQAagllVJYEZQoKPgDc-sBBuKGWSVDmVAFgzKYwOGBUqemZVNm5+RTFpRXVtfWNzW38QnBqjlTudvDDEBNQCray4IoSRm6aEABGAFZUFDC8ssTwJMk0ALyIXhwEFwaZZSwFKg4ABcWhgUF0eh8cJIiP0cAAPpImgpEHBnOVKjjmnReLQOl0cD1fv0UuxwbMcnlCiUiasFHUGritoJhMpoAVSMwygQRHCqAAPMAKYAUYAydwfSyBEJhPoDIYjaTjSYM0ozOZuDzYfDfcjUAA8AEEnKQcJa0UiAHwYJ0Y7EbBTO+as5aVGqc9Y81pAA)

```ts
import { vi, SpyInstance } from 'vitest'

// does not compile when spying on Storage (spy inferred as never)
vi.spyOn(window.localStorage, 'getItem').mockReturnValue(null);
vi.spyOn(Storage.prototype, 'getItem').mockReturnValue(null);

// whereas it properly compiles on an object
const storage = {
    getItem(key: string): string | null { return null }
}
vi.spyOn(storage, 'getItem').mockReturnValue(null);

// workaround: explicit cast
(vi.spyOn(Storage.prototype, 'getItem') as SpyInstance<Array<string>, string | null>).mockReturnValue(null);
```

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 15.84 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.volta/tools/image/node/16.13.2/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.3.2 - ~/.volta/tools/image/npm/8.3.2/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Firefox: 96.0.2
    Safari: 15.2
  npmPackages:
    @vitejs/plugin-vue: 2.0.1 => 2.0.1
    vite: 2.7.13 => 2.7.13
    vitest: 0.2.3 => 0.2.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by DerYeger**
Closes #637.

~~I'm pretty sure this should solve the error.
If I understand the current typing correctly, a method was required to be a constructor.
This should remove that constraint.
If we do want to spy on constructors I can add another overload declaration.~~

### CODE REVIEW

File: packages/vitest/src/integrations/jest-mock.ts [hunk 1]
```diff
@@ -120,7 +120,7 @@ export function spyOn<T, G extends Properties<Required<T>>>(
 export function spyOn<T, M extends Classes<Required<T>>>(
   object: T,
   method: M
-): Required<T>[M] extends new (...args: infer A) => infer R
+): Required<T>[M] extends (...args: infer A) => infer R
```
Comment (Demivan) [inline packages/vitest/src/integrations/jest-mock.ts:123]: Wouldn't this change make this type the same as `Methods` case on line 126?

From the type info it looks like you can spy on instance methods by spying on the constructor. I'm not sure if this is the case with tinyspy.

Comment (sheremet-va) [reply packages/vitest/src/integrations/jest-mock.ts:123]: Yes, it will. Maybe we need to change the order or something

Comment (sheremet-va) [reply packages/vitest/src/integrations/jest-mock.ts:123]: For context: we didn't have this overload, but added it in some issue to mock classes. This aligns with jest and works well, since classes are functions.

Comment (sheremet-va) [reply packages/vitest/src/integrations/jest-mock.ts:123]: I think `Classes` returns incorrect types here, since the idea here is to limit overload. `never` should never happen here in theory, so conditional types wouldn't be needed.

Comment (DerYeger) [reply packages/vitest/src/integrations/jest-mock.ts:123]: I missed that part, my bad.

I'm not too familiar with TypeScript's conditional types. 
Is it possible to check if it extends a union type? Or maybe something along the lines of:
```ts
(Required<T>[M] extends (...args: infer A) => infer R) || (Required<T>[M] extends new (...args: infer A) => infer R) ? SpyInstance<A, R> : never
```

Comment (sheremet-va) [reply packages/vitest/src/integrations/jest-mock.ts:123]: > I missed that part, my bad.
> 
> I'm not too familiar with TypeScript's conditional types. Is it possible to check if it extends a union type? 

You need to chain them like so:

```ts
A extends B 
  ? B extends C 
    ? true
    : false
  : never
```
It's really ugly. But as I said it shouldn't be needed, since `M extends Classes<Required<T>>`, so `Required<T>[M]` should only contain constructors. `extends (...args: infer A) => infer R` is just a formality to get types of arguments and return type.

Comment (Demivan) [reply packages/vitest/src/integrations/jest-mock.ts]: `Classes` type is strange here. It is a dictionary of constructors for some reason. Am I missing something?

Comment (DerYeger) [reply packages/vitest/src/integrations/jest-mock.ts]: I pushed a commit that should just merge the two overloads in a backward-compatible way.

File: packages/vitest/src/integrations/jest-mock.ts [hunk 2]
```diff
@@ -117,17 +117,11 @@ export function spyOn<T, G extends Properties<Required<T>>>(
...
-): Required<T>[M] extends new (...args: infer A) => infer R
-  ? SpyInstance<A, R>
-  : never
-export function spyOn<T, M extends Methods<Required<T>>>(
+export function spyOn<T, M extends (Methods<Required<T>> | Classes<Required<T>>)>(
   obj: T,
   methodName: M,
-  mock?: T[M]
-): Required<T>[M] extends (...args: infer A) => infer R ? SpyInstance<A, R> : never
+  mock?: M extends Methods<Required<T>> ? T[M] : never
```
Comment (sheremet-va) [inline packages/vitest/src/integrations/jest-mock.ts:123]: can you remove this argument? it's not used actually.

**Review by sheremet-va — CHANGES_REQUESTED** [review]

**Comment by DerYeger** [comment]
Rebasing broke the spy test. Did something change since my initial branching?

**Comment by Demivan** [comment]
> Rebasing broke the spy test. Did something change since my initial branching?

Yes, there was a fix for #645 in tinyspy. Will check this case in tinyspy.

**Comment by sheremet-va** [comment]
Maybe this is another bug. `localStorage` and `widow.localStorage` are not the same?

I know we have a similar issue with timers. Can you try assigning `global.window` to `global`?

**Comment by DerYeger** [comment]
It worked before the rebase.

Are you sure that they are not the same using jsdom?

**Comment by Demivan** [comment]
> Are you sure that they are not the same using jsdom?

Just checked it in tinyspy repo. It works with happy-dom but not with jsdom. And it does not work even when using it without `window.`. So something actually broke.

**Comment by DerYeger** [comment]
> > Are you sure that they are not the same using jsdom?
> 
> Just checked it in tinyspy repo. It works with happy-dom but not with jsdom. And it does not work even when using it without `window.`. So something actually broke.

I'm glad that the test was useful for something else than the typecheck after all

**Comment by Demivan** [comment]
@DerYeger https://github.com/Aslemammad/tinyspy/pull/18#discussion_r794357609 - check my comment on tinyspy. We cannot mock localStorage like this.

**Comment by DerYeger** [comment]
> @DerYeger https://github.com/Aslemammad/tinyspy/pull/18#discussion_r794357609 - check my comment on tinyspy. We cannot mock localStorage like this.

Hmm, weird that it worked before

**Comment by Demivan** [comment]
tinyspy was mocking prototype but this caused other issues. As @sheremet-va stated https://github.com/Aslemammad/tinyspy/pull/18#discussion_r794366717 you can spy on the prototype explicitly.

**Comment by Demivan** [comment]
@DerYeger Can you disable that failing custom reporters test? I will look into how to write it properly later

**Comment by DerYeger** [comment]
> @DerYeger Can you disable that failing custom reporters test? I will look into how to write it properly later

Done

**Review by Demivan — APPROVED** [review]

**Review by sheremet-va — APPROVED** [review]
