### PR TITLE
fix: ensure errors keep their message and stack after `toJSON` serialisation

### LINKED ISSUE #8040: Errors with toJSON method are not formatted correctly
### Describe the bug

Vitest requires errors the override `toJSON` methods to return `message` and `stack` in the resulting object.
Without those fields present the error will not have the stack trace or the message visible in the console output.

This diverges from the standard way errors are serialized:
```js
JSON.stringify(new Error("foo")) === "{}"
```

Currently the vitest error serializer ignores `message` and `stack` properties on the error object if there's `toJSON` method defined. Instead it should inspect `message` and `stack` even if `toJSON` method is defined.

This issue is apparent when using vitest with https://effect.website/ library. Their errors have `toJSON` defined as:

```ts
toJSON() {
   return { ...this }
}
```

Using effect with vitest results in errors that have no stack traces, which is very difficult to debug.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-muksh8v1?file=test%2Ferrors.test.ts

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: latest => 3.1.4 
    vite: latest => 6.3.5 
    vitest: latest => 3.1.4
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
Fixes #8040

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/utils/src/error.ts [hunk 1]
```diff
@@ -122,15 +150,6 @@ export function processError(
...
 
-  // stack is not serialized in worker communication
-  // we stringify it first
-  if (typeof err.stack === 'string') {
-    err.stackStr = String(err.stack)
-  }
-  if (typeof err.name === 'string') {
-    err.nameStr = String(err.name)
-  }
-
```
Comment (hi-ogawa) [inline packages/utils/src/error.ts:133]: I was feeling this is mostly redundant for a long time :smile:

**Review by hi-ogawa — APPROVED** [review]

**Comment by Jinjiang** [comment]
Seems this PR [breaks](https://github.com/Jinjiang/envs-health-status/actions/runs/15455376487/job/43506523298#step:16:74) our code because we use `err.stackStr`. I understand using `err.stack` instead should fix?

**Comment by sheremet-va** [comment]
> Seems this PR [breaks](https://github.com/Jinjiang/envs-health-status/actions/runs/15455376487/job/43506523298#step:16:74) our code because we use `err.stackStr`. I understand using `err.stack` instead should fix?

Yes, use `stack`

**Comment by sheremet-va** [comment]
> Seems this PR [breaks](https://github.com/Jinjiang/envs-health-status/actions/runs/15455376487/job/43506523298#step:16:74) our code because we use `err.stackStr`. I understand using `err.stack` instead should fix?

By the way, note that Vitest 4 will remove `ErrorWithDiff` type and replace it with `TestError` (it's already available)

**Comment by Jinjiang** [comment]
I see. Good to know. Thanks.
