### PR TITLE
fix(mocker): set cache before mocking to allow circular dependencies

### LINKED ISSUE #2381: vi.mock() not working when there is an import loop
### Describe the bug

When using `vi.mock` on a module that is part of an import loop and is imported in the test there is an error displayed.

```
TypeError: default is not a function
 ❯ Module.__vite_ssr_exports__.default ../../src/index.js:8:15
```

I was debugging this for a while and only realized that this is an import loop when I saw the contents of the `moduleCache`:

```js
{
    importers: Set(1) {
      '/Users/danieltschinder/Projects/github/react-docgen/packages/react-docgen/src/utils/__tests__/getMemberValuePath-test.ts'
    },
    promise: Promise { <pending> },
    code: 'removed',
    exports: [Object: null prototype] [Module] {}
}
```

this is from `console.log(mod)` after [this line](https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/runtime/mocker.ts#L364).
So the promise is still pending, but vitest already mocks the exports which are not yet loaded.
Not sure if this helps, but that is what I found.

### Reproduction

1. `git clone https://github.com/danez-labs/vitest-default-commonjs.git`
2. npm i
3. npm test

### System Info

```shell
Tested on gitpod
  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 AMD EPYC 7B13
    Memory: 37.65 GB / 62.80 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  npmPackages:
    vite: ^3.2.4 => 3.2.4 
    vitest: ^0.25.3 => 0.25.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by danez**
Fixes #2381

This is an attempt to fix the issue described in #2381.

As suggested by @sheremet-va I removed the `moduleCache` Handling and only used `this.request`
```diff
-const mod = this.moduleCache.get(cacheKey)?.exports || await this.request(dep)
+const mod = await this.request(dep)
```

This alone did not fix the problem, as [this block](https://github.com/vitest-dev/vitest/blob/main/packages/vite-node/src/client.ts#L204-L209) kicks in for the second request to the module and at that point we already have the Module-Symbol set on exports.

In order to fix this, it is necessary to already assign an empty exports object in the module cache for the mocked module. This way the second call to `requestWithMock()` would return this empty object, which later gets filled once the first call resolves.

This also mimics [what Node.js does](https://nodejs.org/api/modules.html#modules_cycles) for circular dependencies and as long as the imported value isn't directly used in the module scope everything is fine.

### CODE REVIEW

File: packages/vitest/src/runtime/mocker.ts [hunk 1]
```diff
@@ -360,10 +360,12 @@ export class VitestMocker {
...
         return cache.exports
-      const cacheKey = toFilePath(dep, this.root)
-      const mod = this.moduleCache.get(cacheKey)?.exports || await this.request(dep)
-      const exports = this.mockObject(mod)
+
+      const exports = {}
+      // Assign the empty exports object early to allow for cycles to work. The object will be filled by mockObject()
       this.moduleCache.set(mockPath, { exports })
+      const mod = await this.request(dep)
+      this.mockObject(mod, exports)
```
Comment (danez) [inline packages/vitest/src/runtime/mocker.ts:368]: I opted to provide the exports object to `mockObject()` to prevent having to copy the object once more here.

So this could also be 
```js
Object.assign(exports, this.mockObject(mod))
```

**Review by sheremet-va — APPROVED** [review]

**Comment by sheremet-va** [comment]
Thank you!
