### PR TITLE
fix: try fix node crash

### LINKED ISSUE #319: NodeJs fatal error when running tests
### Describe the bug

When running tests on Windows I get a core dump from Node.

It is not consistent. Sometimes it works: https://github.com/fluent-vue/rollup-plugin-fluent-vue/runs/4635574629?check_suite_focus=true#step:6:17 and sometimes not: https://github.com/fluent-vue/rollup-plugin-fluent-vue/runs/4635579648?check_suite_focus=true

I don't think it is the same as https://github.com/vitest-dev/vitest/issues/317. I tried to get stack trace for that issue to compare but it didn't work.

### Reproduction

https://github.com/fluent-vue/rollup-plugin-fluent-vue

### System Info

```shell
System:
    OS: Windows 10 10.0.17763
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
    Memory: 4.99 GB / 7.00 GB
  Binaries:
    Node: 16.13.1 - C:\hostedtoolcache\windows\node\16.13.1\x64\node.EXE
    Yarn: 1.22.17 - C:\npm\prefix\yarn.CMD
    npm: 8.1.2 - C:\hostedtoolcache\windows\node\16.13.1\x64\npm.CMD
  Browsers:
    Internet Explorer: 11.0.17763.2145
  npmPackages:
    vite: ^2.7.7 => 2.7.7 
    vitest: ^0.0.114 => 0.0.114 
```

### Used Package Manager

pnpm

### Logs

```shell
https://github.com/fluent-vue/rollup-plugin-fluent-vue/runs/4635579648?check_suite_focus=true


FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.

 1: 00007FF6417E30AF v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112511
 2: 00007FF641772216 DSA_meth_get_flags+65542
 3: 00007FF6417730CD node::OnFatalError+301
 4: 00007FF6420AD5D5 v8::V8::ToLocalEmpty+53
 5: 00007FF64176A2B6 DSA_meth_get_flags+32934
 6: 00007FF64175DC1B v8::base::CPU::has_sse+42267
 7: 00007FF641845BF7 uv_timer_stop+1207
 8: 00007FF6418421CB uv_async_send+331
 9: 00007FF64184195C uv_loop_init+1292
10: 00007FF641841AFA uv_run+202
11: 00007FF641810C05 node::SpinEventLoop+309
12: 00007FF6416AB4D0 v8::internal::wasm::SignatureMap::Freeze+35776
13: 00007FF6416A6B28 v8::internal::wasm::SignatureMap::Freeze+16920
14: 00007FF6418322DD uv_poll_stop+557
15: 00007FF642643DF0 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+146416
16: 00007FFB0E117974 BaseThreadInitThunk+20
17: 00007FFB10DEA2F1 RtlUserThreadStart+33
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by Demivan**
Fixes #319

### CODE REVIEW

File: packages/vitest/src/node/cli.ts [hunk 1]
```diff
@@ -101,9 +101,6 @@ async function run(cliFilters: string[], options: UserConfig) {
     if (!ctx.config.watch)
       await ctx.close()
   }
-
-  if (!ctx.config.watch)
-    process.exit()
```
Comment (antfu) [inline packages/vitest/src/node/cli.ts:106]: If we don't have this, the process might be hanging due to unresolved side effects

**Comment by Demivan** [comment]
@antfu I was about to create pull request. :slightly_smiling_face: 
f7bdb905143946ad9a64d760d343248e23dfff1f is not enough. Terminating process causes the crash too.

File: packages/vitest/src/node/cli.ts (hunk 1 above)
Comment (Demivan) [reply packages/vitest/src/node/cli.ts:106]: Terminating the process causes the crash too

Comment (Demivan) [reply packages/vitest/src/node/cli.ts:106]: Did you have an issue with unresolved effects or this is just a precaution?

Comment (Demivan) [reply packages/vitest/src/node/cli.ts:106]: NodeJs workers are really fragile. If there anything going on inside worker (open port, file handle), terminating it causes a crash.

Comment (userquin) [reply packages/vitest/src/node/cli.ts:106]: @Demivan  With your changes windows will run ok, testing this last change (3 consecutive `nr ci` + 3 sequences alternating `pnpm run test:cli` and `pnpm run test:all`)...

Comment (antfu) [reply packages/vitest/src/node/cli.ts:106]: It could be dangerous as a hanging process will eat up all your CI time 👀. At some point, there will be some cases, but not very sure if it still applies since we migrate to workers (but there is still a non-worker mode). Could never be too prepared :P
