### PR TITLE
fix(vite-node): add ERR_MODULE_NOT_FOUND code error if module cannot be loaded

### LINKED ISSUE #6699: Dynamic import error doesn't have error code `ERR_MODULE_NOT_FOUND`
### Describe the bug

For this code:

```ts
try {
  await import('no-such-package');
} catch (e) {
  console.log('code:', e.code);
  console.log('message:', e.message);
}
```

On Node

```
❯ node src/repro.js
code: ERR_MODULE_NOT_FOUND
message: Cannot find package 'no-such-package' imported from /home/projects/vitest-dev-vitest-53av14/src/repro.js
```

On Vitest

```sh
❯ vitest

stdout | src/repro.test.js > repro
code: undefined
message: Failed to load url no-such-package (resolved id: no-such-package) in /home/projects/vitest-dev-vitest-53av14/src/repro.test.js. Does the file exist?
```

It looks like this was brought up previously in https://github.com/vitest-dev/vitest/issues/326. It doesn't throw during import analysis anymore, but dynamic import error still doesn't have `ERR_MODULE_NOT_FOUND` code (or maybe it did when it's fixed but regression).

There are some places injecting `ERR_MODULE_NOT_FOUND`, so maybe it works in some cases, but not the basic case above. https://github.com/vitest-dev/vitest/blob/5e6de2742f329b7e65fe3dff4827b5134d777009/packages/vite-node/src/client.ts#L296-L296

Vite SSR injects `ERR_MODULE_NOT_FOUND` https://github.com/vitejs/vite/blob/95020ab49e12d143262859e095025cf02423c1d9/packages/vite/src/node/ssr/fetchModule.ts#L78, so it's working there as well.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-53av14?file=src%2Frepro.test.js

### System Info

```shell
(stackblitz)

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: latest => 2.1.2 
    vite: latest => 5.4.8 
    vitest: latest => 2.1.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
### Description

Fixes #6699

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/vite-node/src/client.ts [hunk 1]
```diff
@@ -325,6 +326,25 @@ export class ViteNodeRunner {
     return await this.cachedRequest(id, fsPath, callstack)
   }
 
+  private async _fetchModule(id: string, importer?: string) {
+    try {
+      return await this.options.fetchModule(id)
+    }
+    catch (cause: any) {
+      // rethrow vitest error if it cannot load the module because it's not resolved
+      if (typeof cause?.message === 'string' && cause.message.includes('Failed to load url')) {
```
Comment (hi-ogawa) [inline packages/vite-node/src/client.ts:335]: Can this also check Vite's error code `ERR_LOAD_URL` to be more precise?
https://github.com/vitejs/vite/blob/5b0fb047b90d62b6bbabf0cc6ef03b3faa9a4810/packages/vite/src/node/server/transformRequest.ts#L334

Comment (sheremet-va) [reply packages/vite-node/src/client.ts]: Added an additional check

**Review by hi-ogawa — APPROVED** [review]
