### PR TITLE
fix: export Vitest type from 'vitest', fix #877

### LINKED ISSUE #877: `Vitest` type cannot be used with Reporter
### Describe the bug

```ts
import { Reporter } from 'vitest';
import { Vitest } from 'vitest/node';

class TestReporter implements Reporter {
  ctx!: Vitest;

  onInit(ctx: Vitest) {
    this.ctx = ctx;
  }

  onFinished() {
    this.ctx.log('hello from custom reporter');
  }
}
```
This code occurs the below type error at `onInit`.
```ts
Property 'onInit' in type 'TestReporter' is not assignable to the same property in base type 'Reporter'.
  Type '(ctx: import("stackblitz:/node_modules/vitest/dist/node").Vitest) => void' is not assignable to type '(ctx: Vitest) => void'.
```

To workaround you can obtain the `Vitest` type as below.
```ts
type Vitest = Parameters<Exclude<Reporter['onInit'], undefined>>[0]
```

I think exporting `Vitest` from `vitest` will fix this.
But exporting `Reporter` from `vitest/node` will not fix this, because `Reporter` will be incompatible with `config` type.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-p1tq8a?file=vite.config.ts&initialPath=__vitest__

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 8.38 GB / 31.93 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.24.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.62)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @vitejs/plugin-vue: ^2.2.2 => 2.2.2
    vite: ^2.8.4 => 2.8.4
    vitest: ^0.5.8 => 0.5.8
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sapphi-red**
See #877 for details.

### CODE REVIEW

File: packages/vitest/src/types/reporter.ts [hunk 1]
```diff
@@ -15,3 +15,5 @@ export interface Reporter {
 
   onUserConsoleLog?: (log: UserConsoleLog) => Awaitable<void>
 }
+
+export { Vitest }
```
Comment (antfu) [inline packages/vitest/src/types/reporter.ts:19]:
```suggestion
export type { Vitest }
```
