### PR TITLE
fix(browser): don't exclude node builtins from optimization

### LINKED ISSUE #4535: Cannot import the `url` package in browser mode
### Describe the bug

When the [`url`](https://github.com/defunctzombie/node-url) package is imported, it's not transpiled to ESM, causing the following errors:

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 2 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  a.test.js [ a.test.js ]
SyntaxError: The requested module '/node_modules/url/url.js?v=a21301ec' does not provide an export named 'parse'
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/2]⎯

 FAIL  b.test.js [ b.test.js ]
ReferenceError: require is not defined
 ❯ ../../../../..//node_modules/url/url.js:26:16

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[2/2]⎯

 Test Files  2 failed (2)
      Tests  no tests
   Start at  00:54:15
   Duration  14.49s (transform 0ms, setup 0ms, collect 0ms, tests 0ms, environment 0ms, prepare 0ms)
```

I noticed #4337, but this is not quite the same because here `url` is installed as a dependency, and is imported as `"url"` instead of `"node:url"`, I would expect it to just work like a normal package.

### Reproduction

repo: https://github.com/guansss/repro-vitest-builtin

**a.test.js**
```js
import { parse } from 'url';
import { test } from 'vitest';

test('parse', () => {
  console.log(parse('http://www.example.com'));
});
```

**b.test.js**
```js
import * as url from 'url';
import { test } from 'vitest';

test('parse', () => {
  console.log(url.parse('http://www.example.com'));
});
```

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700KF
    Memory: 18.69 GB / 31.86 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.5 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.58)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitest/browser: 1.0.0-beta.5 => 1.0.0-beta.5
    vitest: ^1.0.0-beta.5 => 1.0.0-beta.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### LINKED ISSUE #4892: loupe ... does not provide an export named 'inspect'
### Describe the bug

Experiencing this on an update to 1.1.3:

```
Error: Vitest failed to load "vitest/utils" after 10 retries.
 ❯ WebSocket.<anonymous> ../../../../../../__vitest_browser__/index-CO7GSZ7y.js:964:36

Caused by: SyntaxError: The requested module '/@fs/path/to/my/package/node_modules/.pnpm/loupe@2.3.7/node_modules/loupe/loupe.js?v=12a7f0f8' does not provide an export named 'inspect'
```

When I downgrade both `vitest` and `@vitest/browser` packages, it still somehow finds 1.1.3 and has the same issue.

I encountered similar [issues/4384](https://github.com/vitest-dev/vitest/issues/4384). I attempted to clear everything:
- New git clone
- Cleared pmpm cache

...however the issue remains. Is there something else I need to clear? Or is this a legitimate bug?

### Reproduction

Nothing exceptional in the test config:

```
test: {
  browser: {
    provider: 'playwright',
    name: 'chromium',
    enabled: true,
    headless: true,
  },
}
```

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 388.22 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.2.5 - ~/Documents/path/to/my/package/node_modules/.bin/npm
    pnpm: 8.14.0 - ~/Library/pnpm/pnpm
    bun: 1.0.3 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 17.2.1
  npmPackages:
    @vitejs/plugin-basic-ssl: ^1.0.2 => 1.0.2 
    @vitest/browser: ^1.1.3 => 1.1.3 
    vite: ^5.0.11 => 5.0.11 
    vitest: ^1.1.3 => 1.1.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### LINKED ISSUE #5046: vitest/browser fails to run when the dependent package has storybook
### Describe the bug

If a project has Storybook as a dependency, tests that used to succeed will now fail.

Test case:
```ts
import { test, expect } from "vitest";

test("sample", () => {
  expect(1 + 1).toBe(2);
});
```

Error message:
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Reload Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Vitest failed to load "vitest/utils" after 10 retries.
 ❯ WebSocket.<anonymous> ../../../../../../__vitest_browser__/index-30Y0Db8-.js:977:36

Caused by: ReferenceError: exports is not defined
 ❯ ../../../../../../node_modules/util/util.js:33:1

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 Test Files  no tests
      Tests  no tests
     Errors  1 error
   Start at  01:03:19
   Duration  3.56s (transform 0ms, setup 0ms, collect 0ms, tests 0ms, environment 0ms, prepare 0ms)


 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
Cancelling test run. Press CTRL+c again to exit forcefully.
```

### Reproduction

https://github.com/odan-sandbox/vitest-browser-issue-with-storybook

### System Info

```shell
System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 102.89 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.local/share/asdf/installs/nodejs/18.12.1/bin/node
    Yarn: 1.22.19 - ~/.local/share/asdf/installs/nodejs/18.12.1/bin/yarn
    npm: 8.19.2 - ~/.local/share/asdf/plugins/nodejs/shims/npm
    pnpm: 8.10.5 - ~/.local/share/asdf/installs/nodejs/18.12.1/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.1
  npmPackages:
    @vitest/browser: 1.2.1 => 1.2.1 
    vitest: 1.2.1 => 1.2.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
### Description

Fixes #4535
Fixes #4892

Possibly fixes #5046

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/browser/src/node/index.ts [hunk 1]
```diff
@@ -81,6 +81,13 @@ export default (project: WorkspaceProject, base = '/'): Plugin[] => {
           },
         }
       },
+      transform(code, id) {
+        if (id.includes('loupe/loupe.js')) {
```
Comment (sheremet-va) [inline packages/browser/src/node/index.ts:85]: We can just bundle `loupe` to be honest, but then we should probably bundle `chai`, but I don't see that happening 🤷🏻

**Comment by sheremet-va** [comment]
@hi-ogawa what do you think?

**Comment by hi-ogawa** [comment]
Oh, I wasn't aware that node builtins were in `optimizeDeps.exclude`. So, removing that would be necessary for people using node builtin polyfill explicitly, but what was the reason it has been added previously?

From this comment https://github.com/vitest-dev/vitest/issues/4892#issuecomment-1907879517, I thought we could simply add `vitest > @vitest/utils > loupe` to `optimizeDeps.include`. But, after adding this, I'm seeing Vite's warning locally, so this approach might still have other issues.

```
Module "util" has been externalized for browser compatibility. Cannot access "util.inspect" in client code. See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
```

---

> We don't want Vite to bundle it because it adds an import from `util` as you pointed out in one of your comments. 

What do you mean by it adds `util`?

**Comment by sheremet-va** [comment]
> So, removing that would be necessary for people using node builtin polyfill explicitly, but what was the reason it has been added previously?

We probably forgot to remove it when we provided polyfills ourselves.

> What do you mean by it adds `util`?

It transforms `require('util')` into `import from 'util'`. Instead, it should keep it as is.

File: packages/browser/src/node/index.ts (hunk 1 above)
Comment (hi-ogawa) [reply packages/browser/src/node/index.ts:85]: Just in case, can you clarify the issues with bundling `chai`?
I guess the obvious one is that it affects vitest's package size. Another one I thought about is that a user code relying on `import "chai"` would end up with different instance of `chai` from what Vitest sees internally.
Do you have anything else in mind?
