### PR TITLE
fix: fix ui mode / html reporter and coverage integration

### LINKED ISSUE #6381: Support for LCOV Reporter in Vitest UI to Improve Coverage Report Organization
### Clear and concise description of the problem

I would like to propose an enhancement to Vitest's coverage report system, specifically regarding the use of the LCOV reporter. Currently, the Vitest UI only recognizes the **HTML reporter** for displaying coverage results, which generates files directly in the root of the /coverage folder. This approach can lead to clutter and makes it harder to manage and share the reports, especially in CI/CD environments.

I suggest that Vitest should also support the **LCOV reporter in its UI**. The LCOV reporter creates the same HTML files but places them inside a dedicated **lcov-report directory** within the /coverage folder. This would result in a cleaner and more organized structure, making it easier to generate and distribute coverage reports without cluttering the root folder. 

lcov-folder

Supporting both reporter 'lcov' or 'html' would maintain compatibility while enhancing organization and usability.

### Suggested solution

LCOV reporter

- https://istanbul.js.org/docs/advanced/alternative-reporters/#lcov
- https://istanbul.js.org/docs/advanced/alternative-reporters/#html

lcov-html

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### LINKED ISSUE #6945: Coverage page is broken in the html report for @vitest/ui
### Describe the bug

When using the 'html' reporter for vitest, with the html coverage reporter also enabled, the UI contains a button to load the coverage report in an iframe, but the iframe fails to load because it is loaded from '/coverage/index.html'.

There are really two problems here.
1. By iframing in the url starting with a `/` the browser will attempt to load `http://my-host.io/coverage/index.html` regardless of the url route your report is served from. Instead, it might be preferrable to use a relative path: `http://my-host.io/report/12345/coverage/index.html` etc.
2. With the default configured options, the two reports are generated in separate directories: `./coverage` and `./html` This makes it harder to bundle all the report artifacts because they are in separate places.

Regarding #2 it would be nice if the html report directory was automatically copied into the vitest html report directory and just referenced via a relative url if the html coverage reporter is enabled. That would solve both issues at once for me without requiring extra configuration. That is my ideal fix, but I can also see the following being useful:

```
export default defineConfig({
  test: {
    coverage: {
      provider: 'v8',
      reporter: ['lcov', 'text-summary', ['html', {subdir: '../vitest-report/coverage'}]],
    },
    reporters: [['html', {outputFile: './vitest-report/index.html'}]],
  },
});
```

The above configuration correctly places the html coverage directory inside of the vitest html report directory, but the paths are not resolved correctly still, Additional work would be needed to support this:
image

Related Issue: #6144 

The above issue appears related in that they are trying to ultimately solve the same problem of the coverage not working depending on how the page is accessed or hosted, but I think the problems are deeper than what is described in the linked issue, so I created this new issue to track fixing some of those fundamental issues as at that point configuring the url to point to an externally hosted service is an orthogonal concern.

### Reproduction

Use the following vitest config on a project:
```ts
import {defineConfig} from 'vitest/config'
export default defineConfig({
  test: {
    coverage: {
      provider: 'v8',
      reporter: ['html'],
    },
    reporters: ['html'],
  },
});
```

Execute:
```bash
npx vitest run
```

Follow the instructions for previewing the test results:
```bash
npx vite preview --outDir html
```

Click the coverage button:
image

Observe that the coverage page fails to load.

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Memory: 10.12 GB / 31.64 GB
  Binaries:
    Node: 22.11.0 - ~\AppData\Local\fnm_multishells\20364_1732206955982\node.EXE
    Yarn: 4.5.1 - ~\AppData\Local\fnm_multishells\20364_1732206955982\yarn.CMD
    npm: 10.9.0 - ~\AppData\Local\fnm_multishells\20364_1732206955982\npm.CMD
    bun: 1.1.29 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @vitejs/plugin-vue: ^5.1.4 => 5.1.4
    @vitest/coverage-v8: ^2.1.2 => 2.1.3
    @vitest/ui: 2.1.3 => 2.1.3
    vite: ^5.4.8 => 5.4.10
    vitest: ^2.1.2 => 2.1.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

- Closes https://github.com/vitest-dev/vitest/issues/6945
- Closes https://github.com/vitest-dev/vitest/issues/6381
- Closes https://github.com/vitest-dev/vitest/pull/9368
- Closes https://github.com/vitest-dev/vitest/discussions/3916#discussioncomment-15759417 (Deploying html reporter under subpath)
- Closes https://github.com/vitest-dev/vitest/pull/9282

This PR simplifies how coverage HTML is served in UI mode and HTML reporter by introducing a new `coverage.htmlDir` option.

**Before:** Coverage HTML serving relied on complex path resolution from `coverage.reportsDirectory` and the `html` reporter's `subdir` option. This required `reportsDirectory` to be set as a subdirectory of the HTML report directory and also inconsistency between ui mode and html reporting.

**After:** Coverage HTML is served at a fixed `./coverage` subpath relative to the UI base. The new `coverage.htmlDir` option is automatically inferred from `html` or `lcov` coverage reporters, and can be explicitly set for custom coverage providers. This removes the directory layout constraint and makes the integration work reliably across UI mode, HTML reporter, browser mode orchestrator html.

TODO
- [x] summary
- [x] test
- [x] doc

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [ ] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/vitest/src/node/core.ts [hunk 1]
```diff
@@ -1372,10 +1371,13 @@ export class Vitest {
...
-      // notify coverage iframe reload
+      // notify builtin ui and html reporter after coverage html is generated
       for (const reporter of this.reporters) {
-        if (reporter instanceof WebSocketReporter) {
-          reporter.onFinishedReportCoverage()
+        if (
+          'onFinishedReportCoverage' in reporter
+          && typeof reporter.onFinishedReportCoverage === 'function'
+        ) {
+          await reporter.onFinishedReportCoverage()
```
Comment (hi-ogawa) [inline packages/vitest/src/node/core.ts:1387]: `reportCoverage` happens after `onTestRunEnd`, so now HTML reporter also needs this to be able to collect coverage html.

Comment (sheremet-va) [reply packages/vitest/src/node/core.ts:1387]: @AriPerkkio that's why I wanted `onCoverage` as a separate hook, by the way. We have it, but it's coupled to `onTestRunEnd`

**Review by sheremet-va — DISMISSED** [review]

File: packages/vitest/src/node/config/resolveConfig.ts [hunk 2]
```diff
@@ -430,6 +430,31 @@ export function resolveConfig(
...
+    if (resolved.coverage.htmlDir) {
+      resolved.coverage.htmlDir = resolve(
+        resolved.root,
+        resolved.coverage.htmlDir,
+      )
+    }
+
+    // infer default based on builtin reporter html output (html and lcov)
+    if (!resolved.coverage.htmlDir) {
+      const htmlReporter = resolved.coverage.reporter.find(([name]) => name === 'html')
```
Comment (AriPerkkio) [inline packages/vitest/src/node/config/resolveConfig.ts]: There's also `html-spa` if we want to support that 👀

File: docs/config/coverage.md [hunk 3]
```diff
@@ -395,3 +393,13 @@ Concurrency limit used when processing the coverage results.
...
+
+## coverage.htmlDir
+
+- **Type:** `string`
+- **Default:** Automatically inferred from `html` or `lcov` coverage reporters
+- **CLI:** `--coverage.htmlDir=<path>`
+
+Directory of HTML coverage output to be served in [Vitest UI](/guide/ui) and [HTML reporter](/guide/reporters.html#html-reporter).
+
+This is automatically configured when using builtin coverage reporters that produce HTML output (`html` and `lcov`). Use this option to override with a custom coverage reporting location when using custom coverage reporters.
```
Comment (AriPerkkio) [inline docs/config/coverage.md]: Should we also mention here that:

> ```
> Note that setting this option does not change where coverage HTML report is generated. 
> Configure the `reporter` option to change the directory instead.
> ```

**Review by AriPerkkio — DISMISSED** [review]

File: packages/vitest/src/node/config/resolveConfig.ts (hunk 2 above)
Comment (hi-ogawa) [reply packages/vitest/src/node/config/resolveConfig.ts]: Forgot about that one. Added!

**Review by AriPerkkio — APPROVED** [review]

File: packages/vitest/src/node/core.ts (hunk 1 above)
Comment (AriPerkkio) [reply packages/vitest/src/node/core.ts:1387]: Current `onCoverage` doesn't make sense in this case. Here we don't want coverage results / coverage map object. We want to know when coverage reporters have finished.

**Comment by melroy89** [comment]
After upgrading to vitest v4.1.0. I now got:


```sh
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
SystemError: Invalid src or dest: cp returned EINVAL (src and dest cannot be the same) melroy/my-project/apps/backend/test-report/coverage
 ❯ checkPaths node:internal/fs/cp/cp:80:13
 ❯ cpFn node:internal/fs/cp/cp:66:17
 ❯ HTMLReporter.onFinishedReportCoverage ../../node_modules/.pnpm/@vitest+ui@4.1.0_vitest@4.1.0/node_modules/@vitest/ui/dist/reporter.js:175:4
 ❯ Vitest.reportCoverage ../../node_modules/.pnpm/vitest@4.1.0_@types+node@24.12.0_@vitest+ui@4.1.0_jsdom@27.4.0_vite@7.3.1_@types+node@2_08ea2c2d9096821c90d54ab0e58e7b62/node_modules/vitest/dist/chunks/cli-api.DuT9iuvY.js:13755:146
 ❯ ../../node_modules/.pnpm/vitest@4.1.0_@types+node@24.12.0_@vitest+ui@4.1.0_jsdom@27.4.0_vite@7.3.1_@types+node@2_08ea2c2d9096821c90d54ab0e58e7b62/node_modules/vitest/dist/chunks/cli-api.DuT9iuvY.js:13459:6
 ❯ ../../node_modules/.pnpm/vitest@4.1.0_@types+node@24.12.0_@vitest+ui@4.1.0_jsdom@27.4.0_vite@7.3.1_@types+node@2_08ea2c2d9096821c90d54ab0e58e7b62/node_modules/vitest/dist/chunks/cli-api.DuT9iuvY.js:13468:11
 ❯ ../../node_modules/.pnpm/vitest@4.1.0_@types+node@24.12.0_@vitest+ui@4.1.0_jsdom@27.4.0_vite@7.3.1_@types+node@2_08ea2c2d9096821c90d54ab0e58e7b62/node_modules/vitest/dist/chunks/cli-api.DuT9iuvY.js:13338:19
 ❯ startVitest ../../node_modules/.pnpm/vitest@4.1.0_@types+node@24.12.0_@vitest+ui@4.1.0_jsdom@27.4.0_vite@7.3.1_@types+node@2_08ea2c2d9096821c90d54ab0e58e7b62/node_modules/vitest/dist/chunks/cli-api.DuT9iuvY.js:14380:8
 ❯ start ../../node_modules/.pnpm/vitest@4.1.0_@types+node@24.12.0_@vitest+ui@4.1.0_jsdom@27.4.0_vite@7.3.1_@types+node@2_08ea2c2d9096821c90d54ab0e58e7b62/node_modules/vitest/dist/chunks/cac.CWGDZnXT.js:2316:15
 ❯ CAC.run ../../node_modules/.pnpm/vitest@4.1.0_@types+node@24.12.0_@vitest+ui@4.1.0_jsdom@27.4.0_vite@7.3.1_@types+node@2_08ea2c2d9096821c90d54ab0e58e7b62/node_modules/vitest/dist/chunks/cac.CWGDZnXT.js:2294:2

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { code: 'ERR_FS_CP_EINVAL', info: { message: 'src and dest cannot be the same', path: 'melroy/my-project/apps/backend/test-report/coverage', syscall: 'cp', errno: 22, code: 'EINVAL' }, errno: 22, syscall: 'cp', path: 'melroy/my-project/apps/backend/test-report/coverage' }
```


Related code line: https://github.com/vitest-dev/vitest/blob/731b14440b1b5be60bbfe6e899ec5ad101f87693/packages/ui/node/reporter.ts#L164C36-L164C51


Here is part of my vitest config snippet:

```ts
    coverage: {
      enabled: true,
      provider: 'v8',
      reporter: ['text', 'text-summary', 'html'],
      reportsDirectory: './test-report/coverage',
      include: ['src/**/*.ts']
    },
    outputFile: {
      junit: './junit.xml',
      html: './test-report/index.html' <!--- This is not allowed anymore ;(, the html output should sit in a separate directory as the coverage
    },
```

The `coverage.htmlDir` is unrelated here. But VItest v4.1.0 broke the coverage report for sure.

---

I fixed it by changing the `outputFile.html`, config apparently its not allowed anymore to write to the same directory. as the coverage report.

For others that might have the same issue, I will now use:

```ts
    coverage: {
      enabled: true,
      provider: 'v8',
      reporter: ['text', 'text-summary', 'html'],
      reportsDirectory: './coverage',
      include: ['src/**/*.ts']
    },
    outputFile: {
      junit: './junit.xml',
      html: './html/index.html'
    },
```

**Comment by sheremet-va** [comment]
@melroy89 this looks like a bug in Vitest, can you raise an issue?

**Comment by hi-ogawa** [comment]
@melroy89 Can you create an issue with repro? I thought I took care of src = dest case, but probably confused myself.

**Comment by melroy89** [comment]
Maybe its not a bug but a feature..?

Since after this PR the output html files, now also contains the `coverage` directory.. Hence if we point both `coverage->reportsDirectory` and `outputFile->html` configs to the same directory, the `coverage` directory will get copied to the same location.

Hence defining two different directories for either the coverage and the html output fixes the problem. 

Repro is as simple as setting both reports to the same directory, called `same-directory` here in this `vitest.config.ts` example file.

See also: https://stackblitz.com/edit/vitest-dev-vitest-evwaapxo?file=README.md

And below:

```ts
import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    include: ['tests/**/*.test.ts'],
    exclude: ['**node_modules/**', '**.git/**', 'dist', 'build'],
    server: {
      deps: {
        inline: ['@fastify/autoload']
      }
    },
    globals: true,
    reporters: ['default', 'junit', 'html'],
    coverage: {
      enabled: true,
      provider: 'v8',
      reporter: ['text', 'text-summary', 'html'],
      reportsDirectory: './same-directory/coverage',
      include: ['src/**/*.ts']
    },
    outputFile: {
      junit: './same-directory/junit.xml',
      html: './same-directory/index.html'
    },
    environment: 'node',
    bail: 2,
    clearMocks: true
  }
})
```

`reporters: ['default', 'junit', 'html'],` ensures it triggers the html report as well. 

And the `reportsDirectory: './same-dir/coverage'` and `html: './same-dir/index.html'` triggers the "message: 'src and dest cannot be the same'" error.

**Comment by melroy89** [comment]
> @melroy89 this looks like a bug in Vitest, can you raise an issue?

Sure: https://github.com/vitest-dev/vitest/issues/9880
