### PR TITLE
fix(browser): stop the browser rpc when the pool is closed

### LINKED ISSUE #6738: workspace + browser mode + watch leave server behind when root config changes
### Describe the bug

Running `vitest` worspace (in watch mode) with a project is using browser mode.

When a root config is changed `vitest` detects the change and try to restart.
But it doesn't first kill the previous browser runner, causing eventual failure:

```sh

Restarting due to config changes...

 DEV  v2.1.3 /home/unional/code/repobuddy/storybook
      [sb] Browser runner started by playwright at http://localhost:5173/

Port 5173 is in use, trying another one...

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: [vitest-api]: Timeout calling "createTesters"
 ❯ Object.onTimeoutError node_modules/.pnpm/@vitest+browser@2.1.3_@vitest+spy@2.1.3_playwright@1.48.1_typescript@5.6.3_vite@5.4.9_@types+node@22.7.5__vitest@2.1.3/node_modules/@vitest/browser/dist/index.js:577:17
 ❯ Timeout._onTimeout node_modules/.pnpm/@vitest+browser@2.1.3_@vitest+spy@2.1.3_playwright@1.48.1_typescript@5.6.3_vite@5.4.9_@types+node@22.7.5__vitest@2.1.3/node_modules/@vitest/browser/dist/index.js:240:41
 ❯ listOnTimeout node:internal/timers:573:17
 ❯ process.processTimers node:internal/timers:514:7

 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

TBD, I have a repro but need to clean it up.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 28.36 GB / 31.31 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.10.0 - /run/user/1000/fnm_multishells/621_1729231040440/bin/node
    npm: 10.2.3 - /run/user/1000/fnm_multishells/621_1729231040440/bin/npm
    pnpm: 9.12.1 - /run/user/1000/fnm_multishells/621_1729231040440/bin/pnpm
    bun: 1.0.22 - ~/.bun/bin/bun
  npmPackages:
    @vitejs/plugin-react: ^4.3.2 => 4.3.2 
    @vitest/browser: ^2.1.3 => 2.1.3 
    vite: ^5.4.9 => 5.4.9 
    vitest: ^2.1.3 => 2.1.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sheremet-va**
### Description

Related #6738

This is not a fix, but it does make the behaviour more consistent.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by sheremet-va** [comment]
@AriPerkkio I added a `$close` method to the birpc interface some time ago. It will reject any pending calls, so we don't keep hanging promises around. It's mostly useful if the timeout is too big, but also nice when we need to stop everything I guess 🤔

File: packages/browser/src/node/pool.ts [hunk 1]
```diff
@@ -156,6 +161,11 @@ export function createBrowserPool(ctx: Vitest): ProcessPool {
     async close() {
       await Promise.all([...providers].map(provider => provider.close()))
       providers.clear()
+      ctx.resolvedProjects.forEach((project) => {
+        project.browser?.state.orchestrators.forEach((orchestrator) => {
+          orchestrator.$close()
```
Comment (AriPerkkio) [inline packages/browser/src/node/pool.ts:166]: Nice, so the `$close` is synchronous method that immediatelly closes everything?

**Review by AriPerkkio — APPROVED** [review]

**Comment by sheremet-va** [comment]
I have a feeling this will lead to some issues that were unnoticed before 😄 Let's see...
