### PR TITLE
fix(vm): fix external module resolve error with deps optimizer query

### LINKED ISSUE #9899: vmThreads/vmForks pool crashes with ERR_MODULE_NOT_FOUND when deps.optimizer.client.enabled is true
## Description

When `pool: 'vmThreads'` (or `pool: 'vmForks'`) is combined with `deps.optimizer.client.enabled: true`, every test worker crashes immediately with:

```
Error: Cannot find module '/path/to/node_modules/vitest/dist/spy.js?v=d0e9b0ac'
Serialized Error: { code: 'ERR_MODULE_NOT_FOUND' }
```

The `?v=<hash>` suffix is appended by the Vite optimizer as a cache-buster for pre-bundled modules. Node's VM module executor (used by both VM pool types) resolves modules via the filesystem and does not strip query strings from paths, so the file is never found.

The two features are therefore mutually exclusive in their current form — enabling the optimizer to speed up cold-cache CI runs prevents using VM pools to speed up local/warm runs.

---

## Reproduction

```ts
// vitest.config.ts
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'happy-dom',
    pool: 'vmThreads', // also fails with 'vmForks'
    deps: {
      optimizer: {
        client: {
          enabled: true,
          include: ['react', 'react-dom'],
        },
      },
    },
  },
});
```

```ts
// example.test.ts
import { expect, test } from 'vitest';
test('basic', () => { expect(1 + 1).toBe(2); });
```

Run:
```bash
vitest run
```

---

## Error output

```
Error: Cannot find module '/absolute/path/node_modules/vitest/dist/spy.js?v=d0e9b0ac'
  at ExternalModulesExecutor.createModule (vitest/dist/chunks/vm.D3epNOPZ.js:621:34)
  at ExternalModulesExecutor.import (vitest/dist/chunks/vm.D3epNOPZ.js:553:29)
Serialized Error: { code: 'ERR_MODULE_NOT_FOUND' }
```

The hash suffix (`?v=d0e9b0ac`) is non-deterministic — it changes per run.

---

## Root cause analysis

The Vite optimizer appends `?v=<hash>` to pre-bundled module specifiers as a cache-invalidation mechanism (see Vite source: `packages/vite/src/node/optimizer/index.ts`). When vitest's VM executor (`ExternalModulesExecutor`) tries to load vitest's own internal modules (e.g. `vitest/dist/spy.js`) that were caught up in the optimizer's module graph, it receives the path with the query string appended. Node's `vm.Module` / `createRequire` resolves strictly against the filesystem — `spy.js?v=d0e9b0ac` does not exist as a file, so resolution fails.

The `forks` pool is unaffected because it uses standard Node.js `require`/`import` in a subprocess, which goes through Vite's dev server transform pipeline where the `?v=` suffix is handled correctly.

---

## Expected behaviour

Either:
1. The VM executor strips query strings before filesystem resolution (matching how the Vite dev server handles them), or
2. Vitest's internal modules are excluded from the optimizer's module graph so they are never given a `?v=` suffix, or
3. The combination is detected at startup and a clear error is thrown explaining the incompatibility

---

## Environment

| | |
|---|---|
| vitest | 4.0.18 |
| vite | 7.3.1 |
| node | 24.12.0 |
| OS | macOS |
| pool | vmThreads / vmForks (both affected) |
| environment | happy-dom (also reproducible with jsdom) |

---

## Workaround

Use `pool: 'forks'` (the default) when `deps.optimizer.client.enabled: true`. The two features cannot be used together until this is resolved.

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

- closes https://github.com/vitest-dev/vitest/issues/9899

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [ ] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/vitest/src/runtime/external-executor.ts [hunk 1]
```diff
@@ -125,7 +125,8 @@ export class ExternalModulesExecutor {
       return { type: 'data', url: identifier, path: identifier }
     }
 
-    const extension = extname(identifier)
+    const { file, postfix } = splitFileAndPostfix(identifier)
```
Comment (hi-ogawa) [inline packages/vitest/src/runtime/external-executor.ts:128]: Added `splitFileAndPostfix` here, so later `pathUrl` won't include `?v=...`, which was the cause of `existsSync` not finding the file and causing module not found.

**Review by sheremet-va — APPROVED** [review]

**Comment by marcebdev** [comment]
Any ideas when this may release as a patch?
