### PR TITLE
fix: issue a warning in conflicting envs

### LINKED ISSUE #666: --dom -flag does not respect global config (always uses happy-dom)
### Describe the bug

I have a test suite that uses MirageJS / pretender for generating mock responses. It broke with Vitest version 0.2.1.

Full traceback:
```
 FAIL  tests/unit/ws-requests.spec.ts > test store websockets
TypeError: Cannot read properties of undefined (reading 'prototype')
 ❯ interceptor node_modules/pretender/dist/pretender.js:1540:46
 ❯ new Pretender node_modules/pretender/dist/pretender.js:1638:32
 ❯ createPretender node_modules/miragejs/dist/mirage-cjs.js:6219:12
    6217| function createPretender(server) {
    6218|   if (typeof window !== "undefined") {
    6219|     return new Pretender__default["default"](function () {
       |            ^
    6220|       this.passthroughRequest = function (verb, path, request) {
    6221|         if (server.shouldLog()) {
 ❯ Server.config node_modules/miragejs/dist/mirage-cjs.js:6623:60
 ❯ new Server node_modules/miragejs/dist/mirage-cjs.js:6417:10
 ❯ Proxy.createServer node_modules/miragejs/dist/mirage-cjs.js:6382:10
 ❯ tests/unit/ws-requests.spec.ts:22:13
```

This is the same test that broke with v0.0.138 (#475) and that was fixed in v0.0.139. It now broke with v0.2.1 (it works w/ all versions up to v0.2.0).

### Reproduction

Install latest version of miragejs and set the following config so pretender dependency works:

```
    deps: {
      inline: ['pretender'],
    },
```
Then try to use Mirage in tests

```js
import { createServer } from 'miragejs'
```

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 165.33 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Firefox: 96.0.3
    Safari: 15.2
  npmPackages:
    @vitejs/plugin-vue: ~2 => 2.1.0 
    vite: ~2.7 => 2.7.13 
    vitest: 0.2.1 => 0.2.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by Aslemammad**
Resolves #666

### CODE REVIEW

File: packages/vitest/src/node/config.ts [hunk 1]
```diff
@@ -44,8 +45,24 @@ export function resolveConfig(
...
 ): ResolvedConfig {
-  if (options.dom)
+  if (options.dom) {
+    if (
+      viteConfig.test?.environment != null
+      && viteConfig.test!.environment !== 'happy-dom'
+    ) {
+      console.warn(
+        c.yellow(
+          `${c.inverse(c.yellow(' CLI '))} Your config.test.environment ("${
```
Comment (antfu) [inline packages/vitest/src/node/config.ts:55]:
```suggestion
          `${c.inverse(c.yellow(' Vitest '))} Your config.test.environment ("${
```
