### PR TITLE
fix: use package.json name for a workspace project if not provided

### LINKED ISSUE #5607: Use unique package names for workspaces
### Clear and concise description of the problem

I set up a workspace with roughly 50 workspace packages, but I could not run all tests of the workspace because I ran into the following issue:

```
Error: Project name "client" is not unique. All projects in a workspace should have unique names.
```

A big project benefits from having similar structures in different parts of a big monorepo. So it is not surprising that packages with similar purpose end up having the same directory names.

### Suggested solution

Why not following rather the same uniqueness restrictions that already exist for package managers and hence will guarantee unique names?

The vitest workspace should identify workspace packages by the "name" property of the `package.json`.

Additionally: This will also reduce e.g. the nesting level seen in vitest VSCode plugin in the "Testing" panel.

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by sheremet-va**
### Description

Closes #5607

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/vitest/src/node/plugins/workspace.ts [hunk 1]
```diff
@@ -35,10 +36,20 @@ export function WorkspaceVitestPlugin(project: WorkspaceProject, options: Worksp
...
-            name = basename(options.workspacePath.endsWith('/') ? options.workspacePath.slice(0, -1) : dirname(options.workspacePath))
-          else
+          if (typeof options.workspacePath === 'string') {
+            // if there is a package.json, read the name from it
+            const dir = options.workspacePath.endsWith('/')
+              ? options.workspacePath.slice(0, -1)
+              : dirname(options.workspacePath)
+            const pkgJsonPath = resolve(dir, 'package.json')
+            if (existsSync(pkgJsonPath))
+              name = JSON.parse(readFileSync(pkgJsonPath, 'utf-8')).name
```
Comment (AriPerkkio) [inline packages/vitest/src/node/plugins/workspace.ts:46]: What happens when there's no `name` in `package.json`?

**Review by AriPerkkio — COMMENTED** [review]
I like the idea 👍

File: packages/vitest/src/node/plugins/workspace.ts (hunk 1 above)
Comment (sheremet-va) [reply packages/vitest/src/node/plugins/workspace.ts:46]: I did not consider that 🤔

**Review by AriPerkkio — APPROVED** [review]
