### PR TITLE
fix(coverage): workspaces c8 source maps

### LINKED ISSUE #3220: Workspaces generate inaccurate c8 coverage reports
### Describe the bug

The C8 test coverage provider reports different statistics and inaccurate line numbers when the reporter runs on a workspace. When I preview the HTML report, the code highlighted is about 10 lines offset from where the actual uncovered code is. The column number offset also appear to shift 1 or 2 characters.

### Reproduction

Vitest hangs when generating coverage in StackBlitz - I will provide a reproduction of this on GitHub when I have a chance.

### System Info

```shell
System:
    OS: macOS 12.6.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 112.97 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.local/share/homebrew/bin/node
    Yarn: 1.22.19 - ~/.local/share/homebrew/bin/yarn
    npm: 8.19.3 - ~/.local/share/homebrew/bin/npm
  Browsers:
    Firefox: 102.2.0
    Safari: 16.3
  npmPackages:
    @vitest/coverage-c8: ^0.30.1 => 0.30.1 
    vitest: ^0.30.1 => 0.30.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by AriPerkkio**
- Fixes #3220

### CODE REVIEW

File: packages/coverage-c8/src/provider.ts [hunk 1]
```diff
@@ -95,8 +95,12 @@ export class C8CoverageProvider extends BaseCoverageProvider implements Coverage
     const sourceMapMeta: Record<SourceMapMeta['url'], MapAndSource> = {}
     const extensions = Array.isArray(this.options.extension) ? this.options.extension : [this.options.extension]
 
+    const fetchCache = this.ctx.projects.map(project =>
```
Comment (sheremet-va) [inline packages/coverage-c8/src/provider.ts:98]: It's possible that one workspace transforms code not like the other workspace, so there will be several files with the same name, but they might look different (for example, one workspace tests Vue without SSR, and the other Vue with SSR). How does it handle those?

**Review by sheremet-va — CHANGES_REQUESTED** [review]

File: packages/coverage-c8/src/provider.ts (hunk 1 above)
Comment (sheremet-va) [reply packages/coverage-c8/src/provider.ts:98]: > Can you think of any other examples than Vue - something that's easy to set up?

You can create two workspace projects with custom plugins. In the first project, it will return one code, and in the second one - the other.

This can happen for node/jsdom environments for example. "node" uses SSR flag when transforming files. jsdom doesn't use SSR flag.

Comment (AriPerkkio) [reply packages/coverage-c8/src/provider.ts:98]: There's now a test case that reproduces this bug. By excluding either `space_1` or `space_3` the final coverage works OK. When both workspaces are included, the coverage of `if (a === 999 && b === 1)` breaks. 

Same bug affects `istanbul` provider as the root cause is in the reporting logic itself.  🙃

Comment (AriPerkkio) [reply packages/coverage-c8/src/provider.ts:98]: I think we can get the https://github.com/vitest-dev/vitest/issues/3220 fixed quickly with changes of 66c1b9f27a826d91f479b736d0c6a0ca58a9eeff.

But to support having different kind of code transformations in different workspace projects, and coverage mapped correctly, we would need bigger refactoring. Should that be done in separate PR and land the 66c1b9f27a826d91f479b736d0c6a0ca58a9eeff now?

Comment (sheremet-va) [reply packages/coverage-c8/src/provider.ts:98]: I think we can release the fix now, and work on bigger refactoring after that.

File: test/workspaces/coverage-report-tests/check-coverage.test.ts [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+        "covered": 3,
+        "pct": 75,
+        "skipped": 0,
+        "total": 4,
+      },
+      "functions": {
+        "covered": 2,
+        "pct": 66.66,
+        "skipped": 0,
+        "total": 3,
```
Comment (AriPerkkio) [inline test/workspaces/coverage-report-tests/check-coverage.test.ts:30]: It looks like the function count does not match. Weird that no-one has reported this issue. 
We'll need to add `/* c8 ignore next */` above each `Object.defineProperty(__vite_ssr_exports__, ...`. I'll work on that on separate PR as it's unrelated to this issue.

Comment (AriPerkkio) [reply test/workspaces/coverage-report-tests/check-coverage.test.ts:30]: Fixed in https://github.com/vitest-dev/vitest/pull/3241

**Review by sheremet-va — APPROVED** [review]
