### PR TITLE
fix: When no argument is passed to the .click interaction command, the webdriver command should also have no argument

### LINKED ISSUE #8931: Webdrivers's click should be called with undefined as the default value
### Describe the bug

I noticed that `actionClick` is used instead of `elementClick` in webdriver (context: https://github.com/webdriverio/webdriverio/blob/e86efccd84e20b01713a43113d166d8deb397edc/packages/webdriverio/src/commands/element/click.ts#L109-L121), even when passing no option.

The problem is that an empty object is passed by default in:

https://github.com/vitest-dev/vitest/blob/ab9a690a2dcc1467345e8a44541a3f11e6b8f307/packages/browser-webdriverio/src/commands/click.ts#L4-L11

I noticed that because `actionClick` was giving me other errors later (probably a webdriverio or browser issue, I'll deal with that too).

### Reproduction

I don't think that's needed

### System Info

```shell
System:
    OS: Linux 6.7 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
    Memory: 30.91 GB / 62.54 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 24.8.0 - /home/julien/.nvm/versions/node/v24.8.0/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 11.6.0 - /home/julien/.nvm/versions/node/v24.8.0/bin/npm
    pnpm: 10.9.0 - /home/julien/.local/share/pnpm/pnpm
    bun: 1.0.29 - /home/julien/.bun/bin/bun
    Deno: 2.0.0 - /home/julien/.cargo/bin/deno
    Watchman: 4.9.0 - /usr/bin/watchman
  Browsers:
    Chrome: 141.0.7390.107
    Chromium: 141.0.7390.65
    Firefox: 140.4.0esr
    Firefox Developer Edition: 140.4.0esr
  npmPackages:
    @vitest/browser-webdriverio: ^4.0.4 => 4.0.4 
    @vitest/coverage-istanbul: ^4.0.4 => 4.0.4 
    @vitest/eslint-plugin: ^1.3.26 => 1.3.26 
    vite: ^7.1.12 => 7.1.12 
    vitest: ^4.0.4 => 4.0.4 
    vitest-browser-lit: ^1.0.1 => 1.0.1 
    webdriverio: ^9.20.0 => 9.20.0
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by julienw**
Indeed webdriver.io has a different behavior when the argument is not undefined.

Fixes #8931

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [X] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [X] Ideally, include a test that fails without this PR but passes with it.
- [X] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [X] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [X] Run the tests with `pnpm test:ci`.

### Documentation
- [X] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [X] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/browser-webdriverio/src/commands/click.ts [hunk 1]
```diff
@@ -4,10 +4,10 @@ import type { UserEventCommand } from './utils'
 export const click: UserEventCommand<UserEvent['click']> = async (
   context,
   selector,
-  options = {},
+  options,
```
Comment (sheremet-va) [inline packages/browser-webdriverio/src/commands/click.ts:7]: Did you check what is passed here when `= {}` is removed? I think we always normalize it in the `browser/*/locators/index.ts`

Maybe a better test could catch that 😄

Comment (julienw) [reply packages/browser-webdriverio/src/commands/click.ts:7]: ah good question, I'll double check at least by adding logs :)

I'm not sure how to do a good test, as they should essentially do the same thing in the end ... except with more work (possibly taking longer especially).

**Comment by julienw** [comment]
FWIW this is the webdriver.io bug I was running into because of that: https://github.com/webdriverio/webdriverio/issues/14840

File: packages/browser-webdriverio/src/commands/click.ts (hunk 1 above)
Comment (julienw) [reply packages/browser-webdriverio/src/commands/click.ts:7]: or maybe I could try to mock the call to see what is _really_ called...

File: test/browser/test/userEvent.test.ts [hunk 2]
```diff
@@ -29,6 +29,10 @@ describe('userEvent.click', () => {
 
     expect(onClick).toHaveBeenCalled()
     expect(dblClick).not.toHaveBeenCalled()
+
+    onClick.mockClear()
+    await userEvent.click(button, { button: 'right' })
+    expect(onClick).toHaveBeenCalled()
```
Comment (julienw) [inline test/browser/test/userEvent.test.ts]: Can you give me some hint about how to run this test only? I couldn't find it :/

Comment (sheremet-va) [reply test/browser/test/userEvent.test.ts]: in `test/core`:

```
PROVIDER=webdriverio pnpm test-fixtures userEvent --run -t "correctly clicks a button"
```

File: packages/browser-webdriverio/src/commands/click.ts (hunk 1 above)
Comment (julienw) [reply packages/browser-webdriverio/src/commands/click.ts:7]: Yeah you're right of course:

https://github.com/vitest-dev/vitest/blob/1f730373858a7d7f49785cca5d6c45d17afc77b6/packages/browser/src/client/tester/locators/index.ts#L77

Comment (julienw) [reply packages/browser-webdriverio/src/commands/click.ts:7]: Playwright defaults to `{}` too, and the `preview` one doesn't take any option, so I guess we can remove the default everywhere.

https://github.com/microsoft/playwright/blob/e7bff526433b6dcb02801763ab5b1c6407902d47/packages/playwright-core/src/client/locator.ts#L108

File: test/browser/test/userEvent.test.ts (hunk 2 above)
Comment (julienw) [reply test/browser/test/userEvent.test.ts]: I guess you meant `test/browser` :)

I see my new test wasn't passing either, but I don't see that in the CI, are they running there?

Now I can fix all of that, thanks!

**Comment by julienw** [comment]
It's not clear to me why the tests are failing :/ I tested locally the individual files, they pass for me, but they don't seem to pass when testing the runner...

Though I'm on Linux, Linux passes too in CI, just not Windows and MacOS, so there might be something different there?

**Comment by julienw** [comment]
I reverted the changes on playwright because this wasn't related to this issue, I just wanted to make things consistent and I thought this would change nothing. But maybe I misread the playwright code. Let's see if this fixes the tests.

__Update__: this didn't fix the test.

File: packages/browser-webdriverio/src/commands/click.ts (hunk 1 above)
Comment (julienw) [reply packages/browser-webdriverio/src/commands/click.ts:7]: I checked using `WDIO_LOG_LEVEL=info` that `elementClick` is correctly called now

I don't have a good idea for a test, I think we'd be testing webdriver.io itself... and I'm also not sure how I'd correctly spy the right API.

**Comment by julienw** [comment]
By preventing the context menu from appearing when clicking right, I fixed the tests, to make new failures appear, which make more sense. I wonder if that might be a bug in Firefox...

It's still pretty weird that only macos fails, and not linux. (I don't know for windows yet) __update__: Ah of course, browser tests are not run on Ubuntu.

File: packages/browser-webdriverio/src/commands/click.ts (hunk 1 above)
Comment (sheremet-va) [reply packages/browser-webdriverio/src/commands/click.ts:7]: Sure, let's not add a new test specifically for this, but it's also important that already established tests don't fail 😄 I can see there is now only `click with modifier` on firefox failing for some reason 🤔

Comment (julienw) [reply packages/browser-webdriverio/src/commands/click.ts:7]: yeah I was looking into that too...

https://github.com/vitest-dev/vitest/blob/1f730373858a7d7f49785cca5d6c45d17afc77b6/test/browser/fixtures/user-event/keyboard.test.ts#L65-L67

I've been told from webdriver's firefox implementor that it's expected: this works with actions but not elementClick at the moment. Which is quite unfortunate :-( But they said also that they didn't implement it because the other browsers didn't either.

It's not clear to me if the test runs in Chrome to check this assumption is true? I don't see it in the test output, but also I see nothing in the file that would run it only in Firefox...

Comment (julienw) [reply packages/browser-webdriverio/src/commands/click.ts:7]: I'm thinking this could be an issue in webdriver.io too, they could/should track the keyboard and decide if they should do an elementClick or a chain of actions.

Comment (julienw) [reply packages/browser-webdriverio/src/commands/click.ts:7]: I pushed an update to fix the test. But this makes the change a breaking change, even if it's webdriver + firefox only.

Comment (julienw) [reply packages/browser-webdriverio/src/commands/click.ts:7]: I created a webdriver.io-based test to look at this:

https://github.com/julienw/webdriver-click-with-modifier/blob/ae33a2e1ff8a8697922ccbf4ec7080a5e1c81339/test/shift-click.test.js#L103-L107

It looks like there is a behavior difference in Firefox :/

Comment (julienw) [reply packages/browser-webdriverio/src/commands/click.ts:7]: https://bugzilla.mozilla.org/show_bug.cgi?id=1456642 turns out there's a bug open in Firefox, it looks like it's actively worked on these days.

Given there's an easy workaround (passing `{}` as a parameter to click), I'll leave it up to you to decide if you want to merge this.

Comment (sheremet-va) [reply packages/browser-webdriverio/src/commands/click.ts:7]: I think if we can add a documentation notice to the `click` event, it's fine to merge. The impact should not be big

Comment (julienw) [reply packages/browser-webdriverio/src/commands/click.ts:7]: I pushed some documentation, tell me if that looks like what you expected.

Comment (sheremet-va) [reply packages/browser-webdriverio/src/commands/click.ts:7]: Yeah, looks good to me, just make sure eslint doesn't fail

Comment (julienw) [reply packages/browser-webdriverio/src/commands/click.ts:7]: oh no, should be fixed now :-)

**Review by sheremet-va — APPROVED** [review]

**Comment by sheremet-va** [comment]
Thank you!

**Comment by julienw** [comment]
Thanks!

**Comment by julienw** [comment]
Is there a changelog to update about this, or will you add it to the release notes ?

**Comment by sheremet-va** [comment]
> Is there a changelog to update about this, or will you add it to the release notes ?

release notes are generated based on the squashed commit message

**Comment by julienw** [comment]
Okay, just want to make sure the folks know what to do in case they see failures because of that.

**Comment by julienw** [comment]
So this change actually avoided the bug I mentioned earlier https://github.com/webdriverio/webdriverio/issues/14840 in Firefox... but now I get a new webdriver bug in Chrome, related to a web component wrapping a button element. Nothing related to vitest IMO, but I wanted to mention it in case other folks got the issue.

**Comment by julienw** [comment]
Not related to vitest directly, but mentioning it in case this can be useful to other folks.
Using ElementClick instead of the actions like previously hits this Chrome issue sometimes: https://groups.google.com/g/chromedriver-users/c/9oxCEdNUdYg/m/7A4DIbbnAQAJ :(
