### PR TITLE
fix: replace root when resolving dependency

### LINKED ISSUE #1294: Can't mock dynamically imported packages
### Describe the bug

Scoped packages, e.g. `@wdio/logger` can't be mocked at all. In Jest it was possible to have the following structure:

```ts
__mocks__/
  - @wdio/
    - logger.ts
```

Jest would automatically pick this up.

### Reproduction

See https://stackblitz.com/edit/vitest-dev-vitest-tx14cb?file=package.json,test%2Fautomocking.spec.ts,__mocks__%2F%40wdio%2Flogger.ts&initialPath=__vitest__

I mocked out `@wdio/logger` in a way I expect Jest to work. The mocked file looks like this:
```ts
export default 'foobar';
```
In my test file (automocking.spec.ts) I do:
```ts
vi.mock('@wdio/test');
test('can automock scoped NPM package', () => {
  expect(foo).toBe('foobar');
});
```

The test failed due to:
```
can automock scoped NPM package
AssertionError: expected [Function getLogger] to be 'foobar' // Object.is equality
 - /test/automocking.spec.ts:38:41
``` 

### System Info

```shell
n/a
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by nieyuyao**
fix #1294.

the reason for this issue is that when we resolve all mocks, store them in `mockMap`. it looks like below,

```javascript
{
    '/node_modules/@wdio/logger/build/node.js': '/__mocks__/@wdio/logger.ts'
}
```

but when we actually import, the incoming path is `@wdio/logger`, it becomes `/@fs/${rootPath}/node_modules/@wdio/logger/build/node.js` after `resolveId` function. so the mock fails.

### CODE REVIEW

File: packages/vite-node/src/utils.ts [hunk 1]
```diff
@@ -8,6 +8,10 @@ export function slash(str: string) {
   return str.replace(/\\/g, '/')
 }
 
+export function mergeSlashes(str: string) {
```
Comment (sheremet-va) [inline packages/vite-node/src/utils.ts:11]: we already have this function in `utils/base.ts`

**Review by sheremet-va — CHANGES_REQUESTED** [review]

File: packages/vite-node/src/utils.ts (hunk 1 above)
Comment (sheremet-va) [reply packages/vite-node/src/utils.ts:11]: Oh, I didn't notice. I guess no, we shouldn't. Maybe sometime we can create a utils package, but not in this issue, I think

**Review by sheremet-va — APPROVED** [review]
