### PR TITLE
fix: fix suite hook throwing errors for unused auto test-scoped fixture

### LINKED ISSUE #10027: Fixture Scope Mismatch Issue
### Describe the bug

When fixtures with different scopes are used, specifically, one with a 'worker' scope and another with the default 'test' scope (and the 'auto' flag set to 'true'), the fixture with the 'worker' scope cannot be accessed or utilized within a "beforeAll" hook.

### Reproduction

```typescript
import { describe, test } from 'vitest';

const it = test
  .extend('fakeTestFixture', { auto: true }, () => {})
  .extend('fakeWorkerFixture', { scope: 'worker' }, () => {
    console.log('fakeWorkerFixture');
    return 'hello';
  });

describe('scope mismatch', () => {
  it.beforeAll(({ fakeWorkerFixture }) => {
    console.log('before all ' + fakeWorkerFixture);
  });

  it('should work', () => {});
});
```

https://stackblitz.com/edit/vitest-dev-vitest-vp84tpwo?file=test%2Fscope.test.ts,package-lock.json&initialPath=__vitest__/

### System Info

```shell
System:
    OS: macOS 26.3.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 262.59 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.10.0 - /Users/avictoor/.nvm/versions/node/v24.10.0/bin/node
    Yarn: 4.12.0 - /Users/avictoor/.nvm/versions/node/v24.10.0/bin/yarn
    npm: 11.6.1 - /Users/avictoor/.nvm/versions/node/v24.10.0/bin/npm
    bun: 1.2.4 - /Users/avictoor/.bun/bin/bun
  Browsers:
    Chrome: 146.0.7680.165
    Edge: 146.0.3856.84
    Firefox: 149.0
    Safari: 26.3.1
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

- Closes https://github.com/vitest-dev/vitest/issues/10027

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [ ] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/runner/src/fixture.ts [hunk 1]
```diff
@@ -337,7 +337,9 @@ export function withFixtures(fn: Function, options?: WithFixturesOptions) {
     const usedProps = getUsedProps(fn)
 
     for (const fixture of registrations.values()) {
-      if (fixture.auto || usedProps.has(fixture.name)) {
+      // suite hook shouldn't automatically trigger unused test-scoped fixtures
+      const auto = fixture.auto && !(options?.suiteHook && fixture.scope === 'test')
```
Comment (sheremet-va) [inline packages/runner/src/fixture.ts]: Can we make the check simpler? `fixture.auto && !(options?.suiteHook && fixture.scope === 'test')` is vile

Comment (hi-ogawa) [reply packages/runner/src/fixture.ts]: I also argued so hard with Codex :rofl:

I thought of some options and ended up with what I have now.

- `fixture.auto && !(options?.suiteHook && fixture.scope === 'test')`
- `fixture.auto && (!options?.suiteHook || fixture.scope !== 'test')`
- `fixture.auto && (options?.suiteHook ? fixture.scope !== 'test' : true)`
- `options?.suiteHook ? (fixture.auto && fixture.scope !== 'test') : fixture.auto`

I might prefer the last one actually.

Comment (hi-ogawa) [inline packages/runner/src/fixture.ts]: Yes or no 👀 

```suggestion
      const auto = options?.suiteHook ? (fixture.auto && fixture.scope !== 'test') : fixture.auto
```

Comment (sheremet-va) [reply packages/runner/src/fixture.ts]: @AriPerkkio help us 

I think we should do a multi line check

```ts
if(!fixture.auto) return false
const isSuiteScope = !!options?.suiteHook
return suiteScope ? fixture.scope !== 'test' : fixture.scope === 'test'
```

_Something_ like this

Comment (AriPerkkio) [reply packages/runner/src/fixture.ts]: > ```ts
> fixture.auto && !(options?.suiteHook && fixture.scope === 'test')
> ```

😱

I would probably write this into a fully verbose function.

```ts
function isAuto(fixture, options) {
  if (!fixture.auto) {
    return false;
  }
  
  if (options.suiteHook && fixture.scope === "test") {
    return false;
  }
  
  return true;
}
```

Comment (hi-ogawa) [reply packages/runner/src/fixture.ts]: Switched to `isAutoFixture` :oncoming_automobile:

**Review by sheremet-va — APPROVED** [review]
