### PR TITLE
fix(browser)!: iframe scale

### LINKED ISSUE #9124: page.screenshot is extremely low resolution with a large viewport
### Describe the bug

Running browser tests with playwright and `viewport: { width: 1280, height: 800 }`

This is unusable, the page is taller than 800px so everything else gets cropped off:
```
await page.viewport(600, 800)
await page.screenshot()
```

This captures the full page but #6512 scales it down to only 42px wide when the scrollHeight is 9300:
```
await page.viewport(600, document.body.scrollHeight)
await page.screenshot()
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-tszdoqkx

### System Info

```shell
System:
    OS: Linux 6.17 Ubuntu 25.10 25.10 (Questing Quokka)
    CPU: (16) x64 AMD Ryzen 7 5700X3D 8-Core Processor
    Memory: 9.52 GB / 31.27 GB
    Container: Yes
    Shell: 4.0.6 - /usr/bin/fish
  Binaries:
    Node: 24.11.1 - /run/user/1000/fnm_multishells/437459_1764264127836/bin/node
    npm: 11.6.2 - /run/user/1000/fnm_multishells/437459_1764264127836/bin/npm
    pnpm: 10.23.0 - /run/user/1000/fnm_multishells/437459_1764264127836/bin/pnpm
  Browsers:
    Chrome: 142.0.7444.175
    Firefox: 145.0.1
    Firefox Developer Edition: 145.0.1
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### LINKED ISSUE #9363: Screenshot dimensions
### Clear and concise description of the problem

I'm using the Playwright provider and trying to use screenshots for rendering tests with the following `vite.config.js` test config:
```js
{
  browser: {
    ui: true,
    provider: playwright({
      launchOptions: {
        args: ['--enable-gpu', '--force-device-scale-factor=1'],
      },
    }),
    enabled: true,
    instances: [{browser: 'chromium'}],
    viewport: {width: 512, height: 512},
  },
}
```

In my tests, I capture a screenshot with `await expect(page.elementLocator(target)).toMatchScreenshot();` and the `target` element has CSS dimensions of 512x512. The problem is that the vitest iframe with the Browser UI has an arbitrary width depending on the `--tester-transform` scale that is applied, and the screenshot dimensions are based on this scaled element's dimensions instead of dimensions that I control.

I can get tests to pass by running them in headless mode or by setting `browser.ui` to `false`. Is there an existing way to configure things so that screenshots captured using headed tests with `browser.ui` set to `true` will have a fixed or known dimension?

### Suggested solution

I'm not sure what a good solution would be. Maybe another option to disable scaling of the `tester-ui` element?
```js
{
  viewport: {width: 512, height},
  scaleViewport: false, // this would make it so tester-ui doesn't have a scale transform applied
}
```

### Alternative

_No response_

### Additional context

```
# npm ls vitest
├─┬ @vitest/browser-playwright@4.0.16
│ ├─┬ @vitest/browser@4.0.16
│ │ └── vitest@4.0.16 deduped
│ └── vitest@4.0.16 deduped
└── vitest@4.0.16
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by macarie**
### Description

Highly WIP and needs a lot of testing, but so far seems to work with Playwright with `chromium`, `firefox`, and `webkit`.

Have to look into WebdriverIO (🫣)

Fixes #9124
Fixes #9363

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [ ] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by sheremet-va** [comment]
Any news here? 👀

**Comment by macarie** [comment]
From my testing seems to be working fairly well with Playwright, but I've had no time to implement the WebdriverIO version yet. Hopefully this week 🤞🏼

File: packages/browser/src/client/orchestrator.ts [hunk 1]
```diff
@@ -312,16 +310,37 @@ export class IframeOrchestrator {
...
+      // Firefox does not support typed arithmetic (divisions between typed values): https://bugzilla.mozilla.org/show_bug.cgi?id=1264520
+      if (config.browser.name === 'firefox') {
+        // Firefox cannot resolve relative units like `cqw` directly inside `atan2()`
+        // Storing it in a CSS variable first forces Firefox to resolve `100cqw` to an absolute pixel value
+        iframe.style.setProperty('--container-width', '100cqw')
+        // `tan(atan2(a, b))` produces a unit-less `a / b` ratio:
+        //  - `atan2()` accepts two lengths and returns an `<angle>`
+        //  - `tan()` converts it back to a unit-less `<number>`
+        iframe.style.setProperty('transform', 'scale(min(1, tan(atan2(var(--container-width), var(--viewport-width)))))')
+      }
```
Comment (macarie) [inline packages/browser/src/client/orchestrator.ts]: todo: merge in an if/else block to set the properties only once with Firefox

File: test/browser/specs/to-match-screenshot.test.ts [hunk 2]
```diff
@@ -178,39 +194,76 @@ describe.runIf(provider.name === 'playwright')('--watch', () => {
...
+      vitest.resetOutput()
+      await vitest.waitForStdout(`Test Files  ${instances.length} passed`, 20_000)
+
+      if (!process.env.CI) {
+        // switch to non-headless mode
+        fs.editFile('vitest.config.js', content => content.replace('headless: true,', 'headless: false,'))
+
+        vitest.resetOutput()
+        await vitest.waitForStdout(`Test Files  ${instances.length} passed`, 20_000)
+      }
```
Comment (macarie) [inline test/browser/specs/to-match-screenshot.test.ts]: Not sure about this part running locally either, can be kinda annoying losing window focus because a browser instance opens for this test 👀

File: packages/ui/client/components/BrowserIframe.vue [hunk 3]
```diff
@@ -118,40 +76,29 @@ const marginLeft = computed(() => {
       />
       <span class="pointer-events-none" text-sm>
         {{ viewport[0] }}x{{ viewport[1] }}px
-        <span v-if="scale < 1">({{ (scale * 100).toFixed(0) }}%)</span>
```
Comment (macarie) [inline packages/ui/client/components/BrowserIframe.vue:121]: I think I can add this back now if necessary.

**Comment by macarie** [comment]
I moved the scaling part to be CSS-only, which allowed removing some JS. I think resizing the browser window and the panels now feels more fluid and less janky, especially on old(_er_) hardware.

When taking screenshots a bit of CSS is injected to remove the scaling from the iframe and making it _escape_ the pane. This should fix the "low resolution" issues, removing the scaling also leads to not having to deal with different sub pixel sizes and GPU rendering differences.

In headless mode (with no UI), Playwright now uses the set viewport, same as WebdriverIO, this should allow capturing screenshots larger than the default viewport size. In UI mode this is not done to prevent having flashing windows (more than we already have), so it's up to the user to make sure the rendered elements fit in the window.

File: packages/browser-playwright/src/commands/screenshot.ts [hunk 4]
```diff
@@ -9,6 +9,16 @@ interface ScreenshotCommandOptions extends Omit<ScreenshotOptions, 'element' | '
...
   mask?: readonly string[]
 }
+
+const SCREENSHOT_STYLES = /* css */`
+  iframe {
+    position: absolute !important;
+    inset: 0  !important;
+    z-index: ${Number.MAX_SAFE_INTEGER} !important;
+    transform: none !important;
+  }
```
Comment (macarie) [inline packages/browser-playwright/src/commands/screenshot.ts]: We might have to `opacity: 0` everything else. When the iframe doesn't have a background, the UI peeks through.

File: packages/browser-playwright/src/locators.ts [hunk 5]
```diff
@@ -155,8 +155,17 @@ function processClickOptions(options?: UserEventClickOptions) {
...
 }
 
+let scale = getIframeScale()
+
+const iframeContainer = window.frameElement?.parentElement
+
+if (iframeContainer) {
+  new ResizeObserver(() => {
+    scale = getIframeScale()
+  }).observe(iframeContainer)
```
Comment (macarie) [inline packages/browser-playwright/src/locators.ts]: These `ResizeObserver`s might not be necessary as this gets executed every time a test runs, but it might be useful in long-running tests if the user resizes the panel... Maybe it should only be enabled when UI is `true`?

Comment (sheremet-va) [reply packages/browser-playwright/src/locators.ts]: Why can't we get the scale like we did before? When action needs it, it resolves the scale

Comment (macarie) [reply packages/browser-playwright/src/locators.ts]: Thought it might be better if it's cached locally rather than getting the computed styles each time, but position clicking should also be rare enough (I'd hope at least) that this might not even matter. Would you like me to keep this as it was previously?

Comment (sheremet-va) [reply packages/browser-playwright/src/locators.ts]: Yeah, let’s just keep the previous implementation, it takes nanoseconds, there is no reason to cache it

File: packages/browser-playwright/src/commands/viewport.ts [hunk 6]
```diff
@@ -0,0 +1,11 @@
+import type { PlaywrightBrowserProvider } from '../playwright'
+import type { UserEventCommand } from './utils'
+
+export const viewport: UserEventCommand<(options: {
+  width: number
+  height: number
+}) => void> = async (context, options) => {
+  const { provider, sessionId } = context
+
+  await (provider as PlaywrightBrowserProvider).getPage(sessionId).setViewportSize(options)
```
Comment (sheremet-va) [inline packages/browser-playwright/src/commands/viewport.ts]: `page` is already available in the context

File: packages/browser-playwright/src/commands/screenshot.ts [hunk 7]
```diff
@@ -9,6 +9,16 @@ interface ScreenshotCommandOptions extends Omit<ScreenshotOptions, 'element' | '
   element?: string
   mask?: readonly string[]
 }
+
+const SCREENSHOT_STYLES = /* css */`
+  iframe {
```
Comment (sheremet-va) [inline packages/browser-playwright/src/commands/screenshot.ts]: Shouldn't this be `[data-vitest=true]`?

File: packages/ui/client/components/BrowserIframe.vue (hunk 3 above)
Comment (sheremet-va) [reply packages/ui/client/components/BrowserIframe.vue:121]: Why would we remove it? The window is still scaled

File: test/browser/specs/to-match-screenshot.test.ts [hunk 8]
```diff
@@ -25,24 +26,23 @@ test('${testName}', async ({ expect }) => {
...
     'vitest.config.js': `
-      import { playwright } from '@vitest/browser-playwright'
+      import { ${provider.name} } from '@vitest/browser-${provider.name}'
       export default {
         test: {
           browser: {
             enabled: true,
             screenshotFailures: false,
-            provider: playwright(),
+            provider: ${provider.name}(),
```
Comment (sheremet-va) [inline test/browser/specs/to-match-screenshot.test.ts]: `runInlineTests` can inject these automatically if you just pass down an object instead of a file content string (so passing down `provider` in the test will correctly specify it in the config)

File: packages/ui/client/components/BrowserIframe.vue (hunk 3 above)
Comment (macarie) [reply packages/ui/client/components/BrowserIframe.vue:121]: I removed it initially when I wasn't sure about what approach to go with. I'll add it back 👍🏼

File: packages/browser-playwright/src/commands/screenshot.ts (hunk 7 above)
Comment (macarie) [reply packages/browser-playwright/src/commands/screenshot.ts]: Yes, should be more specific. Do you prefer `data-vitest` or its `name` (or both)?

File: packages/browser-playwright/src/commands/screenshot.ts (hunk 4 above)
Comment (macarie) [reply packages/browser-playwright/src/commands/screenshot.ts]: This can be fixed by setting a background color. I'm not sure if it should change with the theme or if it should stay white tho 🤔

File: packages/browser-playwright/src/commands/screenshot.ts (hunk 7 above)
Comment (sheremet-va) [reply packages/browser-playwright/src/commands/screenshot.ts]: I think we use data-vitest everywhere in locators), but I’m not sure

File: test/browser/specs/to-match-screenshot.test.ts (hunk 2 above)
Comment (macarie) [reply test/browser/specs/to-match-screenshot.test.ts]: Removed this part.

File: packages/browser-playwright/src/commands/screenshot.ts (hunk 7 above)
Comment (macarie) [reply packages/browser-playwright/src/commands/screenshot.ts]: Used `data-vitest`, looks like it's the one that's used in some other places too.

File: packages/browser-webdriverio/src/commands/screenshot.ts [hunk 9]
```diff
@@ -59,12 +59,55 @@ export async function takeScreenshot(
   // webdriverio expects the path to contain the extension and only works with PNG files
   const savePathWithExtension = savePath.endsWith('.png') ? savePath : `${savePath}.png`
 
+  if (context.project.config.browser.ui) {
+    // refactor with `using` and `Symbol.asyncDispose` when support for Node <24 is dropped
+    await context.browser.execute(() => {
+      const document = window.frameElement?.ownerDocument
+
+      if (!document) {
+        throw new Error('cannot access parent document')
```
Comment (macarie) [inline packages/browser-webdriverio/src/commands/screenshot.ts]: todo: improve this error message (and the one beneath)

File: packages/browser/src/client/tester/tester-utils.ts [hunk 10]
```diff
@@ -224,15 +224,15 @@ export function processTimeoutOptions<T extends { timeout?: number }>(options_:
...
-  if (Number.isNaN(scale)) {
-    throw new TypeError(`Cannot parse scale value from Tester element (${scaleAttribute}). This is a bug in Vitest. Please, open a new issue with reproduction.`)
+  const iframe = window.frameElement
+
+  if (!iframe) {
+    throw new Error(`Cannot find iframe element. This is a bug in Vitest. Please, open a new issue with reproduction.`)
   }
+
+  // we can safely use `a` as both vertical and horizontal scale are the same
+  const scale = new DOMMatrix(getComputedStyle(iframe).transform).a
```
Comment (sheremet-va) [inline packages/browser/src/client/tester/tester-utils.ts:235]: Can you add an explanation (as a comment) of what is going on here? I've never seen this usage before

File: test/browser/specs/to-match-screenshot.test.ts [hunk 11]
```diff
@@ -178,39 +199,68 @@ describe.runIf(provider.name === 'playwright')('--watch', () => {
...
 
         fs.editFile(testFilename, content => content.replace(bgColor, '#000'))
 
         vitest.resetOutput()
-        await vitest.waitForStdout('Test Files  1 passed')
+        await vitest.waitForStdout(`Test Files  ${instances.length} passed`)
 
-        expect(vitest.stdout).toContain('✓ |chromium| basic.test.ts > screenshot-snapshot')
+        for (const instance of instances) {
+          expect(`✓ |${instance.browser}| basic.test.ts > screenshot-snapshot`)
```
Comment (sheremet-va) [inline test/browser/specs/to-match-screenshot.test.ts]: This doesn't test anything?

Comment (sheremet-va) [reply test/browser/specs/to-match-screenshot.test.ts]: I wonder if we should throw an error if expect was called without a matcher

File: packages/browser/src/client/tester/tester-utils.ts (hunk 10 above)
Comment (macarie) [reply packages/browser/src/client/tester/tester-utils.ts:235]: I've updated the comment, does this version explain it better? 🤔

File: test/browser/specs/to-match-screenshot.test.ts (hunk 11 above)
Comment (macarie) [reply test/browser/specs/to-match-screenshot.test.ts]: Fixed it, messed up with the multi-cursor (again) 😅

Comment (macarie) [reply test/browser/specs/to-match-screenshot.test.ts]: > I wonder if we should throw an error if expect was called without a matcher

That would be nice, or maybe a lint issue 👀

**Review by sheremet-va — COMMENTED** [review]
There are a few advanced features here. Does it change our compatibility table? https://vitest.dev/guide/browser/#browser-compatibility

**Comment by macarie** [comment]
Yeah, looks like typed-arithmetic in `calc` has been supported by all the browsers we support since September 2025 (Chromium 140, Safari 26, Firefox not yet). Using the `tan`/`atan2` version everywhere would take the support date back to 2023 (Chromium 111, Firefox 108, Safari 15.4).

I guess this would be a breaking change anyway then 🤔

**Review by sheremet-va — APPROVED** [review]
