### PR TITLE
fix(browser): allow `Locator` type in selectOptions element parameter

### LINKED ISSUE #8830: userEvent.selectOptions types do not take a Locator like said in the documentation
### Describe the bug

Hey folks,
It looks like the types for selectOptions do not accept a Locator as the documentation says on https://vitest.dev/guide/browser/interactivity-api.html#userevent-selectoptions.

### Reproduction

See the issue on [the typescript playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzmAhgcwKYBo4FcDOGUAogG4YB28AvnAGZQQhwBEAAqcDBvjAPQAjRgHdCUALRgANigCewqMDQALfgGMIVDAA8YLANwBYAFAmCRMpRgA6QlIxqYAeTAxgm-AAoTcOCmEoXMjoGNaYMABCsgBKEPaeLBogAhAp2iw4SBQoIBgAXKwAMigUaLghLHDUAJRYPqwM4gBi0Rkm1UbGQA)

### System Info

```shell
This is vitest latest v4 as downloaded by the typescript playground.
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by rzzf**
### Description

Resolves #8830

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [ ] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

File: packages/browser/context.d.ts [hunk 1]
```diff
@@ -227,7 +227,7 @@ export interface UserEvent {
    * @see {@link https://testing-library.com/docs/user-event/utility/#-selectoptions-deselectoptions} testing-library API
    */
   selectOptions: (
-    element: Element,
+    element: Element | Locator,
```
Comment (sheremet-va) [inline packages/browser/context.d.ts]:
```suggestion
    element: HTMLElement | Locator,
```

File: packages/browser/src/client/tester/context.ts [hunk 2]
```diff
@@ -169,7 +169,7 @@ function createPreviewUserEvent(userEventBase: TestingLibraryUserEvent, options:
         return option
       })
       await userEvent.selectOptions(
-        element,
+        toElement(element),
```
Comment (sheremet-va) [inline packages/browser/src/client/tester/context.ts:172]: `toElement` should not be required

**Review by sheremet-va — CHANGES_REQUESTED** [review]

File: packages/browser/src/client/tester/context.ts (hunk 2 above)
Comment (rzzf) [reply packages/browser/src/client/tester/context.ts:172]: I noticed that other similar APIs use `toElement`. If we don’t use it, TypeScript will report an error ts(2345).

Comment (sheremet-va) [reply packages/browser/src/client/tester/context.ts:172]: it shouldn't throw an error if you have `HTMLElement` in the context type

Comment (sheremet-va) [reply packages/browser/src/client/tester/context.ts:172]: Ah, wait, I see it's a different userEvent. Never mind

File: packages/browser/context.d.ts (hunk 1 above)
Comment (rzzf) [reply packages/browser/context.d.ts]: It seems we can’t assert it as HTMLElement, which causes the type error below. So I’m going to revert this change. what do you think?

https://github.com/vitest-dev/vitest/blob/0696898b4807fa9ce0fb5c00f9117bc08bf9eeb9/packages/browser-preview/src/locators.ts#L58

```shell
Argument of type 'HTMLElement | SVGElement' is not assignable to parameter of type 'HTMLElement | Locator'.
  Type 'SVGElement' is not assignable to type 'HTMLElement | Locator'.
```

Comment (sheremet-va) [reply packages/browser/context.d.ts]: The error tells you how to fix it, use `HTMLElement | SVGElement`

Comment (rzzf) [reply packages/browser/context.d.ts]: Done. Thanks!

**Review by sheremet-va — APPROVED** [review]
